### ISSUE TITLE
Streetpass Mii Plaza Savegame Editor

### ISSUE THREAD

**Issue by LaraCrofti** [marcrobledo/savegame-editors#1]
Hello, I don't know why but the Streetpass Mii Plaza Savegame Editior doesn't work anymore. Can you please fix this issue because I want to use the Editor for my Plaza. Or can you say me what the issue is????

**Comment by marcrobledo** [comment]
What is not working for you exactly?

**Comment by LaraCrofti** [comment]
When I click on "selcet file" on the side, to open the meet.dat file there comes an error: Invalid file. But there is no other file with the name meet.dat. Maybe there is an new version of the Lobby?

**Comment by LaraCrofti** [comment]
Hello, are you there? Please answer

**Comment by marcrobledo** [comment]
Can you tell me how big is your meet.dat file?
Is your StreetPass Mii Plaza updated to the latest version?

**Comment by LaraCrofti** [comment]
Yes I have the latest version of the StreetPsss Mii Plaza, and my meet.dat file have the size of 368 KB

**Comment by marcrobledo** [comment]
Upload it somewhere so I can take a look.
When did it stop working?

**Comment by LaraCrofti** [comment]
![meet](https://cloud.githubusercontent.com/assets/26163062/23580973/03e14cd8-010c-11e7-83aa-6f9282242ca8.png) I don't know if it works but if yes you must rename the meet.png back to meet.dat. If it doesn't work please tell it me and I upload it somewhere else.

**Comment by LaraCrofti** [comment]
I don't think so that it works, so I have upload it here: https://www.file-upload.net/download-12352277/meet.dat.html

**Comment by marcrobledo** [comment]
That file is blank :-( That's the reason it's not working.
Which method are you using to extract it?

**Comment by LaraCrofti** [comment]
I open the homebrew launcher by soundhax and then I open the JK's Save Manager. There I select StreetPass Mii Plaza and the Extra Data Options and at last export ExtData.

**Comment by LaraCrofti** [comment]
https://www.file-upload.net/download-12352277/meet.dat.html Is that file realy blank because when I downloade it there are 368 KB on it.

**Comment by marcrobledo** [comment]
I don't think it will work from soundhax. You need JKSM installed as CIA in order to extract system applications data.
Also, you need to extract System Save, not ExtData.

**Comment by LaraCrofti** [comment]
Ok how can I install JKSM as CIA, does it wor with version 11.2.0-36E?

**Comment by marcrobledo** [comment]
You'll need CFW, but it's not an easy process.
I can't help you on that, and this is not the place to talk about it. I close this since it's not any issue.
