### ISSUE TITLE
Pray to increase hearts & stamina ?

### ISSUE THREAD

**Issue by FimoX** [marcrobledo/savegame-editors#10]
When I try to go and pray to increase hearts & stamina, it doesn't read my "spirit orbs" counter in my save file (all non items are well integrated in the game).
Did I missed something ?

**Comment by marcrobledo** [comment]
Me and some users has tested this, and it's working correctly. How many spirit orbs did you put? You shouldn't exceed 120.

**Comment by FimoX** [comment]
I tried 10 spirits orbs but when I tried to increase my hearts/stamina, it still show my real/woned spirit orbs (shrines I won).

**Comment by FimoX** [comment]
I must have done something wrong, because that works:
https://gbatemp.net/threads/the-legend-of-zelda-breath-of-the-wild-savegame-editor.465753/page-8#post-7237454

Thank you.
