### ISSUE TITLE
Filter on text

### ISSUE THREAD

**Issue by Vidness** [marcrobledo/savegame-editors#102]
Would it be hard to filter on any of the names?  Searching for the Eventide island flags.

**Comment by marcrobledo** [comment]
This is going to be implemented in the next version, as both normal and master editor are going to be merged.

**Comment by marcrobledo** [comment]
Implemented in de1aa9fc4930727df6eef39d877ca262e4a0a46a

**Comment by Vidness** [comment]
Amazing! Donated!
