### ISSUE TITLE
[botw] ui request: section tabs, item grids

### ISSUE THREAD

**Issue by yoosefi** [marcrobledo/savegame-editors#104]
i love the editor but the amount of scrolling needed is out of hand if you have a lot of items.

my request is the editing sections be segmented with tabs, and as a bonus have the items in a grid. there is a lot of wasted horizontal space with the current row display so grids would be very nice.

**Comment by marcrobledo** [comment]
This was planned almost for an entire year, but had no time for it.

Fortunately, next version will implement it at last :-D

**Comment by marcrobledo** [comment]
GUI QoL improvements added in de1aa9f

**Comment by yoosefi** [comment]
gorgeous
