### ISSUE TITLE
BotW Save Game Editor Invalid Save?

### ISSUE THREAD

**Issue by Folacore** [marcrobledo/savegame-editors#106]
The Breath of the Wild savegame editor says my save is invalid? Not sure what's wrong with it. Any help is appreciated. I've attached a copy of my save files. I currently have version 1.15.20f and the BotW version 208 with DLC version 80. I'm also using various mods, including one that adds items to the world. Just trying to give as much info as possible to hopefully help as much as I can. Thanks!
[Save Backup.zip](https://github.com/marcrobledo/savegame-editors/files/3958684/Save.Backup.zip)
.

Edit: Added details.

**Comment by marcrobledo** [comment]
Duplicated issue #110
