### ISSUE TITLE
[BoTW][Home] "Add pins to Map" does not get saved

### ISSUE THREAD

**Issue by arvinsters2008** [marcrobledo/savegame-editors#112]
Steps:
1. Got to Home tab
2. On the "Korok seeds" row, press the "Add pins to Map" button.
3. Click Accept button on the prompt "100 pins for missing Korok seeds added to map".
4. Click Save Changes button on the top-right corner.
5. Save the file on your PC.
6. Refresh the page.
7. Open the save file you saved on Step 5.

Expected result:
- Map pins counter should display 0
- Korok seeds pins should be visible in the Map (IN GAME)

Actual result:
- Map pins counter displays 0
- Korok seeds locations was not pinned in the Map (IN GAME)

Note:
Function was last working on the previous version.
This was also tested when restoring the save file to the game.

**Comment by marcrobledo** [comment]
Fixed in afa2dba.
Thanks for reporting.
