### ISSUE TITLE
Save File not working

### ISSUE THREAD

**Issue by neelo2** [marcrobledo/savegame-editors#116]
Hi i have cfw. I put the meet file in the save editor and when finishng the save and saving it, and going in jksm to get the file in the street pass, it says error loading archive and crashes.

**Comment by marcrobledo** [comment]
That sounds like an issue in your side, not the editor. Make sure you are replacing the old file and not creating a new one.

**Comment by neelo2** [comment]
I did replace the old save file, but once i import from jksm it corrupts the whole street pass. I know i am replacing it due to the fact that i see my current street pass tags, plaza tickets, etc
