### ISSUE TITLE
Rhythm Paradise Megamix Save Editor: Save file is reset to the opening tutorial sequence. Once I pass it and the first world starts loading, the game crashes

### ISSUE THREAD

**Issue by lendunistus** [marcrobledo/savegame-editors#119]
Hello! I found this editor and I used it to get max flow balls.

After I restored my new save file using Checkpoint, the file select screen looked as it did before (my Mii and my Flow were still there). However, when I loaded it, I was sent to the opening tutorial sequence that you get when starting the game from a new save file. The controls were set to Simple Tap as well for some reason. I went through it (the weird thing was that all the mascots that I obtained from the goat were still there) and when it got to loading the first world, the game crashed.

I can provide the crash dump file if asked.

Thanks!

**Comment by marcrobledo** [comment]
I've tested it. The editor works perfectly, only edits a single byte.

Can you post here both your original and you hacked savegame? I need to take a look at its differences.

**Comment by lendunistus** [comment]
For some reason, when I went to load my original save, that one also had the same error. My guess is that FTP must have messed up the savefiles somehow (since I was using that to transfer the savegames).

I only have the bugged save file right now, which is in this pastebin: https://pastebin.com/ZLQZJDfd

I don’t currently have access to an SD card reader.

**Comment by marcrobledo** [comment]
I think I know what's happening.
Rhythm Paradise Megamix savegame has a txt extension, but it's not plain text. Most FTP clients transfer .txt files as ASCII instead of Binary automatically, that will mess up the whole file.

Always transfer savegames (regardless of their extension) as Binary. Check your FTP client settings.

**Comment by lendunistus** [comment]
I deleted the original save file off my SD so RIP I guess :(

I’ll be more careful when messing with save files now. Thanks for the help!

**Comment by lendunistus** [comment]
Okay, now I have access to a computer so I attempted to edit my original savegame. However, when I downloaded it (as Binary) and attempted to use it, I got an invalid savegame error. A picture of my WinSCP window and the downloaded savegame are both attached.
[savedataArc.txt](https://github.com/marcrobledo/savegame-editors/files/4842018/savedataArc.txt)

![pilt](https://user-images.githubusercontent.com/53618962/85943882-9effe180-b93b-11ea-931a-c828936e8c6c.png)

**Comment by marcrobledo** [comment]
For some reason, your savegame has six additional blank bytes at the end. The savegame must be exactly 30040 bytes, and yours is 30046. Removing those bytes makes it compatible with the editor. Your FTP server and/or client are modifying the file before/after transfering. I wouldn't trust that software. Make sure that even if you set mode to Binary, there isn't defined an automatic ASCII mode for .txt files in settings.

Anyway, this is not an issue of the editor itself, I'll close this one. If you need more help, please contact me at Twitter DM.
