### ISSUE TITLE
How do I get the modified file?

### ISSUE THREAD

**Issue by JohnB17** [marcrobledo/savegame-editors#123]
So I upload the file (meet.dat) and I edit it, but I hit save and then the close button but it just closes the file but doesn't give me the modified file.

**Comment by marcrobledo** [comment]
When you click on Save, a new file is saved in your computer. Some browsers save the file automatically in the Downloads folder, check it out and make sure it's there.

**Comment by JohnB17** [comment]
> When you click on Save, a new file is saved in your computer. Some browsers save the file automatically in the Downloads folder, check it out and make sure it's there.

Sorry, I was trying to do it on a mobile device.
