### ISSUE TITLE
can not edit the bow MODIFIERS in switch(v1.6)

### ISSUE THREAD

**Issue by jim972329667** [marcrobledo/savegame-editors#125]
Both bows and shields  only show  the durability bottom .[](url)
![QQ截图20200910221848](https://user-images.githubusercontent.com/59948910/92743996-aae43700-f3b3-11ea-8a48-ac134a8d80f7.png)

**Comment by marcrobledo** [comment]
It only happens when adding new equipment. You can edit the modifiers in already created equipment.

This can be fixed with a little tweak, but I have no time currently for this. I'll leave the issue open.

**Comment by jim972329667** [comment]
> It only happens when adding new equipment. You can edit the modifiers in already created equipment.
> 
> This can be fixed with a little tweak, but I have no time currently for this. I'll leave the issue open.

 I still can not edit the modifiers in already created bows and shields in V1.6 savedate . It just a minor issue that does not have much impact on the overall program,but hope you can fix it at odd times .  Thanks

**Comment by marcrobledo** [comment]
Even after loading the savegame up in the game?

The game rearranges some bytes everytime you boot it up, that's when the modifiers should appear in the editor again.

**Comment by jim972329667** [comment]
> Even after loading the savegame up in the game?
> 
> The game rearranges some bytes everytime you boot it up, that's when the modifiers should appear in the editor again.

It's my mistake. It worked ,I loading the savegame but I'm not using bow . Thanks a lot.  (*^ω^*)
