### ISSUE TITLE
Save Editor Zelda - Botw

### ISSUE THREAD

**Issue by Athedge** [marcrobledo/savegame-editors#13]
Hello !

Super Job with this save editor for Zelda - Botw

The program fail to open any savegame since this afternoon ?

Thanks in advance to resolve this issue !

Save me a lot of time ^^

Have a perfect day !

**Comment by Athedge** [comment]
![1](https://cloud.githubusercontent.com/assets/27633172/25072592/933c6308-22d2-11e7-905c-fafd4f210d28.png)

**Comment by marcrobledo** [comment]
Thanks for reporting it :-)
Should be fixed now. Looks like Chrome didn't like a single comma :-P
