### ISSUE TITLE
Clothes

### ISSUE THREAD

**Issue by sharkiller** [marcrobledo/savegame-editors#14]
Maybe a subtitle in clothes for colors could be good.

Actually the input is used for color.
4294967295: Mission item unmodifiable.
0: Original
1: Blue
2: Red
3: Yellow
4: White
5: Black
6: Purple
7: Green
8: Light Blue
9: Dark Blue
10: Orange
11: Pink
12: Dark Red
13: Light Brown
14: Brown
15: Gray

**Comment by sharkiller** [comment]
Updated colors

**Comment by marcrobledo** [comment]
Will be added as soon as possible :-)

**Comment by marcrobledo** [comment]
This will be added in the next version, thank you!
