### ISSUE TITLE
Zelda NPC(white dress) cant show in BOTW.

### ISSUE THREAD

**Issue by grossestein** [marcrobledo/savegame-editors#15]
I wonder what is it,so I change it to my saves,but it cant effect.And I went to begin.
So sorry for my English.

**Comment by marcrobledo** [comment]
The item list from the editor was extracted from https://github.com/joffnerd/botw-trainer/blob/master/items.json, but some items like that Zelda White Dress cannot be injected directly into a savegame.
I'll remove it from the editor since it's confusing some users.
