### ISSUE TITLE
Streetpass Mii Plaza, EU save: Picross 3D Round 2 and Mario & Happy overlap

### ISSUE THREAD

**Issue by kescherCode** [marcrobledo/savegame-editors#162]
In EU, Picross 3D Round 2 is actually placed on the panel slot Mario & Happy would otherwise be in. The slot for what would be Picross 3D Round 2 in literally all other regions goes unused. Unfortunately, this technically creates an incompatibility with this editor, because both panels are of a different size.

In practice, StreetPass Mii Plaza kind of just ignores that this 15 piece puzzle has been set to have more than 15 pieces, but it also stays this way in the savegame, which is kind of bad if someone were to check savegame legitimacy at some point.

I manually applied this diff to give the puzzle 14 pieces (all but one):

```
17956c17956
< 00046230: 0000 0000 0000 0000 ffff fe00 0000 0000  ................
---
> 00046230: 0000 0000 0000 0000 fffc 0000 0000 0000  ................
```

**Comment by kescherCode** [comment]
This sure is another "Nintendo, why?" moment

**Comment by marcrobledo** [comment]
Not sure if I understood well but... @AromaKitsune did your latest PR#463 fix this as well?

**Comment by AromaKitsune** [comment]
> Not sure if I understood well but... @AromaKitsune did your latest PR#463 fix this as well?

The region thing has nothing to do with this issue, it's just the puzzle panels being in the incorrect slots in the save editor. My PR did fix this too, so the save editor now shows the correct number of pieces for Mario & Happy (24x) and Picross 3D: Round 2 (15x).

**Comment by marcrobledo** [comment]
Nice, thank you again :-)
