### ISSUE TITLE
Unable to open or save Zelda BOTW 1.2.0 save files

### ISSUE THREAD

**Issue by chrisnharris** [marcrobledo/savegame-editors#17]
The file validation on uploading of a save file for Legend of Zelda - Breath of the Wild within savegame-editors.js does not correctly validate against save files generated by version 1.2.0. It appears that only the previous two versions of the game are accepted.

If you bypass the validation check with a javascript debugger, the parsing of the save file is malformed. Some data is parsed correctly, rupees for example, but weapons, armor, and horses all are read incorrectly. In short, the editing of files generated by v1.2.0 does not work correctly.

**Comment by marcrobledo** [comment]
Use the beta version here http://www.marcrobledo.com/savegame-editors/zelda-botw/ until I update the savegame-editor.js library.
