### ISSUE TITLE
TOTK: Add item items to inventory

### ISSUE THREAD

**Issue by oliveirarafa** [marcrobledo/savegame-editors#170]
Is it possible to add new itens to my inventory? For what I saw I can edit the itens that I have but if I have 10 itens in my inventory I cant add a 11th.

**Comment by Ritaku02** [comment]
I would like to second this, would be nice to add new items to my inventory like I could with the BotW save editor.

**Comment by marcrobledo** [comment]
Will work on this as soon as possible.

**Comment by oliveirarafa** [comment]
> Will work on this as soon as possible.

Thank you very much for your hard work.

**Comment by Ritaku02** [comment]
> Will work on this as soon as possible.

Thanks!

**Comment by marcrobledo** [comment]
Added an untested add button (resources and zonai devices only for now) in 1335413
