### ISSUE TITLE
TOTK: Zonaite max item amount is above 1000

### ISSUE THREAD

**Issue by Titanor-Soulstone** [marcrobledo/savegame-editors#171]
in totk the max number of  Zonaite you can carry is above 1000 yet your editor will only go to 999 
i also assume this is the case with other items 

right now i have 1013 Zonaite so i dont know where the limit is

**Comment by marcrobledo** [comment]
Zonaite limit incremented to 9999 in 1335413

It would be interesting to know if other resources can go beyond 999. Can you try to give yourself 999 apples then get one in-game and see what happens?

**Comment by R3pcom** [comment]
I just tried this. Apples go up to 999 and won't let you pickup any more beyond that.

**Comment by marcrobledo** [comment]
Thank you @R3pcom !

I'll leave the rest of item limits then.

**Comment by Titanor-Soulstone** [comment]
i just discovered Zonaite goes over 10000 and Crystallized Charge goes over 1000
