### ISSUE TITLE
[Contribution] Skyview Tower Hashes

### ISSUE THREAD

**Issue by lchmagKekse** [marcrobledo/savegame-editors#173]
I created a list of every Skyview Tower and Patterns/Hashes for unlocking them.
The _**Activated**_ flag is set when you examine the tower. This also enables fast travel if the map pin is set.
Hope this might be helpful as I have seen a similar feature in your botw savegame editor

Skyview Tower | Pin on map | Activated | Map unlocked
---|---|---|---
Lookout Landing | 7A 21 07 3C | 53 62 FB B8 | CF 2A 4A 03 
Gerudo Canyon | 86 86 41 E0 | 54 33 AB 0A | 81 4D 40 46
Popla Foothills | 3E 3C 25 DB | 6E 21 FB 71 | 6D 3A 76 14
Mount Lanayru | 8B A5 AE A7 | 4B 5A 64 DC | 36 88 25 D4
Upland Zorana | 23 CE 04 93 | 21 53 EF B0 | AC 73 3E F4
Ulri Mountain | F6 58 94 BC | 27 22 A5 8D | C2 3C 15 0D
Eldin Canyon | 2E 27 B1 C1 | 04 53 36 1F | 56 E9 45 CA
Thyphlo Ruins | 3F B4 AB 8F | B7 DD B4 FC | 2F 3E 39 81
Gerudo Highlands | 13 17 B0 89 | 49 8F E6 9E | AB 33 B1 D1
Hyrule Field | 50 2B EE 5E | 88 10 93 E8 | E8 08 A8 DA 
Rabella Wetlands | 14 41 EC 97 | 24 56 29 B2 | 2D D3 CF 0A
Pikida Stonegrove | B4 A9 E7 6E | 37 28 4B 1F | 8B 1B 79 41
Rospro Pass | 10 5C 41 F4 | 44 D8 C6 F6 | D5 47 65 43
Lindor`s Brow | BE C3 38 EC | E5 6B 23 D0 | 50 88 6B 1B
Sahasra Slope | C5 4B BC 6B | 80 F0 62 84 | 40 7E C7 1D

**Comment by marcrobledo** [comment]
That's a very nice contribution! Thank you! ^_^
I'll try to implement it as soon as possible.

**Comment by marcrobledo** [comment]
Added in c834fb0, thank you!
