### ISSUE TITLE
Constant loading after making changes

### ISSUE THREAD

**Issue by gashrafi1** [marcrobledo/savegame-editors#175]
Seem to be running into an issue where anytime I try to attach a bomb or other item to arrow, it is "Saving" for about a minute before executing. 

This seems to also be happening when entering shrines and saving (which is taking longer than 3 minutes).

Running Ryujinx. Audio is messed up too. Anything accessing the savefile, other than Ryujinx is closed.

**Comment by HylianLZ** [comment]
Close the editor page. It's still accessing the save location, so the game can't save.
