### ISSUE TITLE
ToTK loaded back into starting area after altering save

### ISSUE THREAD

**Issue by DankBot457** [marcrobledo/savegame-editors#177]
I'm not sure what I am doing wrong so some help would be appreciated. I have attempted multiple times to alter a save file, whether it be changing items or increasing hearts/stamina wheel, and every time I replace the old save for the edited one and load in I am spawned back in the starter room with the exit leading to an open void. I am using the emulator yuzu on windows so maybe this is the problem? Just not sure if there is a fix/workaround that I am missing. I am currently utilizing a mod that increases framerate to 60fps, but that is all the mods I have. Another thing to note, whenever I open a save file in the editor the field for hearts is always blank when it should read 3 hearts.

**Comment by marcrobledo** [comment]
Common known issues:

- **Saving/loading is slow in emulators:** If you are playing on an emulator and using the editor, please make sure the emulator is closed when you edit and that the editor is closed when you are playing.
- **Changes made with the editor are not showing up in game (1):** before loading your `progress.sav` in the editor, load your `caption.sav` and you will see a thumbnail of your savegame. This will allow you identify which is your latest savegame.
- **Changes made with the editor are not showing up in game (2):** make sure you are replacing the correct `progress.sav` file and not creating a `progress (1).sav`, that will make your savegame invalid and reset
