### ISSUE TITLE
TOTK: Feature request: add weapons and Armors

### ISSUE THREAD

**Issue by tsurugikengo** [marcrobledo/savegame-editors#181]
sorry for bothering you when you are so busy.

**Comment by marcrobledo** [comment]
Added in 9f65ac9.
Be aware this is untested, so as always: keep a backup of your savegame.

**Comment by tsurugikengo** [comment]
thank you very very much!!
you are god!!!!!!

**Comment by ddaversa** [comment]
Thank you for this addition. Appreciate the activity. Will donate!
