### ISSUE TITLE
TOTK Question: Horse Editing? 

### ISSUE THREAD

**Issue by printer-tray** [marcrobledo/savegame-editors#182]
Does the horse editor currently work? Only asking because I had some horses that were ported forward from my BOTW save somehow and can't seem to edit them.

**Comment by marcrobledo** [comment]
This might be a duplicate of #169, but I'll leave the issue open for now.

The horse editor can arrive sooner if you provide a savegame with horse data. It will be very helpful if it has five horses and you also provide their names, saddles, etc.

**Comment by printer-tray** [comment]
I wasn't looking to edit colors as much as their names, but I don't think I have saddles
Anyway, I'll get three more horses to help out with it

**Comment by marcrobledo** [comment]
Thank you @printer-tray , please post your savegame in #169 ;-)
