### ISSUE TITLE
TOTK: Reset Hyrule Compendium

### ISSUE THREAD

**Issue by JarFiles** [marcrobledo/savegame-editors#185]
Hey,
First of all thank you a lot for the work you’ve already put into this.

I’m not sure how complicated it is, but could you also add back the ability to reset the album photos to the stock images?

Thanks

**Comment by benwa** [comment]
This was actually my favorite feature of the BOTW editor, because I hate snapping pictures.

**Comment by Karlos007** [comment]
Can someone share a progress.sav (in zip) file to test?

**Comment by MagnesG** [comment]
Here

[progress.zip](https://github.com/marcrobledo/savegame-editors/files/11515134/progress.zip)

**Comment by Karlos007** [comment]
> Here
> 
> [progress.zip](https://github.com/marcrobledo/savegame-editors/files/11515134/progress.zip)

Thanks, can you test this file?
[progress_edited.zip](https://github.com/marcrobledo/savegame-editors/files/11515197/progress_edited.zip)
Try to take pictures of unlocked enemies or buy photos from Robbie

**Comment by MagnesG** [comment]
It works!

All of my original captures (5 of them) had been replaced and reset with stock ones. Others had already been bought from Robbie so my compendium is fully on stock images now.

**Comment by JarFiles** [comment]
Sounds great! @Karlos007 Could you share the way you did it or create a PR :)?

**Comment by Karlos007** [comment]
I compared files with hex editor and then tried to change some values manually, 

35 2A DF BE = default stock photo
EC 74 1F 9A = custom photo

The data seems to start at 00034FFC and end at 0003834C on v1.1
There is also a new TOTK SaveGame Editor on gbatemp with that and more stuff.

**Comment by JarFiles** [comment]
I've also tried that on mine and also got it to work. @marcrobledo Would be amazing if you could add this to the editor!

**Comment by Karlos007** [comment]
```
        public static Dictionary<string, uint> CollectionStatusValues = new Dictionary<string, uint>() {
            {"Unopened",           2375459525  },  // C5A2968D
            {"TakePhoto",          2585752812  },  // EC741F9A
            {"Buy",                3202296373  },  // 352ADFBE
        };
```

These are the hashes i think
for the 509 compendium entries

509 Unopened
509 TakePhoto -> (Custom Photo)
509 Buy -> (Stock Photo)

**Comment by JarFiles** [comment]
@Karlos007 Could you share a link to the other editor you were talking about?

**Comment by Karlos007** [comment]
https://gbatemp.net/threads/totk-savegame-editor.633222/

It has the source code with hashes ("TOTK-SaveGame-Editor\Data\GameData.cs")
Pretty interesting

**Comment by marcrobledo** [comment]
I'll try to add this, but do not expect it anytime soon :-(
Before adding any feature, I prefer to do some research and see how the game really manipulates data, I want to be sure that no other undesired byte is changed.

**Comment by Karlos007** [comment]
If you need the hashes or help with testing let us know
There are 3 possibles values for all 509 entries, either no photo, manual photo or buy from the npc.

```
            {"Unopened",           2375459525  },  // C5A2968D
            {"TakePhoto",          2585752812  },  // EC741F9A
            {"Buy",                3202296373  },  // 352ADFBE
```

**Comment by marcrobledo** [comment]
> I'll try to add this, but do not expect it anytime soon :-( Before adding any feature, I prefer to do some research and see how the game really manipulates data, I want to be sure that no other undesired byte is changed.

Got a little time to do some tests and confirm it's safe. So... it's up now :-)
There are two buttons:
- the first one turns all your custom pictures to stock so you can delete the jpg files
- the second one unlocks all missing pictures

**Comment by benwa** [comment]
Worked perfectly for me!

**Comment by zerocreator0** [comment]
> > I'll try to add this, but do not expect it anytime soon :-( Before adding any feature, I prefer to do some research and see how the game really manipulates data, I want to be sure that no other undesired byte is changed.我会尝试添加这个，但不要指望它很快就会完成:-(在添加任何功能之前，我更愿意做一些研究，看看游戏是如何真正操纵数据的，我想确保没有其他不需要的字节被改变。
> 
> Got a little time to do some tests and confirm it's safe. So... it's up now :-)有点时间做了一些测试，确认安全。所以……现在上线了 :-) There are two buttons:有两个按钮：
> 
> * the first one turns all your custom pictures to stock so you can delete the jpg files第一个会把你所有的自定义图片转换成库存，这样你就可以删除 jpg 文件
> * the second one unlocks all missing pictures第二个解锁所有丢失的图片

where the  buttons
