### ISSUE TITLE
Add an option to remove zonal devices

### ISSUE THREAD

**Issue by RobbyV2** [marcrobledo/savegame-editors#186]
If you go above the max amount of zonal devices in your inventory, they don’t show up. This would be useful to remove all current zonal devices and then add them all back so they can show up in game.

**Comment by marcrobledo** [comment]
The max amount of zonai devices is 60. The editor doesn't let you add more than those because the savegame has only reserved space for exactly 60.
In other words, I don't know how you managed to get more than 60, but it's impossible to recover them.

**Comment by rtb4** [comment]
After the modification of the archive, it cannot be saved in the game, which will cause the game to stop working. Hope to solve it as soon as possible

**Comment by RobbyV2** [comment]
I'm unsure if what I said previously was correct because of your response. Let me reword it,
I have exactly 60 zonai devices but in-game there are duplicates and some of them just don't show up, even though they're in the editor.
I was wondering if there's any way to remove zonai devices from the save file? Let me know if you would like my save data.

**Comment by marcrobledo** [comment]
Ah, now I understand!

Removing items in the editor would require some work (it would need to rearrange the item data in the savegame and it's not as easy as it sounds). For the moment, I prefer to focus on other more important features.

If you want to remove the items, just set the quantity to 1 in the editor, then drop them in-game. That will (hopefully) remove them.

If I recall correctly, BOTW allowed to have duplicate items. According to your post, looks like TOTK acts differently. I'll try to add something to the Add item feature so it never adds duplicate items.

**Comment by RobbyV2** [comment]
I see! No worries, I'm glad that this issue is at least fixable as I obviously don't want my save to be ruined! 
TOTK does seem allow duplicate zonai devices, but if they reach the limit they sort of override the ones that are after it in the list. At least, that's what's happening to me.
Take your time! I appreciate how quickly you're working on this save editor and got to my question!

**Comment by marcrobledo** [comment]
In the worst case, I could fix manually your savegame.

**Comment by marcrobledo** [comment]
I know it's a bit late, but I added a button to remove items in https://github.com/marcrobledo/savegame-editors/commit/0885e4ad330646c6ea8324a414d08c708edc2fbb, just hover the mouse over the desired item.
