### ISSUE TITLE
TOTK missing item name.

### ISSUE THREAD

**Issue by sharkiller** [marcrobledo/savegame-editors#187]
In my save I only have 1 missing name: 

### **_Item_StableHostelAccommodationCoupon_A_**

![image](https://github.com/marcrobledo/savegame-editors/assets/712193/2ed139b6-710a-4860-8de7-60b0f2a22bcf)

Real name: 

### **_Sleepover Ticket_**

![image](https://github.com/marcrobledo/savegame-editors/assets/712193/60a49edd-6e6c-41e7-a0ba-6f3caf34de17)

**Comment by rtb4** [comment]
After the modification of the archive, it cannot be saved in the game, which will cause the game to stop working. Hope to solve it as soon as possible

**Comment by marcrobledo** [comment]
Fixed in 6e30735, thank you!
