### ISSUE TITLE
TOTK：Save file modification was damaged

### ISSUE THREAD

**Issue by rtb4** [marcrobledo/savegame-editors#188]
After the modification of the archive, it cannot be saved in the game, which will cause the game to stop working. Hope to solve it as soon as possible

broken save file ： http://159.75.103.230/progress.rar

**Comment by marcrobledo** [comment]
Common known issues:

- **Saving/loading is slow in emulators:** If you are playing on an emulator and using the editor, please make sure the emulator is closed when you edit and that the editor is closed when you are playing.
- **Weapon/shield durability resets:** TOTK changed how durability works and you cannot set a higher value than its base durability anymore like in BOTW. The game resets the value as soon as you load your save.
- **Changes made with the editor are not showing up in game (1):** before loading your `progress.sav` in the editor, load your `caption.sav` and you will see a thumbnail of your savegame. This will allow you identify which is your latest savegame.
- **Changes made with the editor are not showing up in game (2):** make sure you are replacing the correct `progress.sav` file and not creating a `progress (1).sav`, that will make your savegame invalid and reset

Remember to make backups of your savegames before editing.
