### ISSUE TITLE
Save Editor resets progress

### ISSUE THREAD

**Issue by dasflieg** [marcrobledo/savegame-editors#19]
Every time I replace a save file with one from the editor it sets me back to right after Link first wakes with nothing.
This happens even when I dont edit anything, just replace the save file with the one from the editor.

**Comment by marcrobledo** [comment]
This is because the savegame file gets corrupted (it shouldn't happen with the editor though) or you are injecting the file incorrectly.
Can you post your savegame so I can take a look if it's an issue with your savegame?

**Comment by dasflieg** [comment]
Sorry for my incompetence... How do I put my savegame on here, it says file not supported.

**Comment by marcrobledo** [comment]
Compress it as a zip file.
