### ISSUE TITLE
TOTK missing item name

### ISSUE THREAD

**Issue by bmq-code** [marcrobledo/savegame-editors#190]
In my save I only have 1 missing name:
Obj_WarpDLC
![屏幕截图 2023-05-17 094042](https://github.com/marcrobledo/savegame-editors/assets/12109421/1f0b7edc-988b-47ae-b720-8fdb692732aa)
Real name:
travel medallion
![2023051709445000](https://github.com/marcrobledo/savegame-editors/assets/12109421/fd6113db-cc07-4c4b-bc17-f951ca7752c6)

**The quantity is fixed at 3**

**Comment by marcrobledo** [comment]
Fixed in aa9f129, thank you!
