### ISSUE TITLE
TotK Forcing Durability changes

### ISSUE THREAD

**Issue by Invitation2Hades** [marcrobledo/savegame-editors#193]
I know its impossible to set values higher than the max durability of an item, but if an item has Durability ↑↑ and for examples sake lets use the Hylian Shield which naturally has a base 800 durability stat. Say you also have Durability ↑↑ with a +10 modifier. You should have 810 but with the newest build, I can see that it just defaults to 800. Is this intended?

**Comment by marcrobledo** [comment]
Discussing in #191
