### ISSUE TITLE
Game is stuck at save animation.

### ISSUE THREAD

**Issue by Acid-Breath** [marcrobledo/savegame-editors#194]
![Ryujinx 1 1 801 - The Legend of Zelda_ Tears of the Kingdom v1 1 0 (0100F2C0115B6000) (64-bit) 17-05-2023 11_37_27 PM](https://github.com/marcrobledo/savegame-editors/assets/60863453/2a162974-d9ca-4a9c-b3ff-2b18a1f0c420)

The game is being saved for the last 15 minutes. Not helping at all. Please fix this asap.

**Comment by marcrobledo** [comment]
Common known issues:

- **Saving/loading is slow in emulators:** If you are playing on an emulator and using the editor, please make sure the emulator is closed when you edit and that the editor is closed when you are playing. Also, make sure the OS has writing permissions for the savegame file.
- **Changes made with the editor are not showing up in game (1):** before loading your `progress.sav` in the editor, load your `caption.sav` and you will see a thumbnail of your savegame. This will allow you identify which is your latest savegame.
- **Changes made with the editor are not showing up in game (2):** make sure you are replacing the correct `progress.sav` file and not creating a `progress (1).sav`, that would make your savegame invalid and reset your progress
- **Weapon/shield durability cannot get higher than its default values:** unfortunately, TOTK made some changes and we cannot set higher durability values to weapons and shields (without using RAM cheats or ROM modding)
- **Weapon/shield durability cannot get higher than its default values:** unfortunately, TOTK made some changes and we cannot set higher durability values to weapons and shields. Fortunately, there is a workaround: just set the Durability↑↑ mod to the desired weapon and its value to 999999.

Please read and check the common issues above. If you really think there is a bug in the editor after that, provide as much information as you can (if you are playing on real HW or emulator, what you edited exactly, etc). At the moment, it's very hard for me to keep track of all issues posted here and, in most cases, they are just related to emulator (which has nothing to do with the editor). My free time is limited and I cannot spend so much time looking at all issues.

**Always remember to make backups of your savegames before editing. Use this savegame editor at your own risk. By using it, you are responsible of any data lost.**
