### ISSUE TITLE
new version a step backwards

### ISSUE THREAD

**Issue by iansebryk** [marcrobledo/savegame-editors#20]
i love the look of the new version.  i hope i'm not missing something, but it is a serious step backwards in terms of functionality.  i can no longer edit my items in place, which means if i want to change a star level on an item, i no longer can.  i also can't rearrange my inventory anymore.  i appreciate all the work you've done, but in terms of usefulness, this is now less useful.  i think you might want to restore the old editability of the items while incorporating the new, really amazing, UI.

**Comment by marcrobledo** [comment]
All issues you posted seem to work fine for me.
Post your savegame so I can take a look at what's going on.

**Comment by boss69xd** [comment]
yo you mind if ya look at my savegame please? i need help its not working :P

**Comment by marcrobledo** [comment]
Post it and I'll take a look.

**Comment by boss69xd** [comment]
the one i tryed to mod or the plain one?

**Comment by boss69xd** [comment]
ill post both

**Comment by boss69xd** [comment]
wait where do i put it XD

**Comment by boss69xd** [comment]
where do i post the savegame?

**Comment by marcrobledo** [comment]
You can attach it here or upload it anywhere else. But, please, open a new issue.

**Comment by iansebryk** [comment]
sorry for the long delay, i see that i can drag-n-drop reoder the list.  it never occured to me to give that a shot!  :P  thank you for your patience.
