### ISSUE TITLE
TOTK - Hearts issue

### ISSUE THREAD

**Issue by jestergi** [marcrobledo/savegame-editors#202]
Last night I noticed that I couldn't change my maximum hearts. I'd change it from, say, 6 to 14 and save it, then copy it into Yuzu and I'd still be at 6 hearts. At first I thought I was using the wrong save slot, but other changes I'd make would stick (Stamina wheel, rupees, etc).

This morning I noticed that sometimes when I import my .sav into the site the hearts field has no value, and if I save that and load the save game I die, heh.

![image](https://github.com/marcrobledo/savegame-editors/assets/33233883/5d0b2c8c-6965-4d21-b112-cf12e2c7f3c8)

**Comment by marcrobledo** [comment]
Can you post a savegame that shows a blank  max heart value in the editor?

**Comment by jestergi** [comment]
[progress.zip](https://github.com/marcrobledo/savegame-editors/files/11509249/progress.zip)

Here you go. It doesn't happen every time. Sometimes when I'd just clear out the sav in the browser and drag it again and it'd be fine. I did just try this one and it showed the same as the screenshot above. I've tried a couple of times today to change my hearts and it's not taken on any save. I got around it by increasing the Light of Blessing count and just buying hearts at the shrine.

**Comment by marcrobledo** [comment]
Do you remember exactly how many hearts you had and how many hearts you  tried to set?
What happens when you load up this savegame in the game after you die? How many hearts do you have after reviving?
Were playing in The Depths when you saved by any chance?

**Comment by jestergi** [comment]
I don't recall exactly with that save. I believe it was 4 and I tried setting it to 10.

When I'd die it'd load back up like normal and I'd have whatever number of hearts I'd had originally (like 4), though with only 3 filled (typical after death).

[progress2.zip](https://github.com/marcrobledo/savegame-editors/files/11509519/progress2.zip)

Here's one I just tried changing from 14 hearts to 15, and changed my rupees from 99,200 to 99,201. After downloading the save, copying it over and loading it, I still have 14 hearts, but I have 99,201 rupees. The odd thing is if I clear the save on the site and immediately re-upload the .sav that I just downloaded, it shows it's 15 hearts. Once I load that save into the game however it says it's 14. I don't know if the value isn't getting recognized by the game or if there's another file that's saving the heart information and is overriding the one I'm copying over.

**Comment by rubencg195** [comment]
same issue and the korok seeds dont change either on v1.1.0

**Comment by ApacheThunder** [comment]
Huh I ran into this problem too. I believe I had 16 or so hearts. I thought the issue was resolved as I made another change after a couple days and didn't see the issue crop up again. I still have the save it happened on too and I checked just now and it shows correct heart count.

**Comment by marcrobledo** [comment]
Please post your savegames here and try to provide as much information as you can (how many maximum hearts you have in-game, how many hearts you have (including quarters), if you are in The Depths and have some hearts disabled, etc).

**Comment by vhaerath** [comment]
I've been having a similar problem with hearts that's listed in the first post. No matter what save I use, every single other change I make "sticks", but the hearts don't. I haven't run into the 0 hearts issue, but any changes I make to hearts doesn't actually save at all, they just stay the same.

Oddly enough, lchmagKekse's save editor does work for hearts, so I was able to use that one to increase my hearts.

Would you like saves with this issue, or only the 0 hearts issue?

**Comment by marcrobledo** [comment]
Should be fixed now in c251d26!

**Comment by jestergi** [comment]
Confirmed, loaded save with 21 hearts, set to 22, and loaded game with 22 hearts. Thanks!

**Comment by jestergi** [comment]
Confirmed, loaded save with 21 hearts, set to 22, and loaded game with 22 hearts. Thanks!
