### ISSUE TITLE
TOTK - Max durability in mods?

### ISSUE THREAD

**Issue by ddaversa** [marcrobledo/savegame-editors#207]
I've noticed the max durability for equipment seems to be hardcoded, however, I would recommend allowing for higher values. There are mods out there that give items more durability, bypassing the game's limit, so this "feature" clashes with those mods.

**Comment by Anonymous42456** [comment]
You can use an infinite durability code.

**Comment by marcrobledo** [comment]
I wasn't aware that there are already TOTK mods! That's insanely fast!

I could remove the number limit but... that would lead to hundreds of complains and issues opened here asking why the durability limit does not work. So I don't know what to do :-/

> Yes, this would be much appreciated. However, maybe a number next to the Durability field which shows you the legitimate limit or a button that resets the durability to the limited maximum (as it was before you could add weapons and bows etc. to your inventory) would also be a nice addition.

The restore durability button has been added again! Though it won't work with mods savegames.

**Comment by Truinto** [comment]
I edited the javascript to enter any number in the durability field. I also checked that the generated file remembered the durability. However upon loading the game, the durability is reduced to its legitimate maximum.

I conclude it's not possible to go over the maximum (unless I made a mistake). The only way to get ridiculous durability is to make a giant durability modifier.

**Comment by marcrobledo** [comment]
> I edited the javascript to enter any number in the durability field. I also checked that the generated file remembered the durability. However upon loading the game, the durability is reduced to its legitimate maximum.
> 
> I conclude it's not possible to go over the maximum (unless I made a mistake). The only way to get ridiculous durability is to make a giant durability modifier.

Exactly. Unlike BOTW, TOTK fixes automatically durability if it's higher than its maximum allowed. So it's impossible to have an impossible high durability + another modifier, the only way now to create high durability weapons is to use the Durability Up modifiers.
Or to use mods, of course.
