### ISSUE TITLE
Possible Help for the editor 

### ISSUE THREAD

**Issue by DaviF19** [marcrobledo/savegame-editors#210]
hello friend, I hope you are well, I recently found this Save on the GBAtemp forums, I hope it can be of some help... 
This save has the location of 800 hidden koroks, all the underground lights and all the shrines, apart from a few other things... 

I hope it can be useful in some way...

https://drive.google.com/file/d/16lH-rFeA6MqtY4TIzlgY8ukK19MisCn9/view?usp=drivesdk

Thank you so much for your work, this amazing...

**Comment by Foxbound256** [comment]
Just to let you know when trying to open that link for the save it leads to a "You need to request access" page.

**Comment by marcrobledo** [comment]
I appreciate your help, but I have no time for reverse engineer savegames for big features at the moment :-(
