### ISSUE TITLE
Maybe add The Intro Master Sword

### ISSUE THREAD

**Issue by FehlBan** [marcrobledo/savegame-editors#211]
Maybe some People want to use the Mastersword from the Intro cause it is unbreakable the ID is Weapon_Sword_070

**Comment by MrKatzenGaming** [comment]
correction: the id of the intro master sword is Weapon_Sword_77 not Weapon_Sword_70

**Comment by ApacheThunder** [comment]
It appears one of yesterday's commits may have added it. I opened an old save from before I got it and Weapon_Sword_077 shows up at the bottom of the drop down list. ;)

**Comment by marcrobledo** [comment]
Duplicate of #208
