### ISSUE TITLE
ToTK: Feature request:add a "add all items button"

### ISSUE THREAD

**Issue by ilzge** [marcrobledo/savegame-editors#212]
Thank you for the save editor you developed, I hope you can add a "add all items" button to the item interface, and remove the limit on the durability value, this is will be a perfect editor. thanks.

**Comment by marcrobledo** [comment]
The limit on the durability can be surpassed only if you set the Durability+ or Durability++ bonus. This is how it works in TOTK, you cannot have a weapon with any other bonus and a higher durability value anymore like in BOTW.

As of the Add all items, that would lead probably to unexpected issues and would need some testing, so it's not a priority right now. If you really want to add easily items, just click on the Add button then keep pressing space in your keyboard.
