### ISSUE TITLE
TOTK: Added paraglider fabrics don't show up in dye shop menu

### ISSUE THREAD

**Issue by lukatorre** [marcrobledo/savegame-editors#215]
I used editor to add amiibo fabrics to the inventory, but they don't show up in the change paraglider fabric menu in the dye shop.

**Comment by marcrobledo** [comment]
This is a known issue.
Looks like just adding the items to the item list is not enough. There are probably some other needed flags there.

For now, I added a pony points editor so you can at least get some of the fabrics legitly.

**Comment by Karlos007** [comment]
I have a save with the amiibo fabrics if it helps to compare
Another option is to use the No Loot Boxes mod

**Comment by lukatorre** [comment]
Ok, bit of an update, yesterday I did some manipulations, then did the quest with that gets you discount at kakariko clothes shop and also a shiekah fabric, closed out of the game, went to sleep, when I checked the inventory today, every fabric except the shiekah fabric was gone but dye shop still registers ones unlocked the legit way, including shiekah one.

**Comment by ApacheThunder** [comment]
I imagine the cloths vanishing from key items menu upon interaction with the NPC is a normal behavior of the game. Mainly to clean up the key items menu and move new fabrics to the new one for the NPC I imagine. The save edited cloths vanish like they others as expected but there's some additional flag the NPC menu checks before adding them which the save editor currently doesn't support.

**Comment by camjorg** [comment]
Would love an update on this as well. I went through the effort of getting an additional fabric that was legit to see if there needed to be a way for the fabrics to properly checkpoint somehow... Anyway, no luck. All the fabrics disappeared, but the legit one stayed.

**Comment by Karlos007** [comment]
Sayge only removes the items from your inventory.
The flag that adds the fabrics triggers when (in a legit way) you get the said fabric.
I'm getting a list of the hashes if you want to add them.

**Comment by Karlos007** [comment]
https://github.com/Karlos007/TotK-Mods/blob/main/TotK-Research.txt
@marcrobledo feel free to add them when you can
There is also more stuff for unlocking autobuild and stuff like that
(and some minor spoilers at the end)

**Comment by marcrobledo** [comment]
Added usable paraglider flags to the master editor thanks to @Karlos007 !

I haven't tested myself, but I trust Karlos's work so it should work! :-)

**Comment by marcrobledo** [comment]
Added a nice little QoL feature that fixes automatically the paraglider fabric availability flags before saving.
