### ISSUE TITLE
Saving time

### ISSUE THREAD

**Issue by KoreSia** [marcrobledo/savegame-editors#217]
I've noticed that when loading up a modified save, whenever the game tries to save, or I try to save, it can't. It will say it is saving forever and make everything else slow down. I am using Ryujinx and have patch 1.1.1 installed.

**Comment by Karlos007** [comment]
Something is locking the file.
Try to close Chrome or any explorer, and Windows Folders.

**Comment by marcrobledo** [comment]
Common known issues:

- **Saving/loading is slow in emulators:** If you are playing on an emulator and using the editor, please make sure the emulator is closed when you edit and that the editor is closed when you are playing. Also, make sure the OS has writing permissions for the savegame file.
- **Changes made with the editor are not showing up in game (1):** before loading your `progress.sav` in the editor, load your `caption.sav` and you will see a thumbnail of your savegame. This will allow you identify which is your latest savegame.
- **Changes made with the editor are not showing up in game (2):** make sure you are replacing the correct `progress.sav` file and not creating a `progress (1).sav`, that would make your savegame invalid and reset your progress
- **Weapon/shield durability cannot get higher than its default values:** TOTK made some changes on how weapons work. Durability limit can only be increased now to a higher value if you set the modifier to Durability Up.

Please read and check the common issues above. If you really think there is a bug in the editor after that, provide as much information as you can (if you are playing on real HW or emulator, what you edited exactly, etc). At the moment, it's very hard for me to keep track of all issues posted here and, in most cases, they are just related to emulator (which has nothing to do with the editor). My free time is limited and I cannot spend so much time looking at all issues.

**Always remember to make backups of your savegames before editing. Use this savegame editor at your own risk. By using it, you are responsible of any data lost.**
