### ISSUE TITLE
Mons, What is it!?

### ISSUE THREAD

**Issue by lordneeko** [marcrobledo/savegame-editors#22]
There is a box in the HTML and JS for a variable "Mons"

But I cannot for the life of me figure out what it is for. I have changed it and can't see anything change in my game.

What is it?

**Comment by xeng91** [comment]
Mons is the money that is used to buy from Kilton
Kilton sells monster masks and other stuff
He will buy monster parts from you and give you mons instead of rupees

**Comment by lordneeko** [comment]
excellent thanks!
