### ISSUE TITLE
TOTK New feature: cooking editor

### ISSUE THREAD

**Issue by marcrobledo** [marcrobledo/savegame-editors#220]
I added a cooking editor in 68e81ef (inside the food tab).

Can anyone test if it works and/or if the game resets any of the values you set in the editor?

Also, it's missing some bonus effects names, so post them here if you find an unknown value in the food effect dropdown.

**Comment by Karlos007** [comment]
Nice work!

![image](https://github.com/marcrobledo/savegame-editors/assets/23475289/0a584292-6e72-4329-a1b5-c05b32e7bc33)
[c1db0965] is LifeMaxUp - Extra Heart
160 is 40 +Hearts (Full recovery) and 108 Level (+27 Hearts) with 0 duration
![image](https://github.com/marcrobledo/savegame-editors/assets/23475289/ca99aa2c-bc5d-4d13-bbf1-381e931d25c2)

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Carlo/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Carlo/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">



Value | Desc
-- | --
[c1db0965] | LifeMaxUp - Extra Heart
[3459853] | LifeRepair - Gloom Recovery
[4d1e8af4] | MiasmaGuard
[60d8315d] | ExStaminaMaxUp - Extra Stamina
[11383afd] | ResistBurn - Flame Guard
[1df7a011] | ResistHot - Heat Resistance
[9b6d98fb] | ResistCold - Cold Resistance
[183cd822] | ResistElectric - Shock Resistance
[67866c6d] | SwimSpeedUp - Swim Speed Up
[2b0cb1e9] | NotSlippy - Slip Resistance
[74141898] | QuietnessUp - Stealth Up



</body>

</html>

**Comment by marcrobledo** [comment]
Added these effects in d9e7394!

**Comment by Karlos007** [comment]
Works great!
![image](https://github.com/marcrobledo/savegame-editors/assets/23475289/5efadc1c-c2a4-466b-9b66-ef6cf20bb12b)

![image](https://github.com/marcrobledo/savegame-editors/assets/23475289/5d4dab8e-3e6e-4ddc-9a17-70e0bd9e0475)

![image](https://github.com/marcrobledo/savegame-editors/assets/23475289/f8daeb3a-9c85-4daf-a09c-16dd0ac0fc5b)

**Comment by marcrobledo** [comment]
That's fun haha

By the way, I wasn't sure how the game would react so I hardcoded a limit of 80 minutes. I've increased the duration limit now, let me know how long can it get in-game!

Enjoy this feature while you can because I'm afraid it will be patched sooner or later.

**Comment by Karlos007** [comment]
![image](https://github.com/marcrobledo/savegame-editors/assets/23475289/13eeed0b-f319-4830-8a67-1ed2f2b30a26)
for 28800 is 480 minutes

**Comment by Karlos007** [comment]
![image](https://github.com/marcrobledo/savegame-editors/assets/23475289/f6eef1c1-2b68-490a-a6fd-4dbce6e85cee)
I added an effect to a normal food but I can't put more than 8 in the multiplier
And less than 30 in the duration

**Comment by subworx** [comment]
> ![image](https://user-images.githubusercontent.com/23475289/239732943-13eeed0b-f319-4830-8a67-1ed2f2b30a26.png) for 28800 is 480 minutes

Game version 1.1.0 here (waiting for all mods to get ported to 1.1.1). I edited some Roasted Rushrooms or whatever and added Flame Guard for 28800 time units. Shows up without time in game and also does not have any effect when using it. 

![image](https://github.com/marcrobledo/savegame-editors/assets/10171215/08d5bed3-c9ac-49ed-9858-659193576311)

**Comment by HylianLZ** [comment]
Found another effect. ff347a38 which is Stormy Weather Attack Up.
![chrome_LmACNWnZsS](https://github.com/marcrobledo/savegame-editors/assets/33057795/fa10351d-f32b-4156-8758-6e66a1ddd444)
![Ryujinx_qgoHjGGUBm](https://github.com/marcrobledo/savegame-editors/assets/33057795/1390e5de-ffd5-41d5-82f4-6e52b85d6181)
Also noticed that the food effect multiplier is restricted to 40 if edited, which is easily passed in game like with cooking 5 big hearty radishes, which would give 104 or so in that field.

**Comment by easyworld** [comment]
|Value| Desc|
|:-----:|:-----:|
|0xB6EEDE09|None|
|0x1DF7A011|ResistHot - Heat Resistance|
|0x11383AFD|ResistBurn - Flame Guard|
|0x9B6D98FB|ResistCold - Cold Resistance|
|0x183CD822|ResistElectric - Shock Resistance|
|0x25293142|ResitLightning - Lightning Proof|
|0xF5E2A20C|ResistFreeze - UnFreezable|
|0x67866C6D|SwimSpeedUp - Swim Speed Up|
|0x87645022|DecreaseSwimStamina - Swim Dash Stamina Up|
|0xDC7FAF6E|ClimbSpeedUp - Climb Speed Up|
|0xA9384C6C|AttackUp - Attack Up|
|0x4A3E58F6|AttackUpCold - Cold Weather Attack|
|0x4C6A85D2|AttackUpHot - Hot Weather Attack|
|0xFF347A38|AttackUpThunderstorm - Stormy Weather Attack|
|0x74141898|QuietnessUp - Stealth Up|
|0x9ADD92A3|SandMoveUp - Sand Speed Up|
|0x33261E44|SnowMoveUp - Snow Speed Up|
|0xA0A00C0E|DefenseUp - Defense Up|
|0xB3F6B87A|AllSpeed - Speed Up|
|0x4D1E8AF4|MiasmaGuard - Gloom Resistance|
|0x4D91C91B|StalDisguise - Disguise; Bone Weap. Porf.|
|0xC1DB0965|LifeMaxUp - Extra Heart|
|0xE9A30056|StaminaRecover - Stamina Recovery|
|0x60D8315D|ExStaminaMaxUp - Extra Stamina|
|0x3459853|LifeRepair - Gloom Recovery|
|0x6775F470|DivingMobilityUp - Skydive Mobility Up|
|0x2B0CB1E9|NotSlippy - Slip Resistance|
|0x4939DCA1|LightEmission - Glow|
|0xCFD032DB|RupeeGuard - Rupee Padding|
|0x59BE2CC3|SwordBeamUp - Master Sword Beam Up|
|0x82638F9D|NightMoveSpeedUp - Night Speed Up|
|0x0D1D9EF3|DecreaseWallJumpStamina - Climbing Jump Stamina Up|
|0x48AA5DDF|DecreaseChargeAttackStamina - Charge Atk. Stamina Up|
|0x2F3B7069|NoBurning - Fireproof|
|0xC5DEF427|NoFallDamage -Impact Proof|
|0x346A7ABC|NoSlip - Slip Proof|
|0xA3B0355E|DecreaseZonauEnergy - Energy Up|
|0x52FAD704|ZonauEnergyHealUp - Energy Recharge Up|
|0x671DBE0D|MiasmaDefenseUp - Gloom Attack Resist|
|0xF563B129|ChargePowerUpCold - Cold Weather Charge|
|0x4FB7ED09|ChargePowerUpHot - Hot Weather Charge|
|0x8F4FDAF4|ChargePowerUpThunderstorm - Stormy Weather Charge|
|0x1D249847|LightFootprint - Shining Steps|

based on [Eiffel2018](https://www.tekqart.com/space-uid-2551322.html)'s resaerch

**Comment by marcrobledo** [comment]
Added a lot of untested food effects, there is one called TwiceJump that would be cool to see if it works. Though I'm afraid that probably none of them will work :-(

Still, if anyone wants to test them and confirm if they work or not, post it here. Otherwise, I'll consider the food editor complete.

**Comment by 5685C4A059D5** [comment]
I tried a EnableUseSwordBeam elixir and it didn't work, shows msgnotfound and has no effect.
Everything after it (#60 and up) didn't show up though maybe it's because I've hit the food limit.

**Comment by marcrobledo** [comment]
Removed the unusable food effects, thanks for testing @5685C4A059D5 .

I'll leave the issue open for a few more days, just in case someone finds anything odd with the food editor.
