### ISSUE TITLE
TOTK Pouch Size Issue

### ISSUE THREAD

**Issue by Karlos007** [marcrobledo/savegame-editors#221]
I have a save file with maxed (20 sword 14 bow 20 shield) slots, but seems that the editor gets capped to 18 13 20 when you edit.
The limit should be
20 weapons // 19 + 1 when you get the Master Sword
14 bows
20 Shield

You can use the example save file from the horse test
https://github.com/marcrobledo/savegame-editors/issues/169#issuecomment-1556113020

**Comment by marcrobledo** [comment]
Fixed in d9e7394, thank you!
