### ISSUE TITLE
TOTK Feature - Battery Size

### ISSUE THREAD

**Issue by Karlos007** [marcrobledo/savegame-editors#222]
On 34F8C or 34FC4 depending on the version there is a float for the battery size
It can be upgraded 45 times, +1000 every time, or all at once with 4500 Crystallized Charge
Value is from 3000 to 48000

By the way how I can find the "savegame hash keys", is there any special program?
I only know how to find the offsets from progress.sav

**Comment by marcrobledo** [comment]
I'm totally swamped with so many issues and requests, so I forgot to say this was implemented some days ago, thank you :-)
