### ISSUE TITLE
TOTK Request: ability to clear/repair autobuild history

### ISSUE THREAD

**Issue by thecyberwitch** [marcrobledo/savegame-editors#226]
It looks like certain cheats will break Autobuild (presumably by corrupting Autobuild history). 

There's a "fix up" cheat which does seem to work, but it's a bit fiddly and seems to require clearing the favourites list which could mean losing quite a bit of data.

It'd be great if the save editor tool had a repair functionality which could repair this corruption. Ideally this would preserve favourites and either delete all history items, or delete corrupted history items if this is detectable. If that's not possible, being able to clear/remove items from the history and favourites would make this process more convenient to deal with.

```
[Auto Build Fix (v1.1.0)]
04000000 02393718 B828D92A
04000000 02393718 14985A7A
04000000 049AA100 52807001
04000000 049AA104 B828D92A
04000000 049AA108 1767A585
```

**Comment by soul00777** [comment]
Is it possible to share the blueprint by editing the save file?

**Comment by thecyberwitch** [comment]
[slot_00_not_quite_broken.zip](https://github.com/marcrobledo/savegame-editors/files/11528126/slot_00_not_quite_broken.zip)
I wanted to attach a fully broken save, but autobuild seems to work on all the saves i have available.  The attached save does still have some broken history items and it would be nice to be able to purge them still.

**Comment by marcrobledo** [comment]
Cheats manipulate memory in real time, which means, it can break other things in-game. Be careful with that.
I am so sorry but, unfortunately, it would take time to do some research in order to fix glitched savegames (that have nothing to do with the savegame editor).

**Comment by Shideravan** [comment]
> 

Isn't possible just to clear all the history and favorites in autobuild? The main issue is that can't be done in the game directly (there's no way to "delete" an entry in autobuild history)
