### ISSUE TITLE
TOTK NEW Request: Can someone make it so you can remove some of the food items

### ISSUE THREAD

**Issue by naijah** [marcrobledo/savegame-editors#227]
I can Only add items. I cant remove any
![Web capture_22-5-2023_11527_www marcrobledo com](https://github.com/marcrobledo/savegame-editors/assets/134255864/2cdde12e-528c-40b1-b203-5c2189e9673d)

**Comment by beyondmeat** [comment]
That makes sense but there should be a way to undo / remove it before you hit "save changes".

**Comment by Lucifiish** [comment]
An undo button would be a nice QoL feature, but I suspect that implementing it would have a plethora of issues - adding items to the inventory artificially is already somewhat risky; removing them would likely cause internal game issues. Setting the quantity to 1 and eating them in game is absolutely an efficient enough way to get that done.

Recommending closing this thread

**Comment by marcrobledo** [comment]
Added a button to remove items in 0885e4a, just hover the mouse over the desired item.

**Comment by beyondmeat** [comment]
> An undo button would be a nice QoL feature, but I suspect that implementing it would have a plethora of issues - adding items to the inventory artificially is already somewhat risky; removing them would likely cause internal game issues. Setting the quantity to 1 and eating them in game is absolutely an efficient enough way to get that done.
> 
> Recommending closing this thread

The save only technically gets edited on "save changes" and that's a new file download technically. So the undo button would just pop that item from the queue of changes basically and the save wouldn't be affected. This can easily be done b/c the code can know what was added by the editor and not the save file and only display the delete button for changes 'not yet committed'. That would also prevent any unsafe operations happening on a file with those items already saved., bc the button wouldn't be there.

That said, depending on the code, it might require a few changes but nothing major.

Sure you could just reload the page and loadup the untouched file but you might then have to do a bunch re-edits and not very UX friendly.

**Comment by marcrobledo** [comment]
An undo button is definitively doable, but it is not as easy as it sounds and it's not in my priority list, sorry :-(

**Comment by iMaxed0utHD** [comment]
@marcrobledo Does this work for armor too or just materials? I accidentally clicked add armor when scrolling down to upgrade a piece and can't figure out to how delete the extra piece of armor.

**Comment by beyondmeat** [comment]
@iMaxed0utHD reload the unedited save and redo your changes. For the most part, unless it's zora armor, I don't think you will miss a cutscene or anything if you just sell the armor off in game.

**Comment by marcrobledo** [comment]
> @marcrobledo Does this work for armor too or just materials? I accidentally clicked add armor when scrolling down to upgrade a piece and can't figure out to how delete the extra piece of armor.

It didn't, but now it does :-)
I've just enabled the remove button for equipment added in the editor, sort of an undo button. @beyondmeat

**Comment by iMaxed0utHD** [comment]
> > @marcrobledo Does this work for armor too or just materials? I accidentally clicked add armor when scrolling down to upgrade a piece and can't figure out to how delete the extra piece of armor.
> 
> 
> 
> It didn't, but now it does :-)
> 
> I've just enabled the remove button for equipment added in the editor, sort of an undo button. @beyondmeat

Thank you! Super useful ^^ I would have reloaded my save, but I didn't realize I did it until I had already edited tons of things then played for a few hours 😅

**Comment by marcrobledo** [comment]
@Sensei412 added a checkbox for this in the new setttings tab.

I figure there isn't much more that can be improved in item removal, so I'm closing the issue.
