### ISSUE TITLE
savegame problems 

### ISSUE THREAD

**Issue by boss69xd** [marcrobledo/savegame-editors#23]
need help with savegame

i dumped the save using saviine found the savgame file. moved it over to your save game editor modded it then i put it back in the "1" folder, injected it back in botw using saviine went to my save and nothing i edited was there.
and yes the savegame i found was in the "1" folder

**Comment by boss69xd** [comment]
ok sorry i was dumb heres the savegames
[New WinRAR ZIP archive.zip](https://github.com/marcrobledo/savegame-editors/files/1134071/New.WinRAR.ZIP.archive.zip)

**Comment by marcrobledo** [comment]
Can you edit and describe exactly your issue?

**Comment by boss69xd** [comment]
i dumped the save using saviine found the savgame file. moved it over to your save game editor  modded it then i put it back in the "1" folder, injected it back in botw using saviine went to my save and nothing i edited was there.

**Comment by boss69xd** [comment]
and yes the savegame i found was in the "1" folder

**Comment by marcrobledo** [comment]
The editor opens boths savegame correctly, and your changes are there so it's not a savegame problem.

You are not injecting it correctly, unfortunately I cannot give support to that since it's not related to my savegame editor.
