### ISSUE TITLE
caves marked done count?

### ISSUE THREAD

**Issue by beyondmeat** [marcrobledo/savegame-editors#230]
I used the 10x cheat and it affected the buupels which breaks count for them. Counting them up via map wouldn't be accurate since many caves have 2 entrances.

This is really intended as a fix for the 10x cheat doing that.

**Comment by marcrobledo** [comment]
Cheats manipulate memory in real time, which means, it can break other things in-game. Be careful with that.
I am so sorry but, unfortunately, it would take time to do some research in order to fix glitched savegames (that have nothing to do with the savegame editor).
