### ISSUE TITLE
TOTK Not Working

### ISSUE THREAD

**Issue by JimZiii** [marcrobledo/savegame-editors#232]
Not sure what happened, i opened a progress.sav file maybe an hour ago, and it opened. I tried opening a few caption.sav and when i went to open the correct progress.sav nothing happened. After browsing and selecting a progress.sav file i just get an empty page.
Same page as before but without the "browse..... or drop it here"
Caption.sav files still work tho. I've tried this in 4 different browser, all with the same result.
Not sure if i caught it just as it broke or if something happened on my end, but any suggestions on how to fix it is appreciated

**Comment by KEWLBEANS123** [comment]
yes same i occured the same issue and pulled a request, something is definitley wrong if its on ur end too

**Comment by darthcoder9** [comment]
+1

**Comment by KEWLBEANS123** [comment]
working again yall!

**Comment by marcrobledo** [comment]
Fixed, thank you!

**Comment by darthcoder9** [comment]
Thank you!!!!! ✅
