### ISSUE TITLE
TOTK: feature request: fixing teleport for improper cheat usage

### ISSUE THREAD

**Issue by A2Sumie** [marcrobledo/savegame-editors#236]
Altering HP with wrong cheats at the 4th temple causes transport unusable.
Can you make a fix for this kind of savegame?
Sincerely

**Comment by marcrobledo** [comment]
Cheats manipulate memory in real time, which means, it can break other things in-game. Be careful with that.
I am so sorry but, unfortunately, it would take time to do some research in order to fix glitched savegames (that have nothing to do with the savegame editor).
