### ISSUE TITLE
cant save

### ISSUE THREAD

**Issue by mbcskm** [marcrobledo/savegame-editors#238]
i opened the save file with the game closed, i edited and put the save in the save folder, i closed the editor and opened the game, and it stays forever in the saving screen

**Comment by ooxaerooo** [comment]
Hm, true. Problem is not only the edited savegame, also all others wont save anymore.

**Comment by ooxaerooo** [comment]
> Hm, true. Problem is not only the edited savegame, also all others wont save anymore.

Ok, I managend to get the savegames working again. You have to be really careful with editing Items.

**Comment by Lucifiish** [comment]
> i opened the save file with the game closed, i edited and put the save in the save folder, i closed the editor and opened the game, and it stays forever in the saving screen

What do you mean "the saving screen?" Are you saying you're able to play the game, but it freezes when you try to save, or are you saying you're stuck on the title screen? Both sound like emulator issues.

**Comment by Lucifiish** [comment]
> > > i opened the save file with the game closed, i edited and put the save in the save folder, i closed the editor and opened the game, and it stays forever in the saving screen
> > 
> > 
> > What do you mean "the saving screen?" Are you saying you're able to play the game, but it freezes when you try to save, or are you saying you're stuck on the title screen? Both sound like emulator issues.
> 
> you can load the game but if you go under system and save it says forever "saving".
> 
> Its an issue with the items. If I modify the Durability ++ i have this issue. modifying other settings works fine.

Gotcha. Sorry for the confusion. Although it might not be, that does sound like an issue with save editing. I’ve just been trying to help clean up tickets; that’s definitely outside my area of expertise

**Comment by timothywisdom** [comment]
I have the same issue. I edited only Max Hearts and am using Ryujinx 1.1.820.
It also causes all slots to not be saveable and when reloading a previous game, it gets stuck when the autosave feature happens.

**Comment by timothywisdom** [comment]
I've just had some luck repeating the above but I restarted Ryujinx and it worked. Perhaps Ryujinx is holding onto some cache somewhere that doesn't match the edited save file.

**Comment by ooxaerooo** [comment]
> I've just had some luck repeating the above but I restarted Ryujinx and it worked. Perhaps Ryujinx is holding onto some cache somewhere that doesn't match the edited save file.

deactivating the PPTC cache  is not solving the issue.  Really hard to say.. I cant tell the connections but editing the savegame 00 and loading it has the issues... loading save 01 that is a save before save 00 and has no edited items also has the issue. makes not really sense to me.

**Comment by CapnBry** [comment]
I had the same thing happen to me, just tried to edit the quantity of Sunset Fireflies from 2 to 10 (it kept raining every dang day and making them disappear!). It was the last item on the inventory list if that makes a difference. The webpage editor also could not load the file it had just saved with the changes. Ryujinx 1.1.819 /  TOTK v1.1.1

Title of this Issue should maybe be "Any save blocks game after edit"? Autosaves or manual saves just sit there spinning, but the rest of the game is fine. Using the save menu blocks everything because there is no way to cancel a save in progress.

**Comment by ooxaerooo** [comment]
Ok, done a few more tests and it looks like its a problem with the game itself or the Emulator Ryuijinx. With a  other Editor it has the same issue.

**Comment by mbcskm** [comment]
i got the same problem once only adding items i dont have, without editing them
