### ISSUE TITLE
Are botw map pins possible?

### ISSUE THREAD

**Issue by captncraig** [marcrobledo/savegame-editors#24]
Has anyone looked into finding the offsets / format of map pin data? It would be really cool to be able to add pins for missing shrines or korok seeds if that data were availible in some way. 

It looks like this tool can set the korok seed "completed" flags, so it could read them, and potentially set map pins for ones that have not been found yet. That would be amazingly useful if possible.

I'd be happy to help out on it, but I'm afraid I have no idea where to start trying to find the correct locations to edit map pins.

**Comment by marcrobledo** [comment]
Looks like the map pin values that need to be edited in the savegame are:
0x9383490e: MapApp_MapIconNo (s32_array)
0xea9def3f: MapApp_MapIconPos (vector3f_array)

Their XYZ positions can be found here:
https://raw.githubusercontent.com/MrCheeze/botw-tools/master/ActorInfo.product.xml
(look for HiddenKorok strings)

The idea sounds good, but it wouldn't be a quick task and I'm pretty busy now.
