### ISSUE TITLE
TotK Feature Request: Add Specific Items to the Inventory 

### ISSUE THREAD

**Issue by Foxlass** [marcrobledo/savegame-editors#240]
Hello! I'm wondering if it's possible to add or remove individual items such as materials, armor and weapons. Currently the only way to add new items is random and you can't choose what you want to add (to my knowledge at least, correct me if I'm wrong.)

**Comment by Lucifiish** [comment]
You definitely can choose what you want to add. If you click on "add ____," you'll see a new slot of that item category. It will, by default, be the next item on the list after the item at the bottom. That said, if you simply click the item name, you'll be met with a drop down to set that item to whatever you want. If it's special items, materials, or zonai parts, you can change quantity, and if it's weapons, shields, or bows, you can change durability, modifier, and modifier value.

The TotK save editor does not yet have the ability to edit clothing dyes through the save.

This issue can be closed!

**Comment by marcrobledo** [comment]
@Foxlass just click on the item name and you will be able to edit it ;-)

**Comment by Foxlass** [comment]
> @Foxlass just click on the item name and you will be able to edit it ;-)

Oh, thank you! Sorry I hadn't noticed that.
