### ISSUE TITLE
TOTK Fabrics added by the save editor are not showing up in the shop

### ISSUE THREAD

**Issue by Deadlygamer55** [marcrobledo/savegame-editors#247]
Whenever i add a fabric on the tears of the kingdom save editor, it doesn't get added to the shop like it should.

**Comment by VoltageMiner** [comment]
[TOTK known issues & FAQ](https://github.com/marcrobledo/savegame-editors/wiki/TOTK-known-issues-&-FAQ)

**Comment by Karlos007** [comment]
@marcrobledo can you add the flags I found for the fabrics?

**Comment by marcrobledo** [comment]
> @marcrobledo can you add the flags I found for the fabrics?

Sure, thank you!
But let's continue the discussion at #215 if you all don't mind.
