### ISSUE TITLE
TOTK korok seeds glitched

### ISSUE THREAD

**Issue by fennectech** [marcrobledo/savegame-editors#248]
i used the other save editor to alter bag space   now hetsu wont let me upgrade bows or shields and wnats 999 for mele weapons  and when i use them by adding seeds the slots dont stay   I cant get past 20 for mele and shields and i cant get past 14 for bows    here is my save 
https://cdn.discordapp.com/attachments/498994723823026176/1111482712553947207/progress.sav

**Comment by marcrobledo** [comment]
20, 14 and 20 are indeed the real game pouch limits.
