### ISSUE TITLE
TOTK: Veggie Porridge missing from the list of dishes

### ISSUE THREAD

**Issue by Unaty498** [marcrobledo/savegame-editors#249]
Hey, Veggie Porridge seemed to be missing from the list of available dishes, and I found that you probably put a 2 instead of a 3 here: 
![image](https://github.com/marcrobledo/savegame-editors/assets/50841236/bce00eb3-92b7-40c0-92bd-6168c24a9054)
(`zelda-totk.class.item.js` line 677)

**Comment by marcrobledo** [comment]
Fixed in 426867a, thank you!
