### ISSUE TITLE
Trial of the Sword?

### ISSUE THREAD

**Issue by basmith7** [marcrobledo/savegame-editors#25]
Is there anyway to get credit for completing any of the Trial of the Sword?

**Comment by marcrobledo** [comment]
What do you mean?

**Comment by daltonsky9** [comment]
I think he means to have the sword almost never break like after trials of the sword and to receive in game credit for It

**Comment by Squall-Leonhart** [comment]
There must be a condition within the save data somewhere that determines whether the sword has 40, 50, or 60+glow.  The luster at hyrule castle doubles the base power while attack+ adds more on top.
