### ISSUE TITLE
TOTK Request: Repair Playtime

### ISSUE THREAD

**Issue by systox** [marcrobledo/savegame-editors#250]
Huge discrepancy in my savefile playtime of 35 hours 14 minutes from my actual playtime of 13 hours 1 minute. Likely related to unlocked framerate. 

Any chance we can implement a, "test at your own risk" playtime editor? 

I think this issue is causing my enemies to rank up way too fast.

**Comment by XAPHAN63** [comment]
This option would be fine. possible to find this information with the Master editor? thank you in advance for your help

**Comment by marcrobledo** [comment]
Keep in mind the game counts only real gameplay, that means the internal timer doesn't advance during cinematics, dialogues, loading times, pause menu, etc.
That's what it causes that discrepancy. A friend of mine had 280h in his Switch, yet only 160h internal time.


I consider this project done already and from now on I will be working only in critical fixes. I wish I had time for this, but as a compensation, I added **Playtime** to the Master Editor (it was there already, but the hash key is unknown so you couldn't search it, had to implement an alternate way for unknown hash keys for this).
