### ISSUE TITLE
Steam Deck Yuzu TOTK save file question

### ISSUE THREAD

**Issue by axlstackz48** [marcrobledo/savegame-editors#251]
First off thank you for all that you do. Loved your BOTW SE awhile back. Anyhow, I was trying to use the save editor with my steam deck using Yuzu but no joy. I was wondering if it was compatibile or if i'm doing something wrong? I used my progress.sav file like I did on my PC and it works fine there. But then I do it on the SD and it doesn't work. Thank you in advance.

**Comment by marcrobledo** [comment]
Thank you for your kind words.

Unfortunately, I'm afraid I don't think we can help you here :-( All I can tell you is to make sure you are replacing the correct file in the SD and not creating a `progress (1).sav` file.

**Comment by axlstackz48** [comment]
Thank you so much!! I got it working!
