### ISSUE TITLE
TotK: BOTW Only items like Ancient Saddle/Bridle are available

### ISSUE THREAD

**Issue by CodeF53** [marcrobledo/savegame-editors#253]
These lead to the game crashing when added to a save file.

**Comment by JosephTheMan** [comment]
I am using a modded switch, they are using a emulator (I know them) and they crashed but I didn't. However when I went to put the ancient gear on, there was no option to equip it on my horse.

**Comment by ApacheThunder** [comment]
Does adding the other horse related key items work in adding to that menu? Might be a paraglider situation where there's separate flags that need to be set when adding new horse equipment to the key items menu. ;)

**Comment by marcrobledo** [comment]
Those are probably leftovers from my BOTW editor, they don't seem to be available in TOTK anymore. So I removed them the editor, thanks for the warning!
