### ISSUE TITLE
TOTK - Durability beyond the game's maximum

### ISSUE THREAD

**Issue by Halitendo** [marcrobledo/savegame-editors#255]
I mentioned this as a side topic in another Issue, however I thought it was better if I just made a new Issue for organization purposes.

The current TotK editor doesn't allow for higher durability values than the game's maximum, any higher value just gets set to the possible ingame maximum. This isn't quite great, as it takes away the possibility to make "unbreakable" weapons, shields, etc. without any cheat codes, at least as far as I know.
Marc mentioned that people would complain about the durability not being set to the legitimate maximum if he implements this, however, I have a suggestion which should work for both the people who want infinite durability and people who want to keep the legitimate maximum: What about adding a Lock-Button next to each inventory item which enables/disables the input for higher values for said item? That way, people could just toggle the button in order to switch between legtimate max and higher durability.

Before someone asks why I don't just use the Durability Modifier: If I would like to have weapons that deal tons of damage and are nearly unbreakable, I have to use the Attack Up Modifier. For the unbreakable part, I would just edit the base durability of the weapon, just like in the BotW editor. However, that's not possible with the current editor.

**Comment by marcrobledo** [comment]
Unfortunately, TOTK has made some changes on how weapon modifiers work. The only way to make almost-infinite durability (without RAM cheats, of course) is to set the Durability Up modifier. It's impossible to combine any modifier with a high durability 
value.

If you tried to set a higher durability value with any other modifier, as soon as you got in the game, the game would fix the durability and set it to the default value.

**Comment by Bellzine** [comment]
Base durability is stored with the weapon/shield's attributes in the game files rather than the save file,  the solution for this is to use the Unbreakable Equipment mod on gamebanana, works on both emulators and Switch.
