### ISSUE TITLE
TOTK: Set lightroot to found doesnt work

### ISSUE THREAD

**Issue by JimZiii** [marcrobledo/savegame-editors#259]
I've only tried the 'set as found' option because i don't want to unlock the whole map instantly, but not a single new lightroot is shown on the map.
I saved again in-game and opened it in the editor and it still says that they're all shown

**Comment by KEWLBEANS123** [comment]
made the same issue, idk why it does that?

**Comment by JimZiii** [comment]
> made the same issue, idk why it does that?

Yea i saw your post but i thought you meant you got the lightroot markers on your map but couldn't fast travel to them since you only mentioned fast traveling.
But you're saying you didn't get any of the markers either, just the map reveal.

It's hopefully a quick fix for him, just gotta find the correct flags 🤞

**Comment by iAmNotEric** [comment]
Same here. Mark as found but nothing happend on the Underground Map.

**Comment by marcrobledo** [comment]
Fixed in 1c7b1c6! Thank you for the warn.

I recommend you load a backup made before you used the lightroot activation in the editor, as it might have changed undesired flags.

**Comment by JimZiii** [comment]
> Fixed in [1c7b1c6](https://github.com/marcrobledo/savegame-editors/commit/1c7b1c625c180193d01a3a18ba469caf25c394ae)! Thank you for the warn.
> 
> I recommend you to load a backup made before you used the lightroot activation in the editor, as it might have changed undesired flags.

👍yea i reverted as soon as i noticed it wasn't working.
Thnx for the quick response
