### ISSUE TITLE
[TOTK] Can you add the function of modifying the Compendium

### ISSUE THREAD

**Issue by ConanNobita** [marcrobledo/savegame-editors#261]
I took a lot of pictures with camera, but they weren't good. I wanted to use the official photos.

**Comment by VoltageMiner** [comment]
Isn't that what the 'set current to stock' button is for?

**Comment by marcrobledo** [comment]
> Isn't that what the 'set current to stock' button is for?

Exactly. That button turns all your pictures to stock.
