### ISSUE TITLE
[TOTK] Can you add the function to delete a horse?

### ISSUE THREAD

**Issue by Zullivan1987** [marcrobledo/savegame-editors#262]
There is the possibility of deleting the horses, I see that there are two types of saved horses, those that are in the stable or ranches, and those that are dead and are kept by the fairy that revives the stallions.

**Comment by marcrobledo** [comment]
Unfortunately, it doesn't sound as easy as it sounds. The game manages a lot of unknown values for horses. It is much safer to remove them from the real game.

**Comment by Zullivan1987** [comment]
> Unfortunately, it doesn't sound as easy as it sounds. The game manages a lot of unknown values for horses. It is much safer to remove them from the real game.
> 
> Anyway, let's keep the horse discussion in #169 if you don't mind!

Can you add the function to delete at least the horses that are in the stable? I would like the option to delete or free horses to exist since the only option to add more horses to the game is to kill them and send them to the fairy's cemetery.
