### ISSUE TITLE
[TOTK] food effects 骸骨变装・擅长骨武器

### ISSUE THREAD

**Issue by jarod360** [marcrobledo/savegame-editors#263]
BOSS：
   你忘记添加这个特效了。
{name:'骸骨变装・擅长骨武器', value:0x4d91c91b},
![QQ浏览器截屏未命名](https://github.com/marcrobledo/savegame-editors/assets/32123167/fc6792ff-688e-4456-822e-26cc45bba542)

**Comment by marcrobledo** [comment]
Is this a legit modifier? Can it be obtained in-game with food? Does it work? There are a lot of modifiers that don't work with food.
