### ISSUE TITLE
[TOTK] I want to modify both the durability and attack power of the weapon.

### ISSUE THREAD

**Issue by sand626** [marcrobledo/savegame-editors#264]
Can't I increase the durability in a way other than setting the durability bonus? 
Or is it impossible to adjust the attack power level of the material?

**Comment by marcrobledo** [comment]
Sadly, it's impossible. [https://github.com/marcrobledo/savegame-editors/wiki/TOTK-known-issues-&-FAQ](Read the FAQ)
