### ISSUE TITLE
TOTK: Does checking the complete shrine option only make the shrine teleportable?

### ISSUE THREAD

**Issue by bunnynoah** [marcrobledo/savegame-editors#266]
As what the title asks. Does it or does it mark it as you completing the entire shrine? I want to still do the puzzles/challenges but I also want to teleport to the shrines.

**Comment by nbdeity** [comment]
hello! i recently tried the set all shrines as found, and it doesn't mark them as activated, so they cannot be teleported to. However, their location is present on the map

**Comment by bunnynoah** [comment]
> In your case, you should use the Set all shrines as found. It should enable teleportation, but still keep their uncomplete flags. Let me know if it works.

It only makes them shown (fully orange) rather than activated (blue with orange center) So I cannot warp to any I haven't already activated/cleared.

**Comment by cstarrk410** [comment]
> > In your case, you should use the Set all shrines as found. It should enable teleportation, but still keep their uncomplete flags. Let me know if it works.
> 
> It only makes them shown (fully orange) rather than activated (blue with orange center) So I cannot warp to any I haven't already activated/cleared.

If you clicked the tick for the found go to the master editor and go to where it says if they are appear or open. If they are open they should be able to be teleported to i think.
