### ISSUE TITLE
ToTK: Add Editor to project's main index.html file

### ISSUE THREAD

**Issue by ApacheThunder** [marcrobledo/savegame-editors#268]
I've downloaded the project to fiddle with things and noticed the main index page that shows all the available editors doesn't have ToTK added yet. Maybe forgot? Unless it's intended to not be listed there yet for some reason....

**Comment by marcrobledo** [comment]
It is intended. Or it was.

I didn't want this to attract much people because I wanted to avoid having to deal with tens of requests and issues asking the same things. I figure it makes no sense anymore, since it has already spread more than I wished and even indexed in search engines, so...

**Comment by marcrobledo** [comment]
Updated index page

**Comment by ApacheThunder** [comment]
Ahh I see. I wasn't sure so thought to let you know about. :P
