### ISSUE TITLE
TOTK: Lightroot count issue

### ISSUE THREAD

**Issue by Sensei412** [marcrobledo/savegame-editors#269]
I had unlocked all lightroots manually and for some reason the editor is showing 119/120 found and 120/120 activated. attaching my save file
[progress.zip](https://github.com/marcrobledo/savegame-editors/files/11586036/progress.zip)

**Comment by Karlos007** [comment]
![image](https://github.com/marcrobledo/savegame-editors/assets/23475289/d4f63b53-9424-44b5-937c-60469f1641ba)
Same

**Comment by marcrobledo** [comment]
Should be fixed now in 89ae228, thank you.
