### ISSUE TITLE
Streetpass editor

### ISSUE THREAD

**Issue by Joey-nINJJa** [marcrobledo/savegame-editors#27]
How do I get the meet.dat file from my system? Since it's a native system application, do I have to use JKSM via CIA rather than 3dsx? (I actually can't do that, sadly.) When I choose Save Data Options (I think that's what it is, my 3DS crashed when I went to check just now), it tells me there was an error opening the save archive or something akin to that. The file I'm looking for isn't in the Extdata.
Any ideas? (...aside from "ntrboothax," which I'm extremely disappointed isn't going to work for me.)

**Comment by marcrobledo** [comment]
I haven't tried (can't confirm, I can be wrong), but I don't think JKSM as 3dsx have access to system savegames.
Anyway, this is not related to the editor.

**Comment by Joey-nINJJa** [comment]
I finally got CFW installed...
Now it seems the editor is unable to unlock the ticket booth.
