### ISSUE TITLE
TOTK request: add more items to fusion dropdown

### ISSUE THREAD

**Issue by CeruleanSky** [marcrobledo/savegame-editors#270]
[evermean and talus hearts progress.zip](https://github.com/marcrobledo/savegame-editors/files/11587199/evermean.and.talus.hearts.progress.zip)

Some of the most powerful and cool looking fused weapons are those containing enemy drops that you are unable to add to the inventory.  Items like talus hearts and evermean logs, flux  etc.

While the fused icons are dynamically generated by the game and thus not something easily added and I don't know about icons when they are isolated, now that you are enabling fusion, the items themselves might want to be considered being added to the dropdown list as selectable.

They are currently shown but you can't add them to new weapons.

![image](https://github.com/marcrobledo/savegame-editors/assets/2829875/542132bd-72a0-4d93-9d29-0d7a8e608f78)

**Comment by marcrobledo** [comment]
Added these two items to the dropdown.

I figure we can get a list of all fusable items in-game from the game files. Did anyone do research on this already?

**Comment by marcrobledo** [comment]
Added all items from Echocolat list!

I'm closing this issue, need to do a clean up lol. If the list gets updated at some point, just open a new issue.
