### ISSUE TITLE
TOTK Completing the shrines breaks completion

### ISSUE THREAD

**Issue by captaindaffodil** [marcrobledo/savegame-editors#275]
When you complete all of the shrines you are supposed to get a special reward. If you use the editor to complete all shrines you lose the ability to get the reward.

**Comment by marcrobledo** [comment]
Yes. The editor only sets those shrines as completed but still is missing a lot of unknown flags that are probably a requirement for the game to detect if you've done a legit progress during your gameplay.

&nbsp;

This is the biggest issue of using cheats and/or editing saves, there might be unknown side effects. Always use them on your own responsibility and keep a backup of your savegames before editing.
