### ISSUE TITLE
 Trying to upload a progress.sav file just doesn't so anything.

### ISSUE THREAD

**Issue by PokyBread** [marcrobledo/savegame-editors#276]
<img width="2500" alt="Screenshot 2023-05-29 at 15 27 54" src="https://github.com/marcrobledo/savegame-editors/assets/79985109/f1de1141-86cb-4127-b85c-5aaec88f9551">

Trying to upload a progress.sav file just doesn't so anything

**Comment by marcrobledo** [comment]
Can you post here your `progress.sav` so I can take a look at it?

**Comment by PokyBread** [comment]
[progress.sav.zip](https://github.com/marcrobledo/savegame-editors/files/11599698/progress.sav.zip)
Just a normal jailbroken switch.

**Comment by PokyBread** [comment]
<img width="779" alt="Screenshot 2023-05-30 at 13 07 27" src="https://github.com/marcrobledo/savegame-editors/assets/79985109/cc3b6427-9216-4a18-9ada-e4e28414d7d8">
I'm not sure but this might help.

**Comment by JimZiii** [comment]
> [progress.sav.zip](https://github.com/marcrobledo/savegame-editors/files/11599698/progress.sav.zip) Just a normal jailbroken switch.

![Screenshot_20230530_193711_Chrome](https://github.com/marcrobledo/savegame-editors/assets/7854537/9b51d9b6-ed18-459f-96a7-82fc9df22efc)
Opens just fine, probably your browser, try a different one
