### ISSUE TITLE
ToTK: All Shrines and/or Lightroots Marked

### ISSUE THREAD

**Issue by iMaxed0utHD** [marcrobledo/savegame-editors#277]
Is it possible to have a 3rd option for all shrines and/or Lightroots marked (with stamps) rather than Found/Activated? Similar to how the Koroks are currently so that I can still go and find them and explore rather than have it's teleporter active.

**Comment by marcrobledo** [comment]
I just added this feature in 89ae228, let me know if it works :-)

**Comment by iMaxed0utHD** [comment]
> I just added this feature in 89ae228, let me know if it works :-)

I'll check it in a few hours when I get home ^^ Thanks man! You are so quick to address these all while enjoying the game yourself! Don't work to hard! 😃

**Comment by Truinto** [comment]
Does this place ore markers? I did find a bunch placed I didn't put there. But no shrine in sight. Could be hidden shrines tho.
However I also found 4 shrines which had no marker. So I am pretty certain it did not work as intended.

**Comment by marcrobledo** [comment]
> Does this place ore markers? I did find a bunch placed I didn't put there. But no shrine in sight. Could be hidden shrines tho. However I also found 4 shrines which had no marker. So I am pretty certain it did not work as intended.

Theorically, hidden shrines are also pinned (yes, with ore markers).

Coordinates were borrowed from game files. Could be the Z coordinate is placing them in a wrong map (sky/surface)? Can you check out those shrines you found without marker if their marker was exactly in the opposite map?

Also, remember there is a limit of 300 pins. Could be also that it didn't put all the pins if you reached the limit.

**Comment by Truinto** [comment]
I marked shrines, then used the leftover for about 200 korok markers.
I did find at least one match. The map layer is fine. But it also marked shrines I definitely had before. E.g. the shrine in Kakariko is marked, even tho had finished it ages ago.
Perhaps the flags for shrine completion has errors?

**Comment by dpyron325** [comment]
> Is it possible to have a 3rd option for all shrines and/or Lightroots marked (with stamps) rather than Found/Activated? Similar to how the Koroks are currently so that I can still go and find them and explore rather than have it's teleporter active.

Yes. There's an option for that on this save game editor page for it.
 https://www.marcrobledo.com/savegame-editors/zelda-totk/

Cheers :)

**Comment by Truinto** [comment]
Shrines seem to work now. I found the last 50 shrines, which were all correctly marked.
