### ISSUE TITLE
BOTW: Daruk's Protection bug ?

### ISSUE THREAD

**Issue by MJr0019** [marcrobledo/savegame-editors#278]
Hello help me!

In Zelda Breath of the Wild, it has the power: Daruk's Protection.

Whenever I played and took this power when I take an attack it is reflected by Daruk in spirit!

But watching some videos on the internet, I see that there should also be a red shield around Link, when he holds ZL.
Power works normally but the red shield does not, it does not appear, does anyone know why?

**Comment by marcrobledo** [comment]
Are you playing in an emulator by any chance?

**Comment by MJr0019** [comment]
No, Switch v1

**Comment by marcrobledo** [comment]
I'm sorry it's been some time since last time I played BOTW so I've forgotten most of it.

What edits did you do in the editor?

**Comment by MJr0019** [comment]
Hello help me please!

I playing Switch , In Zelda Breath of the Wild, it has the power: Daruk's Protection.

Whenever I played and took this power when I take an attack it is reflected by Daruk in spirit!

But watching some videos on the internet, I see that there should also be a red shield or red orb around Link, when he holds ZL button.

The Power works normally but the red shield around Link , it does not appear, does anyone know why?

Here are my savedata in Master Mode:

https://www.dropbox.com/s/mzntyptgkedtn3g/MarcilioJr%20-%20Com%20Mod%20Edit.zip?dl=0

in folder 6,  red shield around Link appear.

in folder 7,  red shield around Link not appear, this save is 100%

Have any Flag to ative on save 7 ?

**Comment by MJr0019** [comment]
https://github.com/marcrobledo/savegame-editors/issues/353
