### ISSUE TITLE
Having an issue at the second time using your tool...

### ISSUE THREAD

**Issue by alexbaws159** [marcrobledo/savegame-editors#28]
NOTHING works entirely everytime I do the good procedure , nothing works. The first time I did it was for master sword unbreak +15 to make it legit. But after the second time to apply unbreak and + 10 to hylian shield or another stuff... doesnt worked. everything doesnt work anymore and I did the good procedure I dont know what to say or do now im just stuck :/

**Comment by marcrobledo** [comment]
The modifier editor works fine. It must be something wrong in your place. Are you sure you are injecting in the correct slot?

**Comment by alexbaws159** [comment]
Yeah idk why it worked once , I did exactly the same thing and doesnt work
but anyways im no longer using cheats. Idk probably someone had the same
issue no use if its only in my case.
