### ISSUE TITLE
[TOTK] Request: Discover all locations

### ISSUE THREAD

**Issue by Sensei412** [marcrobledo/savegame-editors#280]
Just like the BOTW editor. Including Depths and Sky Islands

**Comment by marcrobledo** [comment]
Got the coordinates already for locations, but not the flags.

**Comment by Karlos007** [comment]
I can help if you want
I was bored and got the 58 stupid wells

**Comment by marcrobledo** [comment]
> I can help if you want I was bored and got the 58 stupid wells

Sure! Since they are 58, I'm pretty sure it will be easy to get the correct order and match them to the coordinates.

**Comment by Karlos007** [comment]
yep i still don't have the locations

The hashes (2 flags per well idk why)
[Hash_Wells.txt](https://github.com/marcrobledo/savegame-editors/files/11601769/Hash_Wells.txt)

The names (probably different order)
[NameList_Wells.txt](https://github.com/marcrobledo/savegame-editors/files/11601762/NameList_Wells.txt)

And 2 progress.sav to compare, one with 0 and the other with 58 (Thanks to cheat engine)
[sav_wells.zip](https://github.com/marcrobledo/savegame-editors/files/11601772/sav_wells.zip)

**Comment by marcrobledo** [comment]
> yep i still don't have the locations
> 
> The hashes and offsets (2 flags per well idk why but makes it harder to test) [Hash_Wells.txt](https://github.com/marcrobledo/savegame-editors/files/11601769/Hash_Wells.txt) [Hard_Offsets_Wells.txt](https://github.com/marcrobledo/savegame-editors/files/11601984/Hard_Offsets_Wells.txt)
> 
> The names (probably different order) [NameList_Wells.txt](https://github.com/marcrobledo/savegame-editors/files/11601762/NameList_Wells.txt)
> 
> And 2 progress.sav to compare, one with 0 and the other with 58 (Thanks to cheat engine) [sav_wells.zip](https://github.com/marcrobledo/savegame-editors/files/11601772/sav_wells.zip)
> 
> Doing this 1 by 1 is too slow but here are some examples 5C09B4C1 Korok - Room of Awakening 0343 -1756 2282 D48A39A6-Lurelin Village Well 2941 -3378 -0004 2DBA628C-Lurelin Village Well 2941 -3378 -0004

As of your well hashes...

You seem to be mixing `IsVisitLocation.Well_XXX` and `IsVisitLocationArea_CaveEntrance.XXX`, that's why you got twice the hashes.

There are exactly 59 `IsVisitLocation.Well_XXX`, though there are 289 `IsVisitLocationArea_CaveEntrance.XXX`. I figure some wells have an additional location that counts as a cave?

It would be interesting to see which ones count towards the 100%.

**Comment by Karlos007** [comment]
> > yep i still don't have the locations
> > The hashes and offsets (2 flags per well idk why but makes it harder to test) [Hash_Wells.txt](https://github.com/marcrobledo/savegame-editors/files/11601769/Hash_Wells.txt) [Hard_Offsets_Wells.txt](https://github.com/marcrobledo/savegame-editors/files/11601984/Hard_Offsets_Wells.txt)
> > The names (probably different order) [NameList_Wells.txt](https://github.com/marcrobledo/savegame-editors/files/11601762/NameList_Wells.txt)
> > And 2 progress.sav to compare, one with 0 and the other with 58 (Thanks to cheat engine) [sav_wells.zip](https://github.com/marcrobledo/savegame-editors/files/11601772/sav_wells.zip)
> > Doing this 1 by 1 is too slow but here are some examples 5C09B4C1 Korok - Room of Awakening 0343 -1756 2282 D48A39A6-Lurelin Village Well 2941 -3378 -0004 2DBA628C-Lurelin Village Well 2941 -3378 -0004
> 
> As of your well hashes...
> 
> You seem to be mixing `IsVisitLocation.Well_XXX` and `IsVisitLocationArea_CaveEntrance.XXX`, that's why you got twice the hashes.
> 
> There are exactly 59 `IsVisitLocation.Well_XXX`, though there are 289 `IsVisitLocationArea_CaveEntrance.XXX`. I figure some wells have an additional location that counts as a cave?
> 
> It would be interesting to see which ones count towards the 100%.

I tested live with cheat engine and the % only increased when both flags where 1
also the well icon doesn't appear unless both are 1

```
              <Description>"Kakariko Village Well"</Description>
              <VariableType>Byte</VariableType>
              <Address>27885AF1D6E</Address>

              <Description>"Kakariko Village Well"</Description>
              <VariableType>Byte</VariableType>
              <Address>27885AF1D6F</Address>

              <Description>"Kakariko Village Well"</Description>
              <VariableType>Byte</VariableType>
              <Address>27885AF3C8E</Address>

              <Description>"Kakariko Village Well"</Description>
              <VariableType>Byte</VariableType>
              <Address>27885AF3C8F</Address>
</CheatEntry>
```
If you need help identifying the hashes let me know
I unlocked them with CE because is easier for me

**Comment by marcrobledo** [comment]
I've commited some preliminary (unusable yet) work in wells and caves, [if you are curious](https://github.com/marcrobledo/savegame-editors/blob/master/zelda-totk/zelda-totk.class.location.js).

I will be swamped with work during the following days, so do not expect it anytime soon.

**Comment by Karlos007** [comment]
> I've commited some preliminary (unusable yet) work in wells and caves, [if you are curious](https://github.com/marcrobledo/savegame-editors/blob/master/zelda-totk/zelda-totk.class.location.js).
> 
> I will be swamped with work during the following days, so do not expect it anytime soon.

No problemo, i'm using my cheat table for that

may i help with something?

**Comment by marcrobledo** [comment]
This features will come at some point, can't promise when though.

Doing an issue cleanup, let's continue this discussion at #183 .
