### ISSUE TITLE
TOTK: Save issue

### ISSUE THREAD

**Issue by alexbee0816** [marcrobledo/savegame-editors#281]
I have done the whole process of backing up my current save. Going to my computer modifying my save. Replacing the save with the modified save. The whole jig yet, the modified save doesn't seem to work and goes back to my original either way. Why is this??

Let me know

**Comment by ApacheThunder** [comment]
Have you made sure you are working on the correct slot? Slot_01 from my experience is always the hard save. All the others are auto save slots.

**Comment by FrankZ20** [comment]
> Have you made sure you are working on the correct slot? Slot_01 from my experience is always the hard save. All the others are auto save slots.

yes. but some saves are different. like mine is Slot_04. So you have to try it yourself

**Comment by alexbee0816** [comment]
Yes, i've got it. You can figure out which is actually your hard save slot by using the website (Macrobledo's Save Game Editor for TOTK) and inputing each slots progess.sav's file into 6 different tabs and you will know which is YOUR correct hard save by looking at which of your tabs or save files has more playtime.

**Comment by marcrobledo** [comment]
Do not lose time with that.

Just open the `caption.sav` file in the editor and you will see that savegame thumbnail, allowing you to quickly identify your latest savegame.





> Have you made sure you are working on the correct slot? Slot_01 from my experience is always the hard save. All the others are auto save slots.
No, the manual save it is not always the same, it depends on how the player has played and saved the game, the number will change if next time you play you load a non manual savegame.

**Comment by alexbee0816** [comment]
Oh... Haha. Thanks!!
