### ISSUE TITLE
Travel medallions

### ISSUE THREAD

**Issue by Edodaddy** [marcrobledo/savegame-editors#283]
Hi cant get 2nd medillion after opening Towers.For purah pad upgrade

**Comment by marcrobledo** [comment]
Did you use any external cheat? Which edits did you do in the editor?

**Comment by Edodaddy** [comment]
No i only opened all towers before i got the location activation animation cheers for for looking into this

**Comment by marcrobledo** [comment]
I figure the game is looking for a number of open towers which is saved somewhere else.

Luckily, you might be able to fix it in the new master editor. Go to the last tab in the editor and uncheck some towers so you can unlock them legitly in-game.

**Comment by Edodaddy** [comment]
Unticked map revealed scooted round them all finished in no time got all 3 medallions cheers
