### ISSUE TITLE
TOTK: 2 new item values for fuse 

### ISSUE THREAD

**Issue by JimZiii** [marcrobledo/savegame-editors#284]
Noticed you didn't have the item values for two of my fuses so might as well share them
![Flux Construct III Core](https://github.com/marcrobledo/savegame-editors/assets/7854537/bf8ba6f1-4832-4759-a6ae-337c8d4cdd2f)
^ Flux Construct III Core
![Luminous Stone Talus Heart](https://github.com/marcrobledo/savegame-editors/assets/7854537/c00b99b2-4fac-47e3-a52b-8ec57dda96e5)
^ Luminous Stone Talus Heart

**Comment by marcrobledo** [comment]
Let's continue discussion at #270
