### ISSUE TITLE
[request] TOTK: Please add these Dragon Position Offsets

### ISSUE THREAD

**Issue by CeruleanSky** [marcrobledo/savegame-editors#285]
I have confirmed changing these changes the position of the light dragon, making it much easier to catch, even if somebody doesn't want to edit them, makes it much easier to find.

Offsets from beginning of the file (on version 1.1.2):
"Light Dragon X", "Light Dragon Z", "Light Dragon Y"
0x0005333C, 0x00053340 ,0x00053344

They are floats, Y is inverted but you probably knew that.

Example save with Light Dragon at 2555.004395, 799.999939, -2999.611084 
(2555,2999,799 on in game map)

[progress.zip](https://github.com/marcrobledo/savegame-editors/files/11604315/progress.zip)

**Comment by CeruleanSky** [comment]
Just glad I could contribute back even if it is in such a small way.  If nothing else, it is documented here and even if you go slower forward, you still got what will likely remain the best save editor for the game.

Here are more dragons, I used cheat engine's file open feature (shift+ctrl+o) which allows you to search for values in a file, then I make a save, reload the file and check for value changes to find these.  These offsets are for update 1.1.2, Y float needs to be inverted negatively.

      "Fire Dragon Dinraal"
          "Fire Dragon X"
          00053288
          "Fire Dragon Z"
          0005328C
          "Fire Dragon Y"
          00053290
      "Frost Dragon Naydra"
          "Frost Dragon X"
          00053294
          "Frost Dragon Z"
          00053298
          "Frost Dragon Y"
          0005329C
      "Electric Dragon Farosh"
          "Electric Dragon X"
          00053324
          "Electric Dragon Z"
          00053328
          "Electric Dragon Y"
          0005332C
      "Light Dragon"
          "Light Dragon X"
          0005333C
          "Light Dragon Z"
          00053340
          "Light Dragon Y"
          00053344

**Comment by marcrobledo** [comment]
Forgot to tell, I added these to the master editor yesterday!

**Comment by CeruleanSky** [comment]
Works great, thanks for also doing the Vector3d transform from what was likely rendering coordinates to map coordinates, makes it much less confusing to place something or figure out where it is.  While out of scope, if there ends up being a lot of coordinate stuff, perhaps it would be good to add something that pops up a map that shows the current location and lets you click for a new one.
