### ISSUE TITLE
[TOTK] Decayed Master Sword

### ISSUE THREAD

**Issue by Foxbound256** [marcrobledo/savegame-editors#286]
So I was messing around trying to display the master sword in links house I eventually got it but it got me thinking about other glitches items. One in particular is the decayed master sword which in the editor is called sword_70_broken or something like that. I'm not sure how easy it would be to add but would be cool to have.

**Comment by ApacheThunder** [comment]
I fiddled around and modified the editor locally to add that version of the sword to my inventory. Sadly it's pretty useless as they show up with no icon and are invisible. Appears they only work properly during the early start of the game. :(

**Comment by agentruru** [comment]
> I fiddled around and downloaded a local copy of the editor and modified it to add that version of the sword to my inventory (among a bunch of other things like spawning random crap from Stables for the hell of it. :P ). Sadly it's pretty useless as they show up with no icon and are invisible. Appears they only work properly during the early start of the game. :(

I've seen someone make a tutorial on how to get the Decayed Master Sword out of the start of the game just fine.

They made a new save after progressing enough where they could obtain a weapon that could cut through vines, performed a weapon transfer glitch to the new save where the Decayed Master Sword is on display stuck inside the tree root at the very start of the game after the whole upheaval cutscene. Then, they cut through the vines which are intended to force the player to pick up the Decayed Master Sword, however with the weapon they had transferred from the previous save, after completing the tutorial island without ever picking up the Decayed Master Sword, they can bypass the cutscene which takes the Decayed Master Sword out of your inventory never to be seen again, and simply teleport back to the tree root and keep the sword for the rest of the game.

The tutorial is in Portuguese I think, however you get the idea. https://www.youtube.com/watch?v=k4TpOijgVuY&ab_channel=Planeta8-Bits

I would've done this glitch if it doesn't mean restarting the game completely lol. I've commented before on this in another issue, I just don't want this cool sword to be accidentally overlooked as unusable! Foxbound is right about the sword's name being Weapon_Sword_070_Broken.

**Comment by Foxbound256** [comment]
> > I fiddled around and downloaded a local copy of the editor and modified it to add that version of the sword to my inventory (among a bunch of other things like spawning random crap from Stables for the hell of it. :P ). Sadly it's pretty useless as they show up with no icon and are invisible. Appears they only work properly during the early start of the game. :(
> 
> I've seen someone make a tutorial on how to get the Decayed Master Sword out of the start of the game just fine.
> 
> They made a new save after progressing enough where they could obtain a weapon that could cut through vines, performed a weapon transfer glitch to the new save where the Decayed Master Sword is on display stuck inside the tree root at the very start of the game after the whole upheaval cutscene. Then, they cut through the vines which are intended to force the player to pick up the Decayed Master Sword, however with the weapon they had transferred from the previous save, after completing the tutorial island without ever picking up the Decayed Master Sword, they can bypass the cutscene which takes the Decayed Master Sword out of your inventory never to be seen again, and simply teleport back to the tree root and keep the sword for the rest of the game.
> 
> The tutorial is in Portuguese I think, however you get the idea. https://www.youtube.com/watch?v=k4TpOijgVuY&ab_channel=Planeta8-Bits
> 
> I would've done this glitch if it doesn't mean restarting the game completely lol. I've commented before on this in another issue, I just don't want this cool sword to be accidentally overlooked as unusable! Foxbound is right about the sword's name being Weapon_Sword_070_Broken.

Yes I am aware it is obtainable but completely useless unless you want to display it. Thats kind of the reason I didn't get it is for the restart as well. Aside from displaying it, it's pretty useless in terms of a sword and is solely for decoration.

**Comment by agentruru** [comment]
> > > I fiddled around and downloaded a local copy of the editor and modified it to add that version of the sword to my inventory (among a bunch of other things like spawning random crap from Stables for the hell of it. :P ). Sadly it's pretty useless as they show up with no icon and are invisible. Appears they only work properly during the early start of the game. :(
> > 
> > 
> > I've seen someone make a tutorial on how to get the Decayed Master Sword out of the start of the game just fine.
> > They made a new save after progressing enough where they could obtain a weapon that could cut through vines, performed a weapon transfer glitch to the new save where the Decayed Master Sword is on display stuck inside the tree root at the very start of the game after the whole upheaval cutscene. Then, they cut through the vines which are intended to force the player to pick up the Decayed Master Sword, however with the weapon they had transferred from the previous save, after completing the tutorial island without ever picking up the Decayed Master Sword, they can bypass the cutscene which takes the Decayed Master Sword out of your inventory never to be seen again, and simply teleport back to the tree root and keep the sword for the rest of the game.
> > The tutorial is in Portuguese I think, however you get the idea. https://www.youtube.com/watch?v=k4TpOijgVuY&ab_channel=Planeta8-Bits
> > I would've done this glitch if it doesn't mean restarting the game completely lol. I've commented before on this in another issue, I just don't want this cool sword to be accidentally overlooked as unusable! Foxbound is right about the sword's name being Weapon_Sword_070_Broken.
> 
> Yes I am aware it is obtainable but completely useless unless you want to display it. Thats kind of the reason I didn't get it is for the restart as well. Aside from displaying it, it's pretty useless in terms of a sword and is solely for decoration.

Me personally I wanna just give it an attack up modifier and play my game with a no durability mod, using it that way. Unless you're not referring to its low attack and durability?

**Comment by marcrobledo** [comment]
Added decayed master sword.
