### ISSUE TITLE
ToTK: Found these weapon IDs not currently in the editor...

### ISSUE THREAD

**Issue by ApacheThunder** [marcrobledo/savegame-editors#287]
I found 3 bows that the editor doesn't currently have. 2 of them appear to be NPC bows? One is a glitched swallow that isn't mounted on link's back properly and another is a Great Eagle with same bug. No icon and isn't mounted on link's back properly. They both fire properly except for the glitched Great Eagle which only fires 1 arrow instead of 3. Oh and the weapon_bow_128 only fires one arrow despite being a Great Eagle bow.

My guess is these first 2 are the actual bows used by the Tulin NPC. As for weapon_bow_129, it appears as a Great Eagle Bow and is otherwise identical to the Great Eagle Bow already supported by the editor. I'm not sure if there is any difference actually. Maybe just a duplicate bow ID for that one. It fires 3 arrows properly and seems to shoot identically to the original.

But the first 2 are notable as they appear to be NPC bows. Note if the 2 NPC bows are dropped you can't pick them back up. They can't be fused to anything either (ingame via ultrahand anyways. You can pick them up and fuse them to other objects with the non weapon version of Ultrahand though). Though the weapon_bow_129 version of Great Eagle Bow can be picked up and fused to things just like the proper one. I have not tested fusing them to stuff via the editor though. (worst case the game will auto remove it from the weapon if it's not supported as I have attempted fusing non standard stuff to things as a test and the game just clears them on save load. :P )

![image](https://github.com/marcrobledo/savegame-editors/assets/11767416/e5ce6f7e-c92b-4380-928f-0978deb0c5ba)

Oh also there's Weapon_Bow_166_For_Ganondorf as well but it appears to act identical to normal Weapon_Bow_166.

EDIT: 

Some other weapon IDs I found: 

Weapon_Spear_150
This appears to be NPC version of Lightscale Trident. Suffers from similar issues to the NPC bows. Mounts weird on Link's back and can't be picked up once dropped.

Weapon_Sword_152_Main
Weapon_Sword_152_Sub
These appear to be NPC versions of the swords used by Riju. Have similar bugs to the other NPC weapons.

Weapon_Sword_070_ForGrabEvent
Version of Master Sword for certain event. It can't be equipped and is otherwise not functional. Can be dropped which shows a glowing Master Sword with Grab prompt. Nothing happens if you attempt to grab it. Ultrahand can't interact with it at all.

Weapon_Sword_071
Weapon_Sword_071_Broken
Decayed versions of Master Sword I assume. (they both show as Master Sword but with 0 damage stat and no icon). They can't be equipped. One vanishes the moment you drop it and the other drops a Master Sword that lets you interact with it but trying to pick it up doesn't do anything. Maybe they only work properly if added to inventory before the Master Sword is picked up proper in the main story quest or perhaps only usable at the very start before Link reaches the back of the Temple of Time in the sky.

Weapon_Lsword_154
NPC version of Boulder Breaker. Same behavior as the others. Though I think it may be unbreakable. Haven't tested the other NPC weapons long enough to know for sure but they might all be unbreakable perhaps?

Npc_Zelda_Torch
Torch held by Zelda? This torch is unique in that it has different icon and does 7 melee damage instead of 2 like the normal torches in the game. Can be dropped and picked up and doesn't appear to be bugged aside form having the MsgNotFound text like the prologue Master Sword. Though unlike prologue Master Sword this weapon can be broken. You can cut one tree down with it before it breaks so also does cut type damage. Normal torch is classed as a club I think so can never cut trees.

The game won't let you fuse it to other weapons (it doesn't let you select it when it's on the ground). But you can fuse other weapons to it just fine. Haven't tried but I assume it can be displayed at Link's home since it isn't the Master Sword.

**Comment by marcrobledo** [comment]
Those are nice findings!

Is any of these weapons really useful? Is any of them having its own model?
I'd really like to add only those that are playable in-gam, are not a clone of other normal weapons and are not bugged.

**Comment by ApacheThunder** [comment]
They appear to use the same model. I can do some more testing with some of the NPC swords to see if they are unbreakable or not. But yeah I imagine the Zelda torch might be the only one you'd really want to add.

**Comment by marcrobledo** [comment]
I've added Npc_Zelda_Torch :-)
Good job! Added you the credits in `equipment.js` if you don't mind.

Also, when looking for that item's default durability, I managed to find and fix a bug with the durability input fields, which were not getting their maximum value allowed updated when changing an item.

**Comment by ApacheThunder** [comment]
No problem. Glad I could contribute. :D

**Comment by agentruru** [comment]
> Those are nice findings!
> 
> Besides Zelda's torch... Is any of these weapons really useful? Is any of them having its own model? I'd really like to add only those that are playable in-game, are not a clone of other normal weapons and are not bugged.

They mention Weapon_Sword_071_Broken being unusable, however I believe the genuine Decayed Master Sword is instead with the name Weapon_Sword_070_Broken. Please try and add this to the editor if possible, I'd really love to use it in game as it just looks sick.
