### ISSUE TITLE
[TOTK] Request: Add all schema stones and Yiga schematics

### ISSUE THREAD

**Issue by Sensei412** [marcrobledo/savegame-editors#290]
As the title says. There are 34 yiga schematics and 12 schema stones. not sure if you want a save with all of them unlocked. but Im gonna do it now anyway. Attached save.

Edit: I forgot about this one but you could add an option to collect all old maps as well. For this one, an option to have all the items collected from the chest would be great. 
[progress.zip](https://github.com/marcrobledo/savegame-editors/files/11620485/progress.zip)

**Comment by Karlos007** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

This should help
<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Carlo/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Carlo/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">



. | Hash | . | Name
-- | -- | -- | --
Schematics 01 v1.0.0 Value=" | 6C8FCA57 | RealAddress=00000770" | Headlight Raft
Schematics 02 v1.0.0 Value=" | 7708C653 | RealAddress=000009A8" | Excavator
Schematics 03 v1.0.0 Value=" | FBA73B41 | RealAddress=00003968" | Raiding Plane
Schematics 04 v1.0.0 Value=" | ABC30AB3 | RealAddress=00003CE8" | Icebreaker
Schematics 05 v1.0.0 Value=" | 732C5985 | RealAddress=00004330" | Whirling Basher
Schematics 06 v1.0.0 Value=" | A7BCCF88 | RealAddress=000048C8" | Super Spring
Schematics 07 v1.0.0 Value=" | 127A75C9 | RealAddress=00004DE0" | Hot-Air Ballon
Schematics 08 v1.0.0 Value=" | 11F75220 | RealAddress=00005398" | Instant Scaffold
Schematics 09 v1.0.0 Value=" | D3F712CC | RealAddress=00005EC8" | Monocycle
Schematics 10 v1.0.0 Value=" | B625E1FC | RealAddress=00006548" | Automated Ally
Schematics 11 v1.0.0 Value=" | 0520DEA7 | RealAddress=000065F8" | Tank
Schematics 12 v1.0.0 Value=" | 97C52512 | RealAddress=000067F0" | Bomb Bouquet
Schematics 13 v1.0.0 Value=" | 3385B6C6 | RealAddress=00006F10" | Vertical Escape
Schematics 14 v1.0.0 Value=" | 260AD4D3 | RealAddress=000077C0" | Instant Kitchen
Schematics 15 v1.0.0 Value=" | 7F86E965 | RealAddress=00007D18" | Beam Spinner
Schematics 16 v1.0.0 Value=" | 047DD1A3 | RealAddress=0000A7B8" | Aerial Cannon
Schematics 17 v1.0.0 Value=" | BE350FDB | RealAddress=0000B5C0" | Charged Charger
Schematics 18 v1.0.0 Value=" | 5FADC4E3 | RealAddress=0000C1A0" | Wagon
Schematics 19 v1.0.0 Value=" | 0CDDDDBF | RealAddress=0000D1F0" | Liftoff Glider
Schematics 20 v1.0.0 Value=" | 345E7150 | RealAddress=0000DA60" | Bolt Boat
Schematics 21 v1.0.0 Value=" | 5109695F | RealAddress=0000FC70" | Bridge
Schematics 22 v1.0.0 Value=" | EEE1492C | RealAddress=00010888" | Flamethower Ballon
Schematics 23 v1.0.0 Value=" | 0CBEA150 | RealAddress=00012258" | Launch Pad
Schematics 24 v1.0.0 Value=" | A8707E8A | RealAddress=00014120" | Fishing Trawler
Schematics 25 v1.0.0 Value=" | 8476F277 | RealAddress=00014848" | Cargo Carrier
Schematics 26 v1.0.0 Value=" | 4CE68BE6 | RealAddress=00014ED8" | Three Wheeler
Schematics 27 v1.0.0 Value=" | A07798A6 | RealAddress=00014F58" | Rocket Platform
Schematics 28 v1.0.0 Value=" | 6206DA4F | RealAddress=00016058" | Floodlights
Schematics 29 v1.0.0 Value=" | B3752C42 | RealAddress=00018708" | Shock Trap
Schematics 30 v1.0.0 Value=" | 499AFA5B | RealAddress=00019658" | Rainmaker
Schematics 31 v1.0.0 Value=" | 97E22BF9 | RealAddress=0001A160" | Fanplane
Schematics 32 v1.0.0 Value=" | 542B78F1 | RealAddress=0001AD30" | Dirigible
Schematics 33 v1.0.0 Value=" | 8EBFC267 | RealAddress=0001B978" | Fanboat
Schematics 34 v1.0.0 Value=" | AF8870C6 | RealAddress=0001C580" | Sprinkler System
Schematics 35 v1.0.0 Value=" | 8FE4140A | RealAddress=0001C610" | Beam Cycle
Schematics 36 v1.0.0 Value=" | EE3DB7D1 | RealAddress=0001CE80" | Triple Cannon
Schematics 37 v1.0.0 Value=" | 41B07B33 | RealAddress=0001D260" | Scatter Trap
Schematics 38 v1.0.0 Value=" | A7CE2E78 | RealAddress=0001D7A0" | Big Rig
Schematics 39 v1.0.0 Value=" | 45F95172 | RealAddress=0001FD68" | Smoke Rocket
Schematics 40 v1.0.0 Value=" | 3F9F61FD | RealAddress=00020610" | All-Purpose Raft
Schematics 41 v1.0.0 Value=" | 14FD96AA | RealAddress=000207B0" | Beam Turret
Schematics 42 v1.0.0 Value=" | 9F4BA799 | RealAddress=00020F28" | Instant Cannon
Schematics 43 v1.0.0 Value=" | 29BCADE1 | RealAddress=00021940" | Assault Cart
Schematics 44 v1.0.0 Value=" | AAACF14D | RealAddress=00022B10" | Hovercraft
Schematics 45 v1.0.0 Value=" | 2ABB2DF0 | RealAddress=000240B8" | Instant Scaffold
Schematics 46 v1.0.0 Value=" | D7AC3FC8 | RealAddress=00024238" | Water Freezer



</body>

</html>

**Comment by marcrobledo** [comment]
Added Yiga Schematics completionism features (both map pin and unlock).

@Karlos007 I'm sorry I'm not using your data this time, since the order is wrong. I suppose you've sorted them by offset, but that wasn't the internal game order (and thus, not compatible with the pin to map feature). I already had got the correct sorted hashes myself but, anyway, thank you again as always ^_^
