### ISSUE TITLE
Fast Travel Disabled

### ISSUE THREAD

**Issue by Galvanyz** [marcrobledo/savegame-editors#294]
Good day,

First off, I appreciate end love the save editor! Though, I've ran into an issue where my fast travel is disabled. I originally left the shrines, roots, and towers untouched so I may do them myself. But I noticed I couldn't fast travel. So I went back and selected to pin all missing shrines and roots, and set all towers found. But to no avail. I went back and just activated all the towers and roots, and set all the shrines to cleared. Not sure how to fix this.

**Comment by Squall-Leonhart** [comment]
use the position editor to return to the starting sky island, and complete the 4th shrine above where you woke up.

**Comment by marcrobledo** [comment]
Did you use any other external cheat?

**Comment by FriscoTec** [comment]
If you happened to use hearts mod on Sky Island to open the doors, then the trigger to get Fast Travel was circumvented. even if you use coordinates to go to the 4th shrine- it won't have a door. :( Hopefully you can start fresh without losing too much progress, and didn't get stuck in the Depths for 12 hours

**Comment by Galvanyz** [comment]
Oh, dear. Looks like I'll be footing most of the game. Oh well, I won't complain on this, since I put this on myself. I'll just make some ZOnai contraptions to get me out of the walled-off depth areas. As for the general depths, I'll just locate the ascension pillars :)
Thank you all for your help!

**Comment by Karlos007** [comment]
That's what happens when you open the door with cheats on your first try

you can manually enable the flag 4b392ebf - Teleport unlocked

**Comment by marcrobledo** [comment]
> That's what happens when you open the door with cheats on your first try
> 
> you can manually enable the flag 4b392ebf - Teleport unlocked

I've added that flag in the Master Editor, hoping this can fix those broken savegames. Though I'm afraid cheats might have broke something else.

**Comment by snix47** [comment]
I´m sorry, how would I change that value, I can´t find it in the "Master  Editor" tab for the online save game editor. What do I  search for, or do I make a new key (somehow)? A little bit stuck.  Thanks in advance for any help.  //snix
