### ISSUE TITLE
TOTK: Save Editor Won't work 

### ISSUE THREAD

**Issue by navydudu** [marcrobledo/savegame-editors#299]
When I use the save Editor and replace the progress.sav file in my save game directory, then load back in,  link is stuck in this weird black room.
How am I meant to use it?
Also I'm on v1.1.0

**Comment by marcrobledo** [comment]
What edits did you do in the progress.sav?
Can you post your original untouched savegame so I can try to replicate the bug?

**Comment by Ouanm** [comment]
i have this issue as well, how would i post my untouched saved game and the new one

**Comment by marcrobledo** [comment]
Been trying to replicate this, the only method I found is to delete the `progress.sav `file.

Are you sure there is a `progress.sav` file in the respective folder?
