### ISSUE TITLE
Kid Icarus: Uprising Weapon Modification

### ISSUE THREAD

**Issue by LarryStandard** [marcrobledo/savegame-editors#3]
The editing of pre-existing weapons is functional so long as the weapon's actual name is not selected; and or it was already located within the game's weapon slots before editing. If a weapon is changed to another via the drop down menu or is add entirely to the weapon slot list, it will not appear within the game, and can break the weapon slot list forcing the game to crash.

**Comment by marcrobledo** [comment]
Yeah, the weapon changer does not work as expected.  I do not have any documentation about how the weapon ID is built in-game. Do you have any additional information by any chance?

The later will be fixed though :-)

**Comment by LarryStandard** [comment]
Sorry, I have no knowledge on how the game handles weapon IDs. I also have little knowledge on hex editing in relation to Kid Icarus: Uprising.

**Comment by marcrobledo** [comment]
New version will be up in a few minutes:
* you can no longer change weapon ID (until someone figures out how it really works)
* you can only select already created weapons
* negative stars added (experimental)
