### ISSUE TITLE
(Bug) seems to corrupting autobuild log even without mess with it

### ISSUE THREAD

**Issue by Shideravan** [marcrobledo/savegame-editors#301]
I haven't used the autobuild section yet (to say the truth, i didn't notice until that corrupts) but it probably corrupted the autobuild log and favorites in my save.
Now press Y in favorites isn't removing it.
I tried to import a old save to import at least some funcional autobuild, but it didn't fixed the problem.
Can you have an "clear all log" option and a checkmark where the save editor doesn't change this part of code.
I'm not sure it's your addition that did it, but since you just added it and I had the problem immediately after, I'm inferring it was the cause

**Comment by Shideravan** [comment]
I not sure if I can post the corrupted savegame directly here, but in case I can't then feel free to remove it.
[progress.zip](https://github.com/marcrobledo/savegame-editors/files/11646133/progress.zip)

**Comment by marcrobledo** [comment]
I don't exactly understand what happened. What edits did you do?
Can you post the original savegame so I can try to replicate the bug?

**Comment by Shideravan** [comment]
> I don't exactly understand what happened. What edits did you do? The autobuilder importer doesn't (or it shouldn't) write to the file unless you import a file. Can you post the original savegame so I can try to replicate the bug?

I only realized until some time later playing that the 
[progress.zip](https://github.com/marcrobledo/savegame-editors/files/11646415/progress.zip)
autobuild history was corrupted. But I have a backup from some time way before.

**Comment by Shideravan** [comment]
Probably this is related with this: https://github.com/marcrobledo/savegame-editors/issues/226

I think that just a feature to clear all the autobuild history will suffice and can be helpful for everyone that wants autobuild to return the same way it was when you first get from Master Kohga.
The research can be done just comparing a save with full history with other save without any registers as like recently get from Master Kohga or even a clean new save that will probably have this part of autobuild clean.
As autobuild history reflects in loadtime of the game, maybe this feature will be useful for even more users 😊

**Comment by Shideravan** [comment]
But as that is a very similar issue, I'll close this one
