### ISSUE TITLE
TOTK: Feature request: edit difficulty scaling

### ISSUE THREAD

**Issue by TTFH** [marcrobledo/savegame-editors#302]
After you kill certain enemies the game becomes harder, there are less red enemies and more silver ones. It would be nice to be able to edit the save to make the game easier/harder.

Here is some info about how this works on BOTW, it's similar in TOTK:
https://www.reddit.com/r/Breath_of_the_Wild/comments/8fchiq/about_difficulty_scaling_for_enemies_and_weapons/

**Comment by CeruleanSky** [comment]
@Echocolat is reversing how the XP system works this time around and has a todo on their spreadsheet.  Maybe if they find some hashes they can be shared for the editor.

**Comment by marcrobledo** [comment]
The Master Editor will include these values soon!

**Comment by marcrobledo** [comment]
You should be able to edit the enemies killed in the master editor by searching DefeatedEnemyNum. Let me know if it works.

**Comment by CeruleanSky** [comment]
If you go to https://objmap-totk.zeldamods.org/ click the magnifying glass on the left side and search for `scale:1`" you'll see a complete list of every weapon/enemy that can scale"

Source: https://www.reddit.com/r/Breath_of_the_Wild/comments/8fchiq/about_difficulty_scaling_for_enemies_and_weapons/jntbsq6/ it is the same person who did most of the BOTW reversing, the thread is in BOTW but it is a side discussion about TOTK

**Comment by TTFH** [comment]
It seems to work, I increased some values and some Bokoblins went from black to silver.
