### ISSUE TITLE
TOTK: change durability freely

### ISSUE THREAD

**Issue by LeBoxOTreats** [marcrobledo/savegame-editors#307]
Was wondering if you we could set the durability of a weapon without having to have the durability ++ modifier, like we could in the botw save editor.

Would be nice to have an unbreakable weapon that can do a lot of damage

**Comment by marcrobledo** [comment]
No, it's impossible. [Read the known issues & FAQ](https://github.com/marcrobledo/savegame-editors/wiki/TOTK-known-issues-&-FAQ)
