### ISSUE TITLE
TOTK: Can't add master sword

### ISSUE THREAD

**Issue by exjah** [marcrobledo/savegame-editors#309]
Hi, i tried to add master sword, but the sword doesn't appear in inventory.
Is there any way to fix?

**Comment by AmyRoseRose** [comment]
> Hi, i tried to add master sword, but the sword doesn't appear in inventory. Is there any way to fix?

I have a completed save if you want it.

**Comment by ChaoticG** [comment]
AF0C  是一个布尔类型   代表了大师剑的flag   如果想添加  请修改为01 但是无法查看剧情   建议维持00  并添加MSG大师剑

AF0C is a Boolean type representing the flag for the Master Sword. If you want to add it, please modify it to 01. However, you won't be able to view the plot. It's suggested to keep it at 00 and add the MSG Master Sword

**Comment by marcrobledo** [comment]
In order to make Master Sword usable, go to the Master Editor, search HaveMasterSword and check the checkbox.
