### ISSUE TITLE
Spelling on Save button

### ISSUE THREAD

**Issue by jay-deez** [marcrobledo/savegame-editors#31]
https://github.com/marcrobledo/savegame-editors/blob/858aee9bb8b211b59540c0f4ac994603d6cbf86a/zelda-botw/index.html#L161

Only a small issue, the button should be "Save changes". Not really important but it appears every time you save your file.

**Comment by marcrobledo** [comment]
Fixed in 6469e279ccd60d42ca8af490cce222c2e5783593
