### ISSUE TITLE
[TOTK] Is it impossible to change the attack power point of the material?

### ISSUE THREAD

**Issue by sand626** [marcrobledo/savegame-editors#310]
I understand that the bonus for weapons cannot be set double.
Then, is it difficult to modify the attack power of the material that fuses the weapon?

**Comment by ChaoticG** [comment]
内存修改可以达成
存档修改无法  因为这个变量的值没有出现在存档里

**Comment by marcrobledo** [comment]
As far as I know, it's impossible to change the fused weapon's power. The only way to do that is by game mods or cheats.
