### ISSUE TITLE
TOTK: Exporting the savegame from the Switch?

### ISSUE THREAD

**Issue by FrankEBailey** [marcrobledo/savegame-editors#311]
Hi, this is probably a stupid question, but how can I export the Switch savegame for TOTK so I can upload it here into the editor? I've never messed around with save exporting on Switch before so any advice would be much appreciated.

**Comment by AmyRoseRose** [comment]
> Hi, this is probably a stupid question, but how can I export the Switch savegame for TOTK so I can upload it here into the editor? I've never messed around with save exporting on Switch before so any advice would be much appreciated.

I have a completed save if you want it.

**Comment by marcrobledo** [comment]
> Hi, this is probably a stupid question, but how can I export the Switch savegame for TOTK so I can upload it here into the editor? I've never messed around with save exporting on Switch before so any advice would be much appreciated.

You need a modded Switch. Unfortunately, we cannot help you here with that :-( Hope you understand.
