### ISSUE TITLE
TOTK: Possible to change bubbel frog information?

### ISSUE THREAD

**Issue by JimZiii** [marcrobledo/savegame-editors#312]
I saw the korok values in the master editor and wondered if it's possible to do something similar with bubbel frogs and set them as defeated?

I changed my amount of bubbel gems to get all the rewards from koltin, but after handing him "all" bubbel gems for the last reward i still haven't killed all of the frogs, so a cave won't get the cleared check mark till it's frog is killed and the gem has been picked up, but now i keep getting a notification every time i pick up a gem that all frogs are gone and i should go see koltin.

Its not super important or urgent, but if you stumble over the values for the frogs, a button setting all of them as cleared would be nice.
You only get the bubbel gems from them and those are useless after you're done with koltin

**Comment by marcrobledo** [comment]
It is possible, and it will come at some point!

**Comment by marcrobledo** [comment]
Forgot to notify here, it's up already though flags and coordinates are not all correct. There are other issues discussing this.
