### ISSUE TITLE
TOTK: Horse Editor Help

### ISSUE THREAD

**Issue by AmyRoseRose** [marcrobledo/savegame-editors#313]
What is the horse number for the Appleloosas?
![Savegame Editor – The legend of Zelda_ Tears of the Kingdom - Google Chrome 06_06_2023 07_18_54](https://github.com/marcrobledo/savegame-editors/assets/134152757/2e3ff443-e6c9-47e8-b317-533a014f5add)

**Comment by Truinto** [comment]
Pretty sure that's the actor name. In this context it's probably horses with different textures.

**Comment by InkDragon** [comment]
if it helps my solid blue horse is Horse 20(uses icon 01), where as my Spotted blue is Horse 01(uses icon 05). that said I don't believe you can actually change them with the editor.

**Comment by marcrobledo** [comment]
I'm sorry, but this is not the place to ask about the game's content :-(

Let's stick to bugs and features.
