### ISSUE TITLE
TotK - Request ✦ Defeated Bosses

### ISSUE THREAD

**Issue by Karlos007** [marcrobledo/savegame-editors#315]
My last 'issue'

I can find them one by one but that would take ages.

So I only found 1

v1.0.0 Hard Offset 00009234
Hash **B27EF16F** 
Battle Talus Killed (-0109, -0802, 0036) 
https://www.zeldadungeon.net/tears-of-the-kingdom-interactive-map/?m=Talus_G20

Hope it helps

**Comment by Karlos007** [comment]
<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Carlo/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Carlo/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">



Hash | RealAddress
-- | --
9f9b40d6 | 00015E1C
25d4c463 | 0000FB4C
8b486d07 | 00006F9C
7ad63fa8 | 0001311C
169430a2 | 00021F84
1c9c116b | 000268A4
73cdc65f | 0000B004
e9a2ae7f | 00021004
802a685b | 0000AECC
905ea02e | 0000225C
7a5d5d0a | 0000B8CC
d43fd092 | 0001C4BC
d1dfb8cc | 00005F6C
5c6a95fb | 0000C9AC
d5228754 | 00000B5C
ab170b3c | 000040F4
4db447b9 | 00017BC4
e60cd4cc | 0001DA64
3668b8d6 | 000217B4
a4e8e50e | 0000E6EC
83c2df0c | 0000E66C
6a18a1f9 | 0000847C
6ee4a677 | 00011EF4
a8756648 | 00004F2C
62bcd3bc | 0000DF7C
c3244c7b | 0001793C
e1a28b21 | 00008AF4
c5b95329 | 00009884
a24823eb | 0001DDFC
186f50e4 | 0001C65C
9ddfabff | 000007C4
ef668d93 | 0001E4E4
3bad804e | 00002DEC
4d0d8fe3 | 00007B94
e0b131e6 | 00013984
be5f233a | 0002242C
49cf21a8 | 0000145C
548d830e | 00011154
a8027d0c | 00003894
e0caa12e | 0001235C
9d6b4642 | 0001BE9C
339ada62 | 000045D4
5b894eb1 | 000081BC
754b1650 | 00010CC4
70e03aea | 00000F64
7f8e8d9b | 00014964
ef027e9e | 00013064
e7d22a1e | 0000895C
88d95135 | 00018984
b166db6c | 00010BF4
a2d4c991 | 00008484
8441dcc9 | 00023FCC
09eda448 | 00018AB4
59f1c02e | 000222A4
a0b5253d | 0000F84C
c84cbb8f | 0001046C
9cc2f318 | 0002177C
6ce3aae0 | 0001798C
e58fd91e | 0000B0FC
a6e5f8f9 | 000094C4
cdd24dc3 | 00023E04
4d890430 | 0000CBAC
5debb6a6 | 0000C244
3ef68091 | 0001138C
36009a9a | 0000D6FC
eb7c4d24 | 0000F22C
c6dde95b | 00012794
0b50ee69 | 00023D54
b31a5983 | 000167AC
29a424d5 | 00017F94
6fa68bac | 0001346C
2a2157fc | 0000FFC4
082cc63a | 00027624
b27ef16f | 000139D4
33123104 | 0001E364
a121c2c7 | 0001F304
0441ff69 | 0002018C
271e2bf0 | 00000B04
ec2735c0 | 00007D6C
0e385329 | 0001CF94
8751a4d7 | 00017E94
35b7597e | 000047F4
b117ffaf | 0001865C
95fbd37d | 0001DE44
2f9108f0 | 0000EFDC
a449182a | 00016484
7f7fa936 | 0001C054
36c21c1c | 0001EF1C
5f379b38 | 0001DA34
d58c280b | 000214AC
4c5cbe28 | 0000CCCC
64eb3a85 | 0001F54C
e55fde6d | 0001F064
889c540c | 00007614
0069a6fe | 00022004
4c446633 | 000011A4
f1d7e7d3 | 0001E2A4
af9a5195 | 000241A4
d1265861 | 00006944
bf7247d8 | 0000E4FC
26a34449 | 0001D66C
51db4541 | 00000F24
d7ed1df4 | 0001CB6C
1d7597bc | 00007D24
6f741eef | 000095EC
a735405a | 0001B35C
76e36f4f | 000271FC
a94cdb3e | 0000793C
890dca7f | 000002C4
f5c1bafc | 0001343C
d100a967 | 0001197C
874571fe | 0002478C
f87c46cb | 00018184
f8130875 | 0000F334
8ab15a70 | 0001DBEC
fc24c532 | 00009F7C
3b2726f4 | 0000A714
69ae65f0 | 00012A3C
552acfc2 | 0000FEDC
2b7ba716 | 00024C34
57392eef | 0001E87C
b33d6fd6 | 0000C884
f00adc75 | 00012B0C
c8d9587b | 00020A24
814595c9 | 0000325C
c82b6159 | 0000C7AC
3fdfcf6c | 00021A34
e430c1ee | 000113C4
f00e5eaa | 00021A94
9af270b2 | 00009A74
f03a51ad | 000069FC
8fbbb9bd | 0001432C
09e986c6 | 0000C8BC
d7119323 | 0000FCBC
cefc5ebc | 00014A0C
6ba4da77 | 000078DC
4ecbbf59 | 0001CD1C
8c4d535e | 0002234C
d6b83f22 | 00015F64
fc30fbc0 | 00026524
c45b2ccc | 0002153C
e067fd28 | 0000DBB4
5d3e9af6 | 000047AC
3eafefdc | 0000D21C
608c2d3a | 00012E4C
7980d385 | 00011ACC
535c77bd | 00004A4C
b7ae3986 | 0001FD14
cbef5fc1 | 000033E4
f8e86923 | 0000A674
f2b13c3f | 0001B7E4
daacc45d | 0001A58C
11c1f160 | 00002A94
0f86acd0 | 00024FBC
ad93f5bd | 00020A3C
d791063e | 0001978C
803e47c2 | 0001CB24
8f50f2c1 | 00025174
61b1fbda | 000168B4
d5959044 | 00009B9C
e4d27c11 | 000074F4
96f03828 | 00005954
9f723ee4 | 0001D0F4
6a8df83f | 000266D4
a9aa4b3c | 0000D50C
8fd913f8 | 00012DB4
5c7a2882 | 00006C4C
0b4dcd92 | 000041AC
18295227 | 0001355C
8aa89797 | 0000CDD4
98fa3ceb | 00021834
05b33279 | 0000F8B4
ec6bdd61 | 0000EE64
d50dd4cb | 0000C68C
e04021fa | 0000B784
165f835b | 0000605C
1b7b02d4 | 00005E34
1bd37a12 | 0001AD2C
47b0bed9 | 0000544C
a09409be | 0001AB14
12dee5a0 | 00017D2C
bc9fde5a | 0001AD14
2c9f01ef | 0000A484
bb68d751 | 00007EEC
2730997d | 00009E74
4e416702 | 0001F7CC
482c5a03 | 00013A8C
58885f47 | 00009F9C
112d0d53 | 0002715C
fcc50129 | 0001CB04
1e6c7853 | 0000FE0C
321a2ff1 | 00021384
6121697c | 0000377C
c78760f8 | 00002D6C
8051953b | 0000B81C
abc9cce6 | 00025C8C
d3d07ca2 | 00006544
76147575 | 000242CC
d5999747 | 00010934
90cf50e7 | 0001B904
6442b9ef | 00019D94
4ee767ab | 00003774
b634393b | 0001CDDC
e72eb42e | 000204FC
37fbb785 | 00007D64
5bf863a5 | 0000F024
368df7ef | 00023CEC
6da07e01 | 00022514
0171233e | 00013B3C
b5a837bc | 00009B7C
27ce40e5 | 0001E7EC
d735eed8 | 000038FC
509f3803 | 000221B4
15667b8e | 0001A28C
50e7f4fd | 0000B654
3021225c | 00004D0C
76177b24 | 000156C4
a5d53120 | 0000E104
fbbdb439 | 0000E574
42211193 | 0000652C
8927dc6f | 000258BC
b579266b | 000056CC
eb5f3cf3 | 000221EC
1401fdb3 | 000155AC
5c6aa7b3 | 00010E5C
cdebf5bd | 00008034
e18248e8 | 000201F4
0dbd2e32 | 00002F5C
362e8f22 | 0001D6D4
a884f7b5 | 00027014
9f6518c2 | 0001741C
27f36153 | 00019764
f811d7cb | 00016394
77761549 | 0001956C
07204562 | 0001A2DC
5d9e92da | 00005214
1b53507f | 0000D7AC
86041e8f | 0001A7FC
7a28cc7d | 0001E88C
568cc4bd | 000195DC
4b7cd218 | 0000B824
9be62122 | 0001631C
0411bd1c | 00022C04
9ebf7572 | 0002183C
9b2adde9 | 0001B37C
c31ba41b | 0000D2FC
ffb3f46b | 00004B24
38a9f859 | 0000595C
57070b19 | 0002608C
7861acbb | 00015BBC
c522d3a7 | 0001B5E4
8e1ccab1 | 0002221C
976e9085 | 0001BABC
ef4dab11 | 00019624
9c31d47b | 00014EFC
728cddfa | 0001A9C4
51a3caad | 000014E4
9b88093e | 0001084C
a582c596 | 0000376C
06e09b0e | 00004DE4
8ef251a9 | 00026814



</body>

</html>




The gbatemp editor had the 261 hashes
But of course idk who's who

**Comment by Karlos007** [comment]
Weird.I don't know why all 261 hash are together in the game data
Is it possible to get the name?

**Comment by Karlos007** [comment]
Here are more minibosses:

-Depths-
Frox - Enemy_Mogurudo_Junior (12)
Obsidian Frox - Enemy_Mogurudo_Middle (15)
Blue-White Frox - Enemy_Mogurudo_Senior (13)
Stalnox - Enemy_Giant_Bone_AllDay (10)
Flux Construct I - Enemy_Zonau_BlockMaster_Junior (3)
Flux Construct II - Enemy_Zonau_BlockMaster_Middle (9)
Flux Construct III - Enemy_Zonau_BlockMaster_Senior (8)
Dungeon Boss (4 x 3 but not sure if they count)

-Surface-
Stalnox - Enemy_Giant_Bone (6)

-Sky-
Flux Construct I - Enemy_Zonau_BlockMaster_Junior (3)
Flux Construct I - Enemy_Zonau_BlockMaster_Junior_Beginning (1)
Flux Construct II - Enemy_Zonau_BlockMaster_Middle (4)
Flux Construct III - Enemy_Zonau_BlockMaster_Senior (7)


Only 8 hours before getting home to try.....

**Comment by marcrobledo** [comment]
> Weird.I don't know why all 261 hash are together in the game data Is it possible to get the name?

Yes. Actor names and coordinates had been already documented.

Someone (I'm not sure if I can reveal their identity?) is also cracking all hashes, but it's a process that takes some time as it must be done in brute force. I tried some weeks ago myself, but made a big mistake with the alphabet as I expected it to be the same as BOTW, but TOTK includes periods now.

**Comment by McSpazzy** [comment]
Oh no! Not my secret hash cracking identity!

**Comment by McSpazzy** [comment]
> I'll wait then, no need to duplicate hours of work.

...hours ...days ...weeks its all the same when you stare at hashcat the whole time

**Comment by McSpazzy** [comment]
@Karlos007 https://discord.gg/Jf8KwPND we have a server for discussing the internals of the games data and shiz

**Comment by Karlos007** [comment]
> @Karlos007 https://discord.gg/Jf8KwPND we have a server for discussing the internals of the games data and shiz

Thanks
Just that my skills are a bit low
I only use HxD to compare saves with trial and error 
Also a bit of Cheat Engine

**Comment by marcrobledo** [comment]
Added in 74cbcc8!
