### ISSUE TITLE
Zelda TOTK crash after edit

### ISSUE THREAD

**Issue by VileAce** [marcrobledo/savegame-editors#316]
ZTOTK Version 1.1.1
Rynjinx  1.1.855

After loading modified save the changing of inventory tabs in game is slow but everything is okay.

After changing to new armor added full set of Zora 4 star I took a picture of a previous unphotographed Fire RobeXXX and game crashed.

This is the only crash I haved experienced in ZTOTK/Ryujinx

I was able to repeat the crash by repeating the steps.  The game shows "Saving" but never moves on.

Reloading Backup saves resolves the issue.

Can send saves original and edited on request.

**Comment by marcrobledo** [comment]
That's a known issue, read the [TOTK Known Issues & FAQ](https://github.com/marcrobledo/savegame-editors/wiki/TOTK-known-issues-&-FAQ) for a solution.
