### ISSUE TITLE
[TOTK] The function of modifying the compendium cannot take effect

### ISSUE THREAD

**Issue by ConanNobita** [marcrobledo/savegame-editors#317]
When I finished changing the status of the compendium, nothing changed in the game

**Comment by ConanNobita** [comment]
I found that for a modified archive to take effect, I had to delete all the other archives and keep only one modified archive.

**Comment by ConanNobita** [comment]
It's not clear if this is a mechanic of the game.

**Comment by marcrobledo** [comment]
Please, [read the FAQ & known issues](https://github.com/marcrobledo/savegame-editors/wiki/TOTK-known-issues-&-FAQ) on how to identify the savegame file you need to modify and replace and how to replace it correctly.
