### ISSUE TITLE
[TOTK] Add Old map, Sage's Wills, and Bubbulfrogs Completion

### ISSUE THREAD

**Issue by Sensei412** [marcrobledo/savegame-editors#318]
Completion feature for Old Maps and Sage's Wills. Both Collected. Old Maps have two treasure chests, one to get the old map and another to collect the armor

Also thx for the caves and wells discovery. Maybe also add all bubbulfrogs gems collected with the frogs no longer in the caves (All caves should have a check mark next to them)

**Comment by marcrobledo** [comment]
Added old maps in a8585e4! Thank you for your contribution.

The last update comes with a big number of changes and fixes, so some features might be broken.
I'm doing an issue cleanup so I can start tracking the new issues easily.
This issue will be closed, but feel free to open a new one if the new update didn't fix your issue.
