### ISSUE TITLE
[TOTK] Compatibility with official hardware?

### ISSUE THREAD

**Issue by ThatOneExe** [marcrobledo/savegame-editors#319]
Will there be compatibility planned with official hardware? When I attempted to use the save editor with my hacked switch, my computer refused to export the file to the Micro SD card, claiming that the file had properties that could not be copied onto the drive. Is this intentional, or is this an unseen bug?

**Comment by Truinto** [comment]
There is only one save format. And it works for any device, emulated or real. The problem you are having is with your computer. Maybe you have the file open in a program; that would prevent the computer from overwriting it.

In any case, this isn't related to this editor.

**Comment by ThatOneExe** [comment]
Small update: The file refused to load because I had forgotten to adjust the korok seed value in the key items. imsofuckingstupidlmao-
But, all is working well now. Apologies for the question, and my thanks for both the advice, and to Marc for the save editor (I still have nightmares of finding BOTW's Koroks legit)

**Comment by iZachare** [comment]
You should probably close this issue since you've fixed it.
