### ISSUE TITLE
New Update Breaks Horse Editing

### ISSUE THREAD

**Issue by VisceralShad0w** [marcrobledo/savegame-editors#322]
Hi, ever since the new update I can no longer click on the horse ID to switch what number/type of horse it is. Can still edit the stats but couldn't for example, change from horse 08 to horse 09

**Comment by JDOGGOKUSSJ2** [comment]
Yeah I have same problem

**Comment by marcrobledo** [comment]
Should be fixed now!

**Comment by JDOGGOKUSSJ2** [comment]
its fixed but i have a question when i add a special horse using this editor 
(Epona,Royal,stalhorse etc) in game their faces portrait is that of a random horse
is there a way to fix it only the big horse has the correct picture)

**Comment by marcrobledo** [comment]
> its fixed but i have a question when i add a special horse using this editor (Epona,Royal,stalhorse etc) in game their faces portrait is that of a random horse is there a way to fix it only the big horse has the correct picture)

[It is a known issue](https://github.com/marcrobledo/savegame-editors/wiki/TOTK-known-issues-&-FAQ#after-changing-my-horse-in-the-editor-the-thumbnail-in-the-stable-still-shows-the-old-one).

It cannot be done easily, you would need to mess with the master editor. Or... maybe if someone datamines the whole horse data, we then might be able to get all horses icon information into the editor.
