### ISSUE TITLE
[Feedback] Please add a modification for the stamina bar

### ISSUE THREAD

**Issue by ChaoticG** [marcrobledo/savegame-editors#327]
Writing in FF FF FF 4F at 34FA4 can achieve infinite stamina bar. However, when I save it, the website seems to modify this address bar to 00000000. Could you please add a recognition function or an 'if' condition? Otherwise, I have to manually fix it once after I save it.

**Comment by marcrobledo** [comment]
Added!

That was a nice idea, I wasn't aware of infinite stamina being possible in savegame editing, thank you.
