### ISSUE TITLE
ToTK: Feature Request - Ability to reset Korok Found/Carried flags...

### ISSUE THREAD

**Issue by ApacheThunder** [marcrobledo/savegame-editors#328]
It would be nice for an option to clear/set large amounts of Korok flags as going through the master section to do this would be a real chore. Option to set Korok found flags to 421 (the minimum seeds required for max inventory) would be a nice option to have too. As some may opt to just go for max inventory and find the rest on their own rather then put them all in.

A mass reset option for the Korok Carried flags would be good too though not a priority. There's not as many of those. (only a 100 from what I recall)

**Comment by marcrobledo** [comment]
Done.
Made it so the first time you click, you only get up to 421. If you click again, you get the rest.
