### ISSUE TITLE
bubbuls location fix (maybe)

### ISSUE THREAD

**Issue by Shin0Impact** [marcrobledo/savegame-editors#329]
BUBBULS_DEFEATED:[
0x29e4a302, //GerudoDesert_0043
0xca24f955, //HyruleRidge_0004
],
i looked in the code and i might be wrong but it seems that the two hashes above point to areas that are depth entrances and as far as i know there arrent any bubbuls there.
in game it says 2 bubbuls left so it could be these two

**Comment by Shin0Impact** [comment]
i found the last bubbuls and it wasnt marked

**Comment by FleX246** [comment]
I also found the last two bubbuls that don't seem to be "marked as defeated" by the savegame editor.

I found the first one in the "Ancient Tree Stump Cave"
(Entrance: -1112, -0432, 0023).

The second then in the "Akkala Citadel Ruins Summit Cave"
(Entrance: 3293, 1492, 0395)

After I defeated the two, I was able to fulfill Koltin's wish. :-)

**Comment by FleX246** [comment]
> I also found the last two bubbuls that don't seem to be "marked as defeated" by the savegame editor.
> 
> I found the first one in the "Ancient Tree Stump Cave" (Entrance: -1112, -0432, 0023).
> 
> The second then in the "Akkala Citadel Ruins Summit Cave" (Entrance: 3293, 1492, 0395)
> 
> After I defeated the two, I was able to fulfill Koltin's wish. :-)

As I found out today, the above are not all bubbuls.
Apparently, the bubbuls are still present in almost all caves, despite being marked as defeated by the savegame editor, and you can defeat any two in order to complete the quest

**Comment by ShadowOne333** [comment]
I can confirm this.
I unlocked all the Bubbulgems with the editor yesterday, and to my surprise, Koltin still said there was one Bubbul left, but couldn't pinpoint where it was in Hyrule.
I entered any cave with a Bubbul in it, killed it and retrieved its gem, and that gave me the prompt to go to Koltin.

However, I noticed that after eating the remaining Bubbulgems, 4 were still in my inventory, and going to another cave and killing another Bubbul to grab its gem still adds to the counter, so the Bubbuls are still in the caves even after using this option from the editor.
Is removing the Bubbulgems from Key items possible with the editor? Or reducing them to 0 would make them disappear?

**Comment by marcrobledo** [comment]
Fixed in a8585e4! Thank you for your contribution.

The last update comes with a big number of changes and fixes, so some features might be broken.
I'm doing an issue cleanup so I can start tracking the new issues easily.
This issue will be closed, but feel free to open a new one if the new update didn't fix your issue.
