### ISSUE TITLE
TOTK : Autobuilder unoficial stuff

### ISSUE THREAD

**Issue by cualquiercosa327** [marcrobledo/savegame-editors#331]
Hello, as the main developer of the save data suggested, i have build this thread to share that crazy things we find while we modding the game editing the Autobuild  save part.

**Comment by cualquiercosa327** [comment]
It is awesome what it allows us..

https://twitter.com/Tankerbot/status/1665897201401298944

**Comment by marcrobledo** [comment]
#228
