### ISSUE TITLE
TOTK: Internal ID for caves and chasms

### ISSUE THREAD

**Issue by youquzhiji** [marcrobledo/savegame-editors#338]
I've been working on a similar project and I want to give you a reminder that there are some chasms internally labeled as caves,  these are Cave_GerudoDesert_0043, Cave_HyruleRidge_0004, Cave_Lanayru_0050, Cave_Lanayru_0063. Also, these caves are not labeled as caves in its name but is actually caves
` {"id": "Well_0043B", "name": "Komo Shoreline Cave", "x": 486.932709, "y": -3831.13599, "z": 8.21369934}, {"id": "Zora_Imperial_Palace", "name": "Pristine Sanctum", "x": 3708.01904, "y": 608.693726, "z": 343.502686}, {"id": "Zora_Imperial_Palace1", "name": "Pristine Sanctum", "x": 3622.3269, "y": 583.486023, "z": 170.002686}, {"id": "ZoraZonauTerminal", "name": "Ancient Zora Waterworks", "x": 3606.64111, "y": 122.201797, "z": -1.0447998}`
note the coordinates are ingame coordinates,

**Comment by marcrobledo** [comment]
Nice!

Do they have bubbuls on them?

**Comment by youquzhiji** [comment]
those all have bubbuls in them, so the total count should be 147 instead of 148

**Comment by marcrobledo** [comment]
This is very interesting.

So which ones are the wrong caves in [my list](https://github.com/marcrobledo/savegame-editors/blob/9918afb6ee307b21c6c406737fc0035cca75e64c/zelda-totk/zelda-totk.completism.js#L433)?

**Comment by youquzhiji** [comment]
Zora_Imperial_Palace //Pristine Sanctum
Zora_Imperial_Palace1 //Pristine Sanctum
these are the different entrance of the same cave

**Comment by youquzhiji** [comment]
Also a rather horrifying discovery is that each cave entrance counts separately toward the map completion, wondering if you should list all the hashes and coords in the data

**Comment by marcrobledo** [comment]
Fixed in a8585e4! Thank you for your contribution.

The last update comes with a big number of changes and fixes, so some features might be broken.
I'm doing an issue cleanup so I can start tracking the new issues easily.
This issue will be closed, but feel free to open a new one if the new update didn't fix your issue.
