### ISSUE TITLE
If I change a horse in my stable to lord of the mountain, and take it out the game crashes

### ISSUE THREAD

**Issue by Benni1703** [marcrobledo/savegame-editors#34]
So, i changed one of my horses to lord of the mountain, and when I went to take it out my game crashed

**Comment by daltonsky9** [comment]
I think its because you aren't supposted to have it registered in a stable to begin with

**Comment by Akorax** [comment]
Yeah, this is most likely not a issue with the savegame editor. I suggest to close this issue.

**Comment by elk1007** [comment]
If the save you're editing has link riding an unregistered horse, you can mod the horse he's riding to Lord of the Mountain. He can't be registered and taken out without a crash, though.

**Comment by marcrobledo** [comment]
Fixed in c9694b5f634ce900719247a7dd4e79e8498b01f7
You cannot edit stable horses to special horses.
