### ISSUE TITLE
ToTK: Armor addition: 

### ISSUE THREAD

**Issue by ApacheThunder** [marcrobledo/savegame-editors#340]
I have found the armor ID for the tunic Link wears during the prologue:

![image](https://github.com/marcrobledo/savegame-editors/assets/11767416/dbc81284-8a2c-44c8-bf88-5409fd7be17c)

It's actor id is Armor_1150_Upper

it is otherwise identical to Champion's Lethers with the only notable difference being Link's arm is not Ultrahanded with it. It has a defense stat of 5. Pretty sure it can't be upgraded though but I did not go to a fairy to test that. :P

EDIT: Went to a Great Fairy and to my surprise she will let upgrade it!

EDIT2: LOL don't attempt to upgrade it:

![image](https://github.com/marcrobledo/savegame-editors/assets/11767416/0b197869-d5c9-4130-9b10-b15230bec658)
It transforms into upgraded Tunic of Memories. :P

I guess they didn't bother setting the "you can't upgrade this" flag on it and the Actor ID it transforms into happens to be Tunic of Memories. :P

I'd say it would still be useful to have in the save editor. It's entirely possible folks will add custom Actor IDs for upgraded version of this thing via mods eventually.

**Comment by marcrobledo** [comment]
Added
