### ISSUE TITLE
TOTK: Modifiers on weapons are broken

### ISSUE THREAD

**Issue by DarkReaper231** [marcrobledo/savegame-editors#344]
![image](https://github.com/marcrobledo/savegame-editors/assets/38611351/e7322abc-fe41-454c-8793-397f7b4cb6bb)

When I get weapon in the world, it shows correct value. `Restore durability` button also restores correct value. But when I want to assign the modifier artificially, it gives it this super high value. Pressing `Restore durability` doesn't fix it to the correct value either.

**Comment by Truinto** [comment]
If you select Durability while the effect value is 0, then it will auto-select the maximum value (almost, max is actually 268435455).
So, if you don't want this, simply enter any effect value (that's the second number).
