### ISSUE TITLE
TOTK: which value would I edit to remove all the rewards from Josha's Lookout Landing location?

### ISSUE THREAD

**Issue by nbdeity** [marcrobledo/savegame-editors#345]
I made the mistake of marking the "Camera Works in the Depths" quest as complete in the editor awhile back without realizing it wouldn't count me as having got the zonaite that Josha keeps in her little area. Given I am using an autocollect Zonaite mod, she's constantly hassling me whenever i go there now and saying not to touch the materials even though i should have gotten them. Is there any way to mark them as recived so they vanish? It's a little annoying to deal with.

**Comment by Asia81** [comment]
can't you just undo the quest in the editor, marking it non completed?
Just a suggestion, i don't deal with quest editing

**Comment by nbdeity** [comment]
Oh yea, i didn't know if that'd mess anything up but i started a new save anyways so it's not too big a deal
thanks!
