### ISSUE TITLE
TOTK: Buttons to mark caves/wells/chasms/addison

### ISSUE THREAD

**Issue by InkDragon** [marcrobledo/savegame-editors#347]
i would love to have a button or buttons to add markers for missing or yet unfound caves, wells, chasms, or addison locations.

**Comment by ProfessionalismIsMyMiddleName** [comment]
Thanks for adding buttons for caves, wells and chasms! Is there any chance we get an Addison pin button?

**Comment by marcrobledo** [comment]
There are a bunch of topics discussing about map pins. Yes, at some point there will be support for other things like missing locations.
Addison sounds a little harder though. I've looked at the savegame and didn't found any boolean flags. So I'm afraid they are probably in the Bool64bit section, which sounds a little harder to implement at this moment.

Anyway, let's continue discussing about map pin features at #183
