### ISSUE TITLE
Hudson signs

### ISSUE THREAD

**Issue by youquzhiji** [marcrobledo/savegame-editors#349]
So in Japanese, hudson's name is enokida(エノキダ), addison's name is kabanda カバンダ, these might be the clues to search for related hashes

**Comment by Asia81** [comment]
I also was going to request for adding trhe missing signs, that would be appreciated

**Comment by marcrobledo** [comment]
Adding Addison map pins sounds impossible at the moment :-( I've looked at the savegame and didn't found any boolean flags. So I'm afraid they are probably in the Bool64bit section, which sounds a little harder to implement at this moment.

Anyway, let's continue discussing about map pin features at #183
