### ISSUE TITLE
Update 1.3.3 is released, no longer able to use the save editor

### ISSUE THREAD

**Issue by MattKimura** [marcrobledo/savegame-editors#35]
Now that Nintendo released update 1.3.3 today, the save editor no longer works. Also the update adds xenoblade chronicles 2 armor, and new amiibo armor for the champions.

This save editor is the best way to get amiibo armor. It would be great to have it updated!

**Comment by marcrobledo** [comment]
Updated in 6469e279ccd60d42ca8af490cce222c2e5783593.
Still missing new amiibo rewards.

**Comment by cheatfreak47** [comment]
[1.zip](https://github.com/marcrobledo/savegame-editors/files/1463695/1.zip)
Here's a save with the new amiibo armor, when I try to load it in the editor I get "invalid save file" oddly.
The armor is at Level 2 I hope that doesn't matter. ✌️

**Comment by BeyJohn** [comment]
I am also unable to load a save from botw 1.3.3, here is my the save in question if you need to take a look at it.
[game_data.zip](https://github.com/marcrobledo/savegame-editors/files/1463830/game_data.zip)

**Comment by MattKimura** [comment]
I tested one of my saves from 1.3.1 and it worked. But when I updated the game to 1.3.3 and saved, the save editor will no longer accept the save file, telling me "Invalid save file" as others mentioned above.

**Comment by marcrobledo** [comment]
I forgot to push :-P
Changes are now up.
