### ISSUE TITLE
[TotK] Unlock Map to 100%

### ISSUE THREAD

**Issue by smcvickar** [marcrobledo/savegame-editors#351]
Feature request to have an ability to set map percentage to 100% or more ideally see the locations which trigger map percentage and toggle those.

**Comment by AmyRoseRose** [comment]
> Feature request to have an ability to set map percentage to 100% or more ideally see the locations which trigger map percentage and toggle those.

Here's my 100% save with that. https://gamebanana.com/mods/449304

**Comment by smcvickar** [comment]
> > Feature request to have an ability to set map percentage to 100% or more ideally see the locations which trigger map percentage and toggle those.
> 
> Here's my 100% save with that. https://gamebanana.com/mods/449304

While slightly helpful in finding 1 of the 3 things I'm missing for 100%, your save file has weird issues (like chasms and wells with checkmarks), I'd much rather use an awesome save editor to see what I'm missing :D

**Comment by youquzhiji** [comment]
> > Feature request to have an ability to set map percentage to 100% or more ideally see the locations which trigger map percentage and toggle those.
> 
> Here's my 100% save with that. [gamebanana.com/mods/449304](https://gamebanana.com/mods/449304)

I kove how you name this a legit save but it's a hacked save by first glance

**Comment by youquzhiji** [comment]
> > > Feature request to have an ability to set map percentage to 100% or more ideally see the locations which trigger map percentage and toggle those.
> > 
> > 
> > Here's my 100% save with that. [gamebanana.com/mods/449304](https://gamebanana.com/mods/449304)
> 
> While slightly helpful in finding 1 of the 3 things I'm missing for 100%, your save file has weird issues (like chasms and wells with checkmarks), I'd much rather use an awesome save editor to see what I'm missing :D

looks like this is a legit one https://gamebanana.com/mods/450649

**Comment by marcrobledo** [comment]
A feature to unlock all locations will come at some point, but do not expect it anytime soon from me :-(


Anyway, let's continue discussing about map pin features and 100% map unlocking at #183
