### ISSUE TITLE
Durability AND Attack up.

### ISSUE THREAD

**Issue by thompa91** [marcrobledo/savegame-editors#352]
Hi there.
Is it possible for you to add like in the previous game where you could change the durability value to 6553500 and still be able to change the modifier itself for example attack up? Now in this game it says durability but it just resets if i change it whenever i have a modifier thats not durability up, is this possible or is it the game itself with the coding?

**Comment by marcrobledo** [comment]
Sorry, it's impossible.
[Read the FAQ & known issues](https://github.com/marcrobledo/savegame-editors/wiki/TOTK-known-issues-&-FAQ)
