### ISSUE TITLE
BOTW and TOTK horse editors

### ISSUE THREAD

**Issue by mjz013** [marcrobledo/savegame-editors#355]
Hi Marc,

Thank you for all your hard work with the Zelda editors, they're awesome.

However, I noticed an area of opportunity to make them better, specifically the horse editor part.

The editors do not include a "special" wild horse, Link's horse, named in the game files "GameRomHorse" (notice that it has no digits at the end of the name).

I would like to link to a old thread in gamefaqs where the user HylianAngel discoved this and goes into depth about how horses work in BOTW, I think their info will aid you greatly in improving the horse editors.

Horse thread in gamefaqs by HylianAngel: https://gamefaqs.gamespot.com/boards/189707-the-legend-of-zelda-breath-of-the-wild/76109671

Here's how the horse in question appears in both the BOTW and TOTK editors as of now.

BOTW: https://imgur.com/eqitc9G

TOTK: https://imgur.com/XoCr8KD

Thank you

**Comment by marcrobledo** [comment]
Added GameRomHorse in a8585e4 in both BOTW and TOTK! Thank you for your contribution.

I haven't tested it though, so I'm leaving the issue open until you confirm it works :-)
