### ISSUE TITLE
After modifying the number of defeated bubbuls, you can't get Koltin's reward

### ISSUE THREAD

**Issue by supyhhg** [marcrobledo/savegame-editors#358]
I unlocked all the Bubbulgems  ,Koltin still said there waszero Bubbul left, but couldn't pinpoint where it was in Hyrule.

**Comment by Karlos007** [comment]
You can use the master editor

DefeatedEnemyNum.Enemy_CaveMaster_000 = 147
ExchangedCaveMasterMedalNum	= 147
Nushishop_MedalRemaining = 0
and the most important:
NushiShop_MedalComplete = true

**Comment by JonJaded** [comment]
Thank you @Karlos007

**Comment by marcrobledo** [comment]
As stated at #366, this should be fixed now!
