### ISSUE TITLE
Update 1.3.4 is released, no longer able to use the save editor

### ISSUE THREAD

**Issue by Akorax** [marcrobledo/savegame-editors#36]
This is pretty much a copy of the 1.3.3 update issue but it's the same problem. Possibly what's needed to be done is another minor tweak to the editor to make 1.3.4 files work. Currently they generate the "invalid savegame file" error.

**Comment by marcrobledo** [comment]
Could you post your 1.3.4 savegame? Thank you.

**Comment by Akorax** [comment]
[game_data.zip](https://github.com/marcrobledo/savegame-editors/files/1524353/game_data.zip)
Thanks for the quick reply. Love your little program :D

**Comment by Akorax** [comment]
*facepalm*
Just went to another computer and my save worked in the editor! Issue was probably the "clear offline storage"-part (unless you just updated the editor)
Just gotta figure out how to fix that for the other computer then...
Sorry for being stupid >.<
