### ISSUE TITLE
TOTK Save Editor Question (Shrine Quests)

### ISSUE THREAD

**Issue by MonfGeiger** [marcrobledo/savegame-editors#365]
i finally hunted down all 120 lightbloom stalks in the depths, and tbh, im not too keen on hunting down the shrines anymore, so im looking at unlocking them all via the save editor, but then there's the ones locked behind the shrine quests. if i unlock all the shrines, will that also auto-complete the shrines with quests, or has there been any jankiness from using the save editor to unlock all the shrines? These are the ones i finished so far
![L1](https://github.com/marcrobledo/savegame-editors/assets/28603306/8d7bc9a2-d968-4dea-b616-b15bc6df9933)
![L2](https://github.com/marcrobledo/savegame-editors/assets/28603306/ca6f8d11-429e-472f-be20-2771330157d2)

**Comment by PratyushGarg48** [comment]
I unlocked all the shrines from editor but now when I go to complete the shrine I get an incompleable shrine quest cause after bringing the crystal nothing happens

**Comment by marcrobledo** [comment]
> I unlocked all the shrines from editor but now when I go to complete the shrine I get an incompleable shrine quest cause after bringing the crystal nothing happens

See #422
