### ISSUE TITLE
The HTTP page automatically redirects to the HTTPS page

### ISSUE THREAD

**Issue by Gokou-Ruri** [marcrobledo/savegame-editors#369]
After jumping to the https page, it is displayed that "This site can't be reached".
The Legend of Zelda: Tears of the Kingdom page everything works, but the Legend of Zelda: Breath of the Wild page has this problem.
![动画 (10)](https://github.com/marcrobledo/savegame-editors/assets/26711804/507013eb-99b9-458b-a0cb-26572edfa433)

**Comment by marcrobledo** [comment]
Yes, it forces https so it can use ServiceWorkers for cache.
You can disable it by setting the constant `FORCE_HTTPS` to false:
```
var FORCE_HTTPS=false;
```
look for that line in every editor's `index.html`.



Anyway, I noticed you are running a local webserver. You don't need that to execute the editor locally. Just open the index.html and it will be fine.
