### ISSUE TITLE
Update 1.4.0

### ISSUE THREAD

**Issue by subworx** [marcrobledo/savegame-editors#37]
Update 1.4.0 was released, editor stopped working again.
Please be so kind to fix it :)
I attached my 1.4.0 + DLC2 savegame for reference.

Thank you :D
Best regards,
sub
[game_data.zip](https://github.com/marcrobledo/savegame-editors/files/1543872/game_data.zip)

**Comment by Luneyes** [comment]
Here is mine too if you need. From the EUR version 1.4.0 + DLC 3.0. ;)
Hope to get an update soon!
Thanks a lot for your work! :D

[EUR_saves.zip](https://github.com/marcrobledo/savegame-editors/files/1544136/EUR_saves.zip)

**Comment by marcrobledo** [comment]
Added 1.4.0 support in 8b9dc22b04fd5d0aa3033ba8e225cf77c1575b0a

**Comment by subworx** [comment]
You rock, thank you very much :D
