### ISSUE TITLE
TotK: [FEATURE REQUEST] Change Symbol for Strayed Korok's

### ISSUE THREAD

**Issue by Rajvir8** [marcrobledo/savegame-editors#372]
I completely understand that due to issues many of the Strayed Korok's show there destination rather than where you go to pick them up, but this does result in a lot of confusion when for example you think it's just a flower/race and spend awhile in that area looking.

Would it be possible to assign a different symbol for the Strayed Korok's instead? For now I'll personally just leave them out of my Mini Map, and will start adding them once I've finished all the normal Korok's.

**Comment by Asia81** [comment]
Yeah that would definitly be cool, I even already suggested it 
https://github.com/marcrobledo/savegame-editors/issues/362

**Comment by Rajvir8** [comment]
> Yeah that would definitly be cool, I even already suggested it #362

I didn't see your request, but it's a lot more work to specifically look at every Korok's friend rather than the destination and would take a lot more work.

I would honestly like it more if your suggestion was taken but it's a lot to ask.

I'd be satisfied if they just changed the symbol for Strayed Korok's so I know when one is relatively nearby, and I can use the Mapgenine to then locate where the friend is.

As is right now I can't have normal Korok's, and strayed on the same map as it'll rapidly get confusing due to Flower's/races already ensuring that many Korok's aren't at their final destination.

My suggestion should be relatively simple to implement since the Save Editor itself already distinguishes itself, all that it needs to do is assign a different unused symbol rather than a Korok Leaf.

**Comment by vincent0408** [comment]
> > Yeah that would definitly be cool, I even already suggested it #362
> 
> I didn't see your request, but it's a lot more work to specifically look at every Korok's friend rather than the destination and would take a lot more work.
> 
> I would honestly like it more if your suggestion was taken but it's a lot to ask.
> 
> I'd be satisfied if they just changed the symbol for Strayed Korok's so I know when one is relatively nearby, and I can use the Mapgenine to then locate where the friend is.
> 
> As is right now I can't have normal Korok's, and strayed on the same map as it'll rapidly get confusing due to Flower's/races already ensuring that many Korok's aren't at their final destination.
> 
> My suggestion should be relatively simple to implement since the Save Editor itself already distinguishes itself, all that it needs to do is assign a different unused symbol rather than a Korok Leaf.

Try not to pin to stayed koroks and finish the 800 single ones, then pin strayed and combine with
https://www.zeldadungeon.net/tears-of-the-kingdom-interactive-map/?l=Surface&z=0&x=1258&y=0
It shows the route you have to take for strayed koroks (also the tree stump ones that you have to travel some distance)

**Comment by Rajvir8** [comment]
> Try not to pin to stayed koroks and finish the 800 single ones, then pin strayed and combine with https://www.zeldadungeon.net/tears-of-the-kingdom-interactive-map/?l=Surface&z=0&x=1258&y=0 It shows the route you have to take for strayed koroks (also the tree stump ones that you have to travel some distance)

That's my current plan yea, although I personally use this map instead, would just be nice for people who come after me to be able to pin both if a different symbol is used.
https://mapgenie.io/zelda-tears-of-the-kingdom/maps/hyrule

**Comment by marcrobledo** [comment]
Fixed in a8585e4! Thank you for your contribution.
Not only the icon has changed, but now the pin is the lost korok and not the destination ;-)

The last update comes with a big number of changes and fixes, so some features might be broken.
I'm doing an issue cleanup so I can start tracking the new issues easily.
This issue will be closed, but feel free to open a new one if the new update didn't fix your issue.
