### ISSUE TITLE
Bubbulfrogs not completing

### ISSUE THREAD

**Issue by Hithere3037** [marcrobledo/savegame-editors#375]
I hit the defeat all bubbulfrogs button but koltin says there are still two bubbulfrogs remaining. If anyone else has this issue and figured it out, where are they.

**Comment by CeruleanSky** [comment]
This is likely a duplicate of #374 

It is likely the 2 frogs that don't show up with the save editor are the Zora domain ones.  You'll visit the areas as you progress through the main story. 
One is behind the king.
After you progress Zora's domain a bit more, you'll go to a huge cavern that is under a large body of water, the 2nd frog is located there.

There is also near the bottom center of the map a well near a stable that ends up going to a cave out by the ocean, but it is likely you found that one already.

**Comment by Hithere3037** [comment]
it worked, thanks.
