### ISSUE TITLE
Pet color is coded wrongly on website.

### ISSUE THREAD

**Issue by aussieblackpig** [marcrobledo/savegame-editors#382]
I modified Lord of The mountain, and was trying to get the color of the pic in the stall closer, and it was wrong, totally.
I played around with color chard in PAINT, windows. and realised the color received was when I reversed the red and green.

OwnedHorseList.Body.PrimaryColor.Red [5]

AND

OwnedHorseList.Body.PrimaryColor.Green [5]

AND maybe all the others too? but I'm sure these two are back to forth, I had to reverse the inputs to get the color I wanted.

Thanks for your hard work guys.
CYA

**Comment by marcrobledo** [comment]
That's odd.

However, that's the original game's variable name. I cannot change that name because that's how the game was coded.

So we should blame the devs 🤣
