### ISSUE TITLE
TotK Master Sword Bonuses

### ISSUE THREAD

**Issue by NateHevens** [marcrobledo/savegame-editors#383]
Why can I no longer add a bonus to the Master Sword? Both boxes are greyed out. It worked fine in-game...

**Comment by NateHevens** [comment]
@marcrobledo They do, they just don't show. I can confirm because as a test I added attack up 1000 and it one-shot almost every enemy on the map. Pretty sure Durability up would work, too, but I use an infinite durability mod lol...

**Comment by marcrobledo** [comment]
Fair enough :-)

Let me know if it works again.

**Comment by NateHevens** [comment]
It does! Thank you so much!
