### ISSUE TITLE
Set all visited on locations broke quest

### ISSUE THREAD

**Issue by yveslancedaniel** [marcrobledo/savegame-editors#386]
The Incomplete Stable quest breaks if you set all locations as visited on TOTK

**Comment by marcrobledo** [comment]
I fixed it, but...

That was indeed the proper functionality, as some quests like that one unlock locations like shops, etc, that count towards 100% map completion.

Some days ago, someone also complained about another quest that I had to remove, and there might be more. Which means, now the visit all locations feature won't get you a 100% map. And I'm afraid some people might complain about that :-/

Anyway, if you want to fix your savegame, go to Master Editor and uncheck `BuildingMaterialsTutorial_Give`.
