### ISSUE TITLE
TOTK : 3 Missing locations but no news pins added

### ISSUE THREAD

**Issue by Asia81** [marcrobledo/savegame-editors#390]
Hello, I'm stuck at 99.87% on the map.
The editor say I miss 3 locations, but it doesn't add any pins when I try to.

![TOTK](https://github.com/marcrobledo/savegame-editors/assets/10244596/2e1c8d14-81f4-4401-9612-eca63a240d8d)

**Comment by Asia81** [comment]
I set the location to all visited, they I checked the flag in the save before and after.
Found the flag in the master editor, they're

IsVisitLocation.MinusField_MorudaMt
IsVisitLocation.MinusField_MorugaMt
IsVisitLocation.MinusField_NezuppoTrees

But I don't really know to what location they corresponds in the game, as moruda/moruga

**Comment by Asia81** [comment]
https://github.com/polarbunny/FirstPersonQuests/blob/master/StaticMsg/LocationMarker.msyt

According to this link, they're locations that I already have visited.
I'm getting headaches.

**Comment by Asia81** [comment]
Finally solved the mystery and these 3 locations, that was actually the underground.
These 3 missing locations wouldn't be pinned by the editor, hope your can fix it for other peoples.

IsVisitLocation.MinusField_MorudaMt
![Daval](https://github.com/marcrobledo/savegame-editors/assets/10244596/be497d66-542b-4cb6-b29a-2eb48bd81927)

IsVisitLocation.MinusField_MorugaMt
![Granajh](https://github.com/marcrobledo/savegame-editors/assets/10244596/4a3e090c-bfe9-44ff-b384-30e3b1c7479b)

IsVisitLocation.MinusField_NezuppoTrees
![PappettoGrove](https://github.com/marcrobledo/savegame-editors/assets/10244596/9a9e5ddb-e988-4a0c-8709-4ca36cfc9368)

**Comment by marcrobledo** [comment]
Those hashes are already in the editor code. Can you share the savegame **before** visiting those places?

**Comment by marcrobledo** [comment]
Fixed in 4e8f212a
