### ISSUE TITLE
TOTK weapon durability

### ISSUE THREAD

**Issue by Booblover22** [marcrobledo/savegame-editors#393]
Hi Just wanted to say thanks for the Hard work making this Save Editor.

My Only Issue is Weapon Durability is CAPPED to the Weapons we pick up and Unchangeable like from your BOTW editor. 
Please update editor to make the durability of weapons Unbreakable like you did for the first game unless the Creator of the game has blocked those types of changes and you are unable to fix it in editor. Its fun to have a 1 hit weapon but not after 3 or 4 hits it breaks.

**Comment by marcrobledo** [comment]
This is impossible, it's explained [here](https://github.com/marcrobledo/savegame-editors/wiki/TOTK-known-issues-&-FAQ#weaponshield-durability-cannot-get-higher-than-its-default-values).
