### ISSUE TITLE
Zelda TotK Invalid savegame file

### ISSUE THREAD

**Issue by quorax** [marcrobledo/savegame-editors#396]
Hi, I can't load my saves with error "Invalid savegame file". I tried all saves from yuzu catalog:
https://i122.fastpic.org/big/2023/0724/f1/4ec8be283d2c9db45b6e60c457bf2bf1.png

I put saves here, can you help me with loading and editing them?
https://drive.google.com/drive/folders/1hvzaxJ5aIjH1qPdy3F73pE2xF1OcAwJ4?usp=sharing

**Comment by marcrobledo** [comment]
For some reason, all your extracted files are blank :-/

Try to extract them again.

**Comment by quorax** [comment]
Now I cant load this saves in game. It starts a new game, if I chose "Load" - shows me empty list.
Is any idea how to recover this save files?

**Comment by marcrobledo** [comment]
It's impossible to recover these files, they are all blank. Something happened and corrupted them, you are going to need to restore a backup.

Anyway, this isn't related to the editor, so I'm closing the issue.

**Comment by LocalNil** [comment]
@marcrobledo I don't even know how to get save files can you help??
