### ISSUE TITLE
TOTK: Bug: Save editor broke the rebuilding mission in Lurelin Village

### ISSUE THREAD

**Issue by tiehu** [marcrobledo/savegame-editors#400]
I noticed that when I came to Lurelin Village, all the shops had been rebuilt, although I never rebuilt them. This results in some NPC conversations not being triggered properly.

By the time I noticed the bug, it had been around for a long time, and I had already edited some things before that. So at first, I wasn't sure which feature was causing the bug.

Fortunately, I regularly back up my save. So I roll back my save forward until I find a point in time where a bug hasn't appeared yet. And check what I do after that.

I think the problem lies in one of the following features:
1.Set all locations as visited
2.Set all wells as visited
3.Set all chasms as visited

These are what I did before the bug appeared. 

After looking #386, it seems most likely that "Set all locations as visited" is the cause?

Anyway, if anyone knows how to solve this problem, I'd really appreciate it.

**Comment by tiehu** [comment]
I have found the problem and it does seem to be caused by the "Set all locations as visited" feature.

For players who have already encountered this bug, to fix it, you need to uncheck the following three variables in the Master Editor:
Revive_Restaurant
Revive_TreasureShop
Revive_Inn

For developers, this bug is fixed by simply commenting the following three lines from zelda-totk.completism.js:
0x1a95a2c3, //Revive_Restaurant (Restaurant)
0x5ad5be95, //Revive_TreasureShop (Lucky Treasure Shop)
0xc1d11035, //Revive_Inn (Inn)

**Comment by marcrobledo** [comment]
Thank you a lot! I removed them from the locations and coordinates list.

Let me know if you find any other broken sidequest :-)
