### ISSUE TITLE
[TOTK]Hello , the Map pins editor did not work

### ISSUE THREAD

**Issue by Lessangel** [marcrobledo/savegame-editors#402]
I backed up and cleaned all old pins and marked the missing items on the map, when I try to restore the old pins, but it failed, nothing happened, I tried many times and different browsers, it still doesn't work. Does anyone know what should I do to make it works? Thank you very much . I use Chrome 115.0.5790.171, my game save version is 1.1.0 , this is my game save
[slot_03.zip](https://github.com/marcrobledo/savegame-editors/files/12296598/slot_03.zip)

**Comment by marcrobledo** [comment]
Can you also post the json file that is failing when imported?

**Comment by Lessangel** [comment]
here it is
[totk_mapPins.zip](https://github.com/marcrobledo/savegame-editors/files/12304406/totk_mapPins.zip)

**Comment by marcrobledo** [comment]
Should be fixed now in 5b82575!

**Comment by Lessangel** [comment]
Really thanks for your great works！
