### ISSUE TITLE
not really an issue more a question about triggered save flags

### ISSUE THREAD

**Issue by ctominna** [marcrobledo/savegame-editors#405]
when using the koltin and addison fabric can you please let us know which save flags are triggered to make it usable, i wanted to undo that but when its activated there's a notification of activating those specific flags but it doesn't mention which ones.

**Comment by marcrobledo** [comment]
They are:
- `OwnedParasailPattern.*`: parasail fabrics
- `OwnedCustomizableHorseTack_Reins.*`: horse reins
- `OwnedCustomizableHorseTack_Saddle.*`: horse saddles

Keep in mind that disabling these flags will make these items unusable even if you got them in the inventory.
