### ISSUE TITLE
Doesn't set DLC enemies to stock

### ISSUE THREAD

**Issue by ben-page** [marcrobledo/savegame-editors#42]
The Hyrule Compendium "Set to Stock" feature does not work for Molduking, Monk Maz Koshia, or Igneo Talus Titan from the Champions Ballad DLC. It says "0 pics were reseted to stock." And if you delete the images from the save directory, the pictures in game are blank.

**Comment by marcrobledo** [comment]
AFAIK, the update does not include stock pictures for new enemies and One Hit Obliterator. You must take the pictures manually.
