### ISSUE TITLE
[ZeldaTOTK] Allow Editor to support save files with additional custom flags

### ISSUE THREAD

**Issue by Waikuteru** [marcrobledo/savegame-editors#420]
Hello!

First of all, great work with the save editor, it's really useful for modding. I'm developing a Randomizer for Zelda TOTK and figured once I add a specific amount of custom flags, the save editor does not load it anymore. I'll attach a save file it occurs with. It would be really neat if such save files with additional, hundreds of custom flags could still be loaded because editing something really quick with your editor always sped things up!

If it's not too much hassle and especially possible, it would be also really cool if we could edit those custom flags in the Master Editor, but I doubt that's possible unless we provide a string table of the actual file name and not murmur3hash. But that would just be bonus and is not really the issue I opened the ticket for anyway!

Best regards
Waikuteru
[Save file.zip](https://github.com/marcrobledo/savegame-editors/files/13742628/Save.file.zip)

**Comment by marcrobledo** [comment]
Hello!

I've pushed a new version (commit 2e5d757584ab448de269a1f6215cdbd45697aaca) that should fix this for all mods that add lots of new variables. Let me know if it works!

**Comment by Waikuteru** [comment]
> Hello!
> 
> I've pushed a new version (commit [2e5d757](https://github.com/marcrobledo/savegame-editors/commit/2e5d757584ab448de269a1f6215cdbd45697aaca)) that should fix this for all mods that add lots of new variables. Let me know if it works!

Loading, editing and using the save files in the game works, thanks! Support for custom save flags in the Master Editor won't be possible, would it?

**Comment by marcrobledo** [comment]
Everything is possible... except having infinite free time to work on all my projects haha

Feel free to open a new issue for that, we can discuss possible solutions there. I cannot guarantee I'll work on it, but leaving an issue open is always a good idea because this is opensource and, who knows, someone else could make a MR sooner or later!

**Comment by Waikuteru** [comment]
> Everything is possible... except having infinite free time to work on all my projects haha
> 
> Feel free to open a new issue for that, we can discuss possible solutions there. I cannot guarantee I'll work on it, but leaving an issue open is always a good idea because this is opensource and, who knows, someone else could make a PR sooner or later!

Gotcha!
