### ISSUE TITLE
[ZeldaTOTK] Allow to edit custom flags in the Master Editor

### ISSUE THREAD

**Issue by Waikuteru** [marcrobledo/savegame-editors#423]
The title basically says it. It would be really useful to be able to change the values of custom-added variables via the Master Editor!

**Comment by marcrobledo** [comment]
As I said in the previous issue, my time is quite limited and I consider this project done. Still, I don't mind adding little features if they are feasible in little time :-)

Theoretically, this can be easily done by just editing [zelda-totk.hashes.csv](https://github.com/marcrobledo/savegame-editors/blob/master/zelda-totk/zelda-totk.hashes.csv) and adding the new variables there (following the CSV structure).
However, I'd like to keep that file clean with only the legacy variables from the base game.

I can think a few solutions for this, but I think the easiest solution would be...
To add new files called `zelda-totk-mods-xxx.hashes.csv`, (where xxx is an unique id for each mod). Every file would include the exclusive variables for each mod.
Then, the editor would parse the specific csv file if an specific mod savegame is open. However, I'm not sure how easy would be to identify the mod.

**Comment by Waikuteru** [comment]
As far as I know, hashes are not reversable so the "real" flag names must be provided, then converted to murmur3. Now, the mods contain the file "GameDataList" which carries those murmur3 flag hashes. They look like this:
`Bool:
- {DefaultValue: false, Hash: !u 0xb55a1bd2, ResetTypeValue: 17, SaveFileIndex: 0}
  - {DefaultValue: false, Hash: !u 0x8356a727, ResetTypeValue: 17, SaveFileIndex: 0}
  - {DefaultValue: false, Hash: !u 0xcea176ff, ResetTypeValue: 17, SaveFileIndex: 0}`

In addition to that, that's a me thing for overview, I have a .yml file that list those too but with their real flag name after a # comment behind the line, looking like that:
`Bool:
- {DefaultValue: false, Hash: !u 0xb55a1bd2, ResetTypeValue: 16, SaveFileIndex: 0} # Randomizer_IsFirstTimeHelloDone
  - {DefaultValue: false, Hash: !u 0xd932fa75, ResetTypeValue: 16, SaveFileIndex: 0} # Randomizer_GoalMode_IsRemoveSpecific
  - {DefaultValue: false, Hash: !u 0x365d36b5, ResetTypeValue: 16, SaveFileIndex: 0} # Randomizer_Spawn_Enemy_Drake`

What about adding a button on the Master Editor page, allowing you to import a file, then reading line for line, and if it detecs a Hash key, value pair, read the flag name after "#" at the end of the line?

**Comment by marcrobledo** [comment]
The yml file can be quickly converted to csv with a macro. Feel free to post it here and I'll see what can I do.

Adding a button to import is an option, of course. But I was trying to avoid doing changes like that due to my limited time 😅 I'll try to think of the best solution for this and decide.

**Comment by Waikuteru** [comment]
> The yml file can be quickly converted to csv with a macro. Feel free to post it here and I'll see what can I do.
> 
> Adding a button to import is an option, of course. But I was trying to avoid doing changes like that due to my limited time 😅 I'll try to think of the best solution for this and decide.

[Custom Flags Zelda TOTK.zip](https://github.com/marcrobledo/savegame-editors/files/13835307/Custom.Flags.Zelda.TOTK.zip)

**Comment by marcrobledo** [comment]
Added the import button!
Try it with this file.
[zelda-totk-randomizer.hashes.csv](https://github.com/marcrobledo/savegame-editors/files/13900838/zelda-totk-randomizer.hashes.csv)

**Comment by Waikuteru** [comment]
> Added the import button! Try it with this file. [zelda-totk-randomizer.hashes.csv](https://github.com/marcrobledo/savegame-editors/files/13900838/zelda-totk-randomizer.hashes.csv)

Thanks a ton! I edited both a boolean, as well as an integer, and it both worked in the game! This feature request is therefore completed. It'll help the modding community a lot - trust me, this game will be modded a lot on the next years!

**Comment by marcrobledo** [comment]
Glad to hear that :-)

Thank you all modders around!
