### ISSUE TITLE
playtime Zelda BotW: differences with cemu

### ISSUE THREAD

**Issue by lodgerz** [marcrobledo/savegame-editors#426]
hi, if I load my Zelda BotW WiiU savegame in the editor it says that the playtime is 50:24 hours, while on Cemu it says 76:47 hours. Why? What is the correct playtime?
Thanks.

**Comment by marcrobledo** [comment]
Cemu counts all hours the game has been running, that includes loading times, title screen, pause screen, etc.
The time in the editor is the one that is saved in the savegame, which is the one the game internally counts: only when you are controlling Link (yes, that doesn't even count cutscenes!).
