### ISSUE TITLE
Location of Addison Signs in TotK Master Editor

### ISSUE THREAD

**Issue by billnyethescienceguy29** [marcrobledo/savegame-editors#429]
I can't seem to locate the Addison signs in the Master Editor. I see a few possible entries, but shouldn't there be 81? Signs, posts, boards, addison, hudson, I can't seem to find a good search for it.

With that, on the auto-complete section on the main page, perhaps add a "view in Master Editor" link so if we need to lock 1 or 2 towers, or lock 1 korok or something, we can easily do it, instead of an all or nothing situation. In my case, the Addison signs.

**Comment by marcrobledo** [comment]
Unfortunately, Addison Signs cannot be found in Master Editor. It's been some time already, but IIRC they are stored in the metadata block.
Some months ago, I planned a metadata editor but it needs time that I do not have now.

**Comment by billnyethescienceguy29** [comment]
Okay, thank you for your response. I just wasn't sure if I was terrible at searching or if it was actually wasn't there. ha
