### ISSUE TITLE
Cant get saved editor to work on android yuzu 

### ISSUE THREAD

**Issue by Adamlee1992** [marcrobledo/savegame-editors#443]
Hi guys
So I'm trying to use save editor for botw on my odin 2 (android device). I created the new save file but when I swap my old save file nothing happens. I still load back to my old save for some reason. Not sure what I'm doing wrong. 

Appreciate any help!

**Comment by marcrobledo** [comment]
I don't think this is an issue of the savegame editor, all I can say is read the FAQ, the second and third questions are usually the most common mistakes while replacing the file:
https://github.com/marcrobledo/savegame-editors/wiki/TOTK-known-issues-&-FAQ
