### ISSUE TITLE
[TOTK] Autobuilder Import issue

### ISSUE THREAD

**Issue by Choom621** [marcrobledo/savegame-editors#449]
I tried to import a bunch of builds from hyruleworks but I could only import 2 blueprints all the .cai files are working on the first 2 slots but won't import on the rest of the slots

**Comment by marcrobledo** [comment]
Chances are they are being imported correctly, but their thumbnail isn't updating (it's cached somewhere in the console's NAND, can't remember when they are updated).

**Comment by Choom621** [comment]
I'm not sure but I don't think its being imported and its not just the thumbnail not updating since I loaded the save and only the first 2 slots show up in game.

**Comment by marcrobledo** [comment]
Do not trust the thumbnail, just select it even if it doesn't show it.

Also, it's been some time since I looked at this code but... Could be if you didn't have more than two designs stored in-game, you might not be able to replace them. Just create anything and store it.

Let me know if it works!

**Comment by Choom621** [comment]
Yup you were right I only had 2 designs stored in game so I created a bunch of random stuff and the blueprints were successfully imported except for the thumbnails but still works. Thank you.
