### ISSUE TITLE
Mario & Happy puzzle not complete 

### ISSUE THREAD

**Issue by tinman66jh** [marcrobledo/savegame-editors#451]
![Screenshot_20240721_142509_X.jpg](https://github.com/user-attachments/assets/8f194d39-b0ce-42e1-86f2-37f20efdc2b0)

Can anyone fix this? Marc is too busy. I would if I knew how.

**Comment by tinman66jh** [comment]
https://www.marcrobledo.com/savegame-editors/streetpass-mii-plaza/

**Comment by tinman66jh** [comment]
https://www.reddit.com/r/3DS/s/bw8nPksGeB
Here's a link to my hexedit chart

**Comment by AromaKitsune** [comment]
Related to #162 

When you edit the panel data for Mario & Happy (0x461F4) in the save editor, it edits the panel data for Picross 3D: Round 2 (0x46238) and vise versa. So, it edits the panel data values on the wrong offsets.

Normally, the M&H panel comes after the Tomodachi Life Friendship Fiesta panel, and the P3DR2 panel comes before the Yo-Kai Watch panel.

I took a look in the [`streetpass-mii-plaza.js`](https://github.com/marcrobledo/savegame-editors/blob/master/streetpass-mii-plaza/streetpass-mii-plaza.js) file and found out the two panel lines were swapped:
```
{Size:24,Name:'Tomodachi Life Friendship Fiesta'},
{Size:15,Name:'Picross 3D Round 2'}, // Mario & Happy should be here
{Size:24,Name:'Mario & Happy*'},     // Picross 3D: Round 2 should be here
{Size:40,Name:'YO-KAI WATCH'},
```

I swapped the M&H and P3DR2 panel lines back:
```
{Size:24,Name:'Tomodachi Life Friendship Fiesta'},
{Size:24,Name:'Mario & Happy*'},
{Size:15,Name:'Picross 3D Round 2'},
{Size:40,Name:'YO-KAI WATCH'},
```

Then I opened the `index.html` in a web browser to edit the save locally, and boom, it edits the panel data values on the correct offsets.

Here's the fixed save editor.

[StreetPass-Mii-Plaza-Save-Editor.zip](https://github.com/user-attachments/files/16351485/StreetPass-Mii-Plaza-Save-Editor.zip)

If you've used the current save editor before, you may want to open the `meet.dat` file in a hex editor, go to 0x46238 (P3DR2):
- if you see `FF FE 00`, that's fine, close a hex editor.
- if you see `FF FE ??`, replace `??` (`FE` or `FF`) with `00` and save.

For those who have this issue, please use the fixed version of the save editor until Marc fixes it.

**Comment by marcrobledo** [comment]
> Related to #162
> 
> When you edit the panel data for Mario & Happy (`0x461F4`) in a save editor, it edits the panel data for Picross 3D: Round 2 (`0x46238`) and vise versa. So, it edits the panel data's hex values on the wrong offsets.
> 
> Normally, the M&H panel comes after the Tomodachi Life Friendship Fiesta panel, and the P3DR2 panel comes before the Yo-Kai Watch panel.
> 
> I took a look in the [`streetpass-mii-plaza.js`](https://github.com/marcrobledo/savegame-editors/blob/master/streetpass-mii-plaza/streetpass-mii-plaza.js) file and found out the two panel lines were swapped:
> 
> ```
> {Size:24,Name:'Tomodachi Life Friendship Fiesta'},
> {Size:15,Name:'Picross 3D Round 2'}, // Mario & Happy should be here
> {Size:24,Name:'Mario & Happy*'},     // Picross 3D: Round 2 should be here
> {Size:40,Name:'YO-KAI WATCH'},
> ```
> 
> I swapped the M&H and P3DR2 panel lines back:
> 
> ```
> {Size:24,Name:'Tomodachi Life Friendship Fiesta'},
> {Size:24,Name:'Mario & Happy*'},
> {Size:15,Name:'Picross 3D Round 2'},
> {Size:40,Name:'YO-KAI WATCH'},
> ```
> 
> Then I opened the `index.html` file in a web browser to edit the `meet.dat` save file locally, saved it, launched StreetPass Mii Plaza, went to Puzzle Swap and bam, the panel data for M&H and P3DR2 have been edited correctly!
> 
> Here's a fixed version of the save editor, it should edit the panel data's hex values on the correct offsets.
> 
> [StreetPass-Mii-Plaza-Save-Editor.zip](https://github.com/user-attachments/files/16351485/StreetPass-Mii-Plaza-Save-Editor.zip)
> 
> If you already edited the M&H panel data using a bugged version of the save editor, you might want to open the `meet.dat` file in a hex editor and check the hex values on `0x46238` (P3DR2 panel data):
> 
>     * if you see `FF FE 00`, that's fine, close a hex editor.
> 
>     * if you see `FF FE ??`, replace `??` (`FE` or `FF`) with `00` and save.
> 
> 
> For those who have this issue, please use a fixed version of the save editor for now, until Marc fixes it.

Can you do a PR for this?

**Comment by AromaKitsune** [comment]
@marcrobledo Done :)

**Comment by marcrobledo** [comment]
Nice, thank you! :-)

**Comment by tinman66jh** [comment]
I apologize for the mixup. It was my hexedit chart that was incorrect. Thank you very much for fixing it. I appreciate all the hard work that you people do to create these editors etc. for us 3ds lovers. :)
