### ISSUE TITLE
TOTK Save editor not working

### ISSUE THREAD

**Issue by AFakeWannaCryRansomware** [marcrobledo/savegame-editors#452]
Hello, im having trouble using this save editor:
https://www.marcrobledo.com/savegame-editors/zelda-totk/
i've tried everything but it's not working, anybody got the solution?
Best regards.

**Comment by AFakeWannaCryRansomware** [comment]
i tried even the sample file, i cant get it to load

**Comment by AFakeWannaCryRansomware** [comment]
do anybody have the solution?

**Comment by GameCrazy6464** [comment]
did you find the solution? im having the same problem
