### ISSUE TITLE
Screen stuck on saving

### ISSUE THREAD

**Issue by AFakeWannaCryRansomware** [marcrobledo/savegame-editors#453]
Hello, when i use the totk save editor i load the file he gave me, and i try to save, it will be stuck on the "Saving screen".
Can anybody help me?

**Comment by AFakeWannaCryRansomware** [comment]
https://github.com/user-attachments/assets/c33a8742-6265-421f-9255-68bfb16cb98e

and it continues saving...

**Comment by AFakeWannaCryRansomware** [comment]
oh now it saved.. but it taked an eternity...
anybody got the solution on how to low the saving time?

**Comment by AFakeWannaCryRansomware** [comment]
i tried to save again but now its really stuck i think.

**Comment by marcrobledo** [comment]
![imagen](https://github.com/user-attachments/assets/bcff7f50-b10f-4cc0-a4a0-4435e11f99b0)
