### ISSUE TITLE
PISSED

### ISSUE THREAD

**Issue by ashieo1130** [marcrobledo/savegame-editors#47]
OK so I used this a little bit and now I cant load sdcaffine mods. WHat I mean is that when I load up the game with mods, link is uncontrollable. He's not there and the camera is in a weird position. I am so mad that I cant use these mods and I will do anything to use them again. PLEAS HELP ME IM SO MAD! I will get a screenshot if I can.

**Comment by daltonsky9** [comment]
It could be the combination of mods with this editor that cause it to not work
