### ISSUE TITLE
Whenever I use the editor and load in the edited save, I start a new game inside the Shrine of Resurrection.

### ISSUE THREAD

**Issue by IgnoreMyname** [marcrobledo/savegame-editors#48]
What to do? First time I added in additional items and thought perhaps that feature no longer works so second time around, I only edit colors on clothes and added weapon mods. I know I'm editing and transferring the correct save because I check the save file icon before editing and transfer back into the correct/same folder.

Or does this just not work on 5.5.2/1.4 any more?

**Comment by Zooke** [comment]
Sounds like the game is not reading the edited save file.
Not an editor issue.

**Comment by x43x61x69** [comment]
I have similar issue to this but not at the Shrine of Resurrection. It'll start from middle of nowhere (underground with water and started to fall) every time I edit the save w/o touching the location settings. (Switch)

**Comment by marcrobledo** [comment]
c9694b5f634ce900719247a7dd4e79e8498b01f7 might fix @x43x61x69 issue
