### ISSUE TITLE
TLoZ-BOTW+Update 1.5

### ISSUE THREAD

**Issue by elifasjvc** [marcrobledo/savegame-editors#49]
The editor work with last update 1.5?
Thanks in advanced.

**Comment by Zooke** [comment]
I am getting invalid save file which I assume is due to 1.5, Please update the editor Marc.
thanks.

**Comment by kmatthaie** [comment]
Is this fixed?

**Comment by qjroundy** [comment]
Well, to get you started, the file size is about 0xFAC87 (1027207 bytes) and the header id I see is 0x471B

**Comment by ThisLegitYT** [comment]
I don't understand how to downgrade. Every time i do it just updates and goes to 1.5.

**Comment by marcrobledo** [comment]
Fixed in 31a3cc9a20677cc7103c182dadd7e1989ea786f6
