### ISSUE TITLE
BOTW Editor Hardmode

### ISSUE THREAD

**Issue by Silver7x** [marcrobledo/savegame-editors#51]
The editor doesn't open any hardmode save, does somebody can help me ?

**Comment by Zooke** [comment]
Yes it does, you have updated to 1.5, but this editor only works to 1.4.1

**Comment by marcrobledo** [comment]
Fixed in 31a3cc9a20677cc7103c182dadd7e1989ea786f6

**Comment by Silver7x** [comment]
Thx u very much
