### ISSUE TITLE
Streetpass Mii Plaza Editor: Plaza Tickets are disabled (greyed out)

### ISSUE THREAD

**Issue by jewelforest** [marcrobledo/savegame-editors#55]
I completed a few puzzles, and unlocked all the hats and speech bubbles that the editor provides. I also added 100 tickets. However, my ticket plaza is greyed out and unable to be used upon injecting the save. I do have a backup.

**Comment by marcrobledo** [comment]
The ticket plaza becomes disabled after you've got all purchasable items there.
