### ISSUE TITLE
Switch savegame support

### ISSUE THREAD

**Issue by cspencer49519** [marcrobledo/savegame-editors#56]
Since we are finally able to at least dump our switch savegames, I was curious when support for theses saves might be added? I do see a commit related to switch support, maybe the save files I am using are too new? I would be glad to help test adding support. Thanks.

**Comment by cspencer49519** [comment]
If you would like a copy of a savegame please let me know. As far as I can tell mine is version 1.3.

**Comment by x43x61x69** [comment]
Obviously it can be done. The only difference is that the Switch and WiiU use different endian due to CPU arch differences.

**Comment by marcrobledo** [comment]
Post all Switch savegames you've got.
Yes, the only difference between Switch and Wii U savegames are indeed the endianness. Indeed, support for Switch savegames was successfully tested a while ago, so I don't know why it's not working anymore.

**Comment by cspencer49519** [comment]
I have to offer my complete apologies, there was some sort of problem with my savegame file, after re-saving/backing up the saves it now works! Thanks for a great tool!!!
