### ISSUE TITLE
BOTW Switch save appears invalid to editor

### ISSUE THREAD

**Issue by coggy9** [marcrobledo/savegame-editors#57]
I'm having trouble with the BOTW save editor accepting my Switch BOTW saves. Every save slot I try gives a "Invalid savegame file" error.

I've tried redumping my BOTW save a few times, each time having the same MD5 for all files and images viewable, but I'm still getting an invalid save error, even after converting them to Wii U saves using [this](https://github.com/WemI0/BOTW_SaveConv) tool. If you would like to have a look at my saves, [here](https://my.mixtape.moe/ihnpnk.tar.gz) they are, straight from my Switch.

**Comment by marcrobledo** [comment]
Thank you.
Can you tell me the update version you are using?
I'll fix it as soon you tell me the version :-)

**Comment by coggy9** [comment]
Version 1.3.0
DLC version 2.0

**Comment by marcrobledo** [comment]
Mmmm... are you sure it isn't 1.3.1?

**Comment by coggy9** [comment]
Yes. the Switch system menu and the game's main menu say [1.3.0.](https://imgur.com/a/APCo2)

**Comment by marcrobledo** [comment]
That's weird. Thank you anyway.

**Comment by marcrobledo** [comment]
Fixed in bcbcb1a7c9089235937782164188a283333d1145
