### ISSUE TITLE
The Legend of Zelda: Breath of the Wild

### ISSUE THREAD

**Issue by Zanza25** [marcrobledo/savegame-editors#58]
"Add pins to map" button is not working correctly in http://www.marcrobledo.com , when I press the button it doesn't show any message, I though: "maybe it is just not showing the message", I installed the save in my Wii U and played Zelda and doesn't show koroks locations 

other features like turn a shield super OP, change horses, adquire exclusive amiibo clothes works perfectly, I also tried to use google chrome, firefox, opera, etc. and doesn't work that feature

my game is in ver 1.4.0
DLC ver 3.0

please excuse my grammar

thank you for your time.

**Comment by marcrobledo** [comment]
Fixed in 58f7ab07b910c184099be186cfa8540ebf5b6a7a

**Comment by Zanza25** [comment]
thank you, I appreciate it
