### ISSUE TITLE
Hyrule Warriors Savegame Editor - Cannot Edit APP.BIN Twice

### ISSUE THREAD

**Issue by EggTimer32** [marcrobledo/savegame-editors#6]
Yesterday, after dumping my APP.BIN, I used the Hyrule Warriors Savegame Editor to mess with my save file (max rupees, max EXP, overpowered weapons, etc). I injected the save file back into the Wii U with no issues at all, and everything worked as expected; every weapon I created was present, I had 9,999,999 Rupees and 999 of every material, and each character would level up to 255 after defeating an enemy or two.
Today, I dumped the newest version of this save file, where I bought every badge for every character, got some new weapons, and completed a few more Adventure Mode missions. However, trying to load the APP.BIN in the Hyrule Warriors Savegame Editor gave me this screen.
![capture](https://cloud.githubusercontent.com/assets/26803553/24527967/7bbf9942-1572-11e7-8f40-8e8d4cee0916.JPG)
Yesterday, when I loaded the save file, a plethora of options appeared for me to edit, but these options are gone now. I've refreshed the page and loaded the file again to no effect. I've also tried dumping the save file again, but that also did not seem to accomplish anything.
Here's the APP.BIN I'm trying to use.
[HW-APP.zip](https://github.com/marcrobledo/savegame-editors/files/883924/HW-APP.zip)

**Comment by Kis4r4gi** [comment]
Same thing, anyone can help?

**Comment by marcrobledo** [comment]
Thanks for reporting!
Should be fixed now.

**Comment by EggTimer32** [comment]
It seems to be working now. Thank you!

**Comment by Kis4r4gi** [comment]
not working for me, same things happen, i can't see editting tabs...

**Comment by marcrobledo** [comment]
@Kis4r4gi please post your savegame so I can take a look on what's happening.
