### ISSUE TITLE
Game closes after Ganon fight in the castle.

### ISSUE THREAD

**Issue by Aambriz1988** [marcrobledo/savegame-editors#64]
Since using the Zelda BOTW tool for my switch save, when I go to defeat Ganon, the game closes. I thought maybe it was because I added the Bow of Light into my inventory. I have since removed it and the same thing happens. I also have a lot of edited weapons, shields, and bows still. Is there anything that could have been tripped in the save file that could cause the game to close? Please and thank you!

**Comment by marcrobledo** [comment]
You need a single empty space for Bow of light before you get it.

**Comment by Aambriz1988** [comment]
I figured it out... I had my first horse set to the lord of the mountain, so it kept crashing because it was trying to pull it out.😅

**Comment by DerProGamer2000** [comment]
lol that is possible? xD
