### ISSUE TITLE
Can't add game_data.sav from Switch 5.0.2

### ISSUE THREAD

**Issue by iteacha** [marcrobledo/savegame-editors#66]
I can't add the save files to the save editor, it says 'Invalid savegame file' the save files are from Switch 5.0.2, BOTW 1.5.0 and exported by CheckPoint 3.1.0 and Y'allAreNUTs v0.1.1 

[Uploading BOTW exported by CheckPoint.zip…]()
[BOTW exported by YallAreNUTs.zip](https://github.com/marcrobledo/savegame-editors/files/2019958/BOTW.exported.by.YallAreNUTs.zip)

**Comment by marcrobledo** [comment]
Fixed in 37c5b5cb64225062372412e5fcdc1138187519ab, thank you.

**Comment by DerProGamer2000** [comment]
i still have the same error
