### ISSUE TITLE
I want to translate your website

### ISSUE THREAD

**Issue by HeJerry** [marcrobledo/savegame-editors#68]
Hello, the great author, web programming language, such as HTML 5 CSS js, I do not understand, but in China there are a lot of people play legend of zelda breath of the wilde, I want to translate the text part of the editer,  Can you help me? Tell me where content should be changed?
When I change into Chinese, the contents of the item does not display the icon

**Comment by marcrobledo** [comment]
BOTW editor has grown a lot, it would deserve a code overhaul with translation support.
But for now, I cannot work on that :-(
Files you need to edit:
index.html
zelda-botw.data.js

Anyway, this is not a forum. Contact me at Twitter if you need help :-)
