### ISSUE TITLE
Switch Save game not working

### ISSUE THREAD

**Issue by DerProGamer2000** [marcrobledo/savegame-editors#72]
When i upload my save game from any of the folders 0-5 it says that its invalid.
I dumped my save using Y'allareNUTs and its 960kb in size
[Botw Switch save file.zip](https://github.com/marcrobledo/savegame-editors/files/2130049/Botw.Switch.save.file.zip)

**Comment by DerProGamer2000** [comment]
Possibly related to: https://github.com/marcrobledo/savegame-editors/issues/66

**Comment by DerProGamer2000** [comment]
i also tried it with EdiZon and checkponit all the same results

**Comment by DerProGamer2000** [comment]
System Version: 5.0.2
BOTW Version: 1.5.0 
DLC: v3

**Comment by marcrobledo** [comment]
The file is corrupted.
A v1.5.0 game_data.sav file must be 1027208kbs. Yours is smaller, it's missing information. Some files are also 0kb, which means something is wrong.
Please ask anywhere else, since this issue is not related to the editor.

**Comment by DerProGamer2000** [comment]
ohh then  its because ftpd is doing something wrong when i send the files to my pc because now when i look at the files on my sd card in my pc they are showing as 1004 kb and should now work

**Comment by DerProGamer2000** [comment]
ok yes now the files work as expected thanks for the info :)

**Comment by DerProGamer2000** [comment]
can you maybe tell me one more thing what folder should i use to edit 0-5 which ones are the autosaves and which one is my manual save
