### ISSUE TITLE
Save Editor not applying changes in BOTW

### ISSUE THREAD

**Issue by Saikora** [marcrobledo/savegame-editors#73]
For about a day now Ive been trying to apply the edited save from the editor into my game but the changes are not taking effect. Every time I try to load the save that I edited it takes me back to the room I started in and I dont have anything that I added. I use CEMU 1.12.1 and the most updated version of BOTW w/ DLC & Updates. Can you please get back as soon as possible to see if its an issue with my computer or if Im doing something wrong? Ive been replacing my save with the edited one in the same folder, but do I need to advance to a place specific to the game for it to take effect (I.E After the tutorial?) Please help ASAP. I really enjoy the results Ive seen from other players and desperately desire to try them myself. Thank you!

**Comment by marcrobledo** [comment]
You are probably doing something wrong.
If it takes you to the Shrine of resurrection with just three hearts and no items, it means the savegame got corrupted for some reason.
If it just takes you to your savegame checkpoint without any addition you made, it means you are not replacing the correct file. Make sure you choose the correct 0-5 folder.

**Comment by Saikora** [comment]
How do I prevent the savegame from being corrupted? Am I replacing the wrong thing? Ive tried every method to fix it and choosing the correct folder but it still occurs

**Comment by marcrobledo** [comment]
It's hard to tell you. It should be as easy as replacing game_data.dat.
