### ISSUE TITLE
offline mode support?

### ISSUE THREAD

**Issue by WanderMax** [marcrobledo/savegame-editors#75]
could you please add offline mode support?
if it can work locally, that sound good!

**Comment by marcrobledo** [comment]
You can download it and run locally:
https://github.com/marcrobledo/savegame-editors/releases

**Comment by WanderMax** [comment]
function is OK, but icon is blank.

**Comment by WanderMax** [comment]
function is ok, icon is blank.

**Comment by mvfsullivan** [comment]
FYI In Chrome, adding the shortcut to your desktop should give you offline access.
