### ISSUE TITLE
A few questions...

### ISSUE THREAD

**Issue by Ghost9910** [marcrobledo/savegame-editors#76]
(Referencing the BotW Save Editor found [here](https://www.marcrobledo.com/savegame-editors/zelda-botw/).

- First of all, is it possible to edit my saves from an non-Jailbroken Wii U? If so, how do I go about doing it/where would I find it?

- Second, what do the numbers mean under the abilities of weapons/shields/bows? IE. A Royal Broadsword has an attack up (star), but with a numerical value of 16. 16 what, exactly? Is this a direct number from the game, or does it mean something else?

Thanks for any help. I could use some answers.

**Comment by marcrobledo** [comment]
I'm going to answer your questions, but remember this place is for reporting issues, it's not a forum.

You need to hack a Wii U in order to extract the savegame.

Numbers are modifier values. If modifier is Attack up and value is 16, then is adding 16 points of attack to that weapon.
