### ISSUE TITLE
BOTW: Save as "Switch" save file option

### ISSUE THREAD

**Issue by lordneeko** [marcrobledo/savegame-editors#86]
@marcrobledo  I know you're not working this anymore, but it'd be awesome if you built a "Save as Switch save file" option right into your program.  Then I could pull a Wii U file, bring it in here, and save as a Switch file.

There are several OS Switch save creators that you could probably link with to do it...not sure which would make the most sense

**Comment by lordneeko** [comment]
Also, this gave gave you creds for figuring out the save file.
https://github.com/Jpe230/BOTW-Save-Editor-GUI

**Comment by marcrobledo** [comment]
This can be done. However, it would be better to build a separate tool for that.
The savegame includes more files in addition to game_data.sav, all files should be modified in order to create a valid Wii U/Switch savegame.

**Comment by marcrobledo** [comment]
I implemented it anyway, it was quite easy.

Hoping to submit all changes as soon as possible!

**Comment by lordneeko** [comment]
You're awesome! Thanks for getting back to this! I wanted to help, but
don't have the ability to try on my switch. I haven't dared hack it yet...
But that day will come soon.

**Comment by marcrobledo** [comment]
Added in 1e669041121bfcb66a77f201cc68f1ab1b0d0355
You need to click in Wii U / Switch in the top bar and it will switch automatically to the other system.
