### ISSUE TITLE
BotW: Switch Kiosk Demo Save does not open.

### ISSUE THREAD

**Issue by einso** [marcrobledo/savegame-editors#90]
The save file, which can be found in the romFS of the kiosk demo, does not open in the editor. File is attached, would love if this got fixed. 

As for why the save might not open: they did some funky stuff with the glider, where you are able to use it, but it doesn't appear ingame in the menu. It also doesn't let you leave the plateau, because the glider isn't in the inventory.

[game_data.zip](https://github.com/marcrobledo/savegame-editors/files/2954851/game_data.zip)

Edit: According to Version.txt, the save file SHOULD be a 1.0 save file. Might not fit those specifications though.

**Comment by marcrobledo** [comment]
Added Kiosk savegame support in 1e669041121bfcb66a77f201cc68f1ab1b0d0355
