### ISSUE TITLE
Download master editor?

### ISSUE THREAD

**Issue by Araraura** [marcrobledo/savegame-editors#91]
Is it possible to download the master editor for botw? There are so many things at once in this one that it just takes forever for stuff to load

**Comment by Araraura** [comment]
Or maybe at least just turn them into dropdown categories that load once you click them

**Comment by marcrobledo** [comment]
This is going to be implemenetd!

**Comment by marcrobledo** [comment]
Added in 1e669041121bfcb66a77f201cc68f1ab1b0d0355
