### ISSUE TITLE
MAX_ITEMS mistake on Switch saves

### ISSUE THREAD

**Issue by AcK77** [marcrobledo/savegame-editors#95]
In your code it's seems you set the `MAX_ITEMS` var to `410`, who is maybe due to the WiiU version?

(Here: https://github.com/marcrobledo/savegame-editors/blob/master/zelda-botw/zelda-botw.js#L14)

But during my research on the switch one, the `MAX_ITEMS` limit seems to be `420`:

As example, the "section" of `ITEMS` size is `0xD200` and the one of `ITEMS_QUANTITY` is `0xD20`.
The `STRING_SIZE` is `0x80` and the quantity is stored on `0x08` (included the hash bytes).

`0xD200` / `0x80` = 420
`0xD20` / `0x8` = 420

So I think you miss the last 10 items? or maybe I misunderstood something?

**Comment by marcrobledo** [comment]
Switch and Wii U are equally the same file (with the exception of endianness).

Can't remember why I set that limit, but you are right. I've maxed the limit up to 420 in f85532b
