### ISSUE TITLE
Save File wont load

### ISSUE THREAD

**Issue by ShadowSlash** [marcrobledo/savegame-editors#96]
Every time I try to use your web editor it says invalid save! I've tried everything please help!.

@marcrobledo

**Comment by marcrobledo** [comment]
Which savegame editor are we talking about?

Post your savegame.

**Comment by ShadowSlash** [comment]
The BOTW one, I try to upload it but it just says invalid save.. 
[BOTW.zip](https://github.com/marcrobledo/savegame-editors/files/3272548/BOTW.zip) 
Its mainly save file number 6 and 7 that I want to edit.

**Comment by exconnie** [comment]
having the same issue

**Comment by exconnie** [comment]
slot 4

**Comment by marcrobledo** [comment]
@ShadowSlash can you post exactly which BOTW version+region do you have installed in your Switch?
@exconnie you didn't post any file.

**Comment by ShadowSlash** [comment]
@marcrobledo - Version 1.6.0 - UK region

**Comment by marcrobledo** [comment]
Should be fixed in d1a143ba9ae6c31898617d0bb1bd272cad7491e8
